/* tslint:disable */
/* eslint-disable */
/**
 * auto_scaling
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface DeleteScalingGroupRequest
 */
export interface DeleteScalingGroupRequest {

    /**
     * @type {boolean}
     * @memberof DeleteScalingGroupRequest
     */
    KeepInstance?: boolean;

    /**
     * @type {string}
     * @memberof DeleteScalingGroupRequest
     */
    ScalingGroupId: string;
}
