/* tslint:disable */
/* eslint-disable */
/**
 * auto_scaling
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface DescribeScalingConfigurationsRequest
 */
export interface DescribeScalingConfigurationsRequest {

    /**
     * @type {number}
     * @memberof DescribeScalingConfigurationsRequest
     */
    PageNumber?: number;

    /**
     * @type {number}
     * @memberof DescribeScalingConfigurationsRequest
     */
    PageSize?: number;

    /**
     * @type {Array<string>}
     * @memberof DescribeScalingConfigurationsRequest
     */
    ScalingConfigurationIds?: Array<string>;

    /**
     * @type {Array<string>}
     * @memberof DescribeScalingConfigurationsRequest
     */
    ScalingConfigurationNames?: Array<string>;

    /**
     * @type {string}
     * @memberof DescribeScalingConfigurationsRequest
     */
    ScalingGroupId?: string;
}
