/* tslint:disable */
/* eslint-disable */
/**
 * auto_scaling
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface DescribeScalingInstancesRequest
 */
export interface DescribeScalingInstancesRequest {

    /**
     * @type {string}
     * @memberof DescribeScalingInstancesRequest
     */
    CreationType?: string;

    /**
     * @type {Array<string>}
     * @memberof DescribeScalingInstancesRequest
     */
    InstanceIds?: Array<string>;

    /**
     * @type {number}
     * @memberof DescribeScalingInstancesRequest
     */
    PageNumber?: number;

    /**
     * @type {number}
     * @memberof DescribeScalingInstancesRequest
     */
    PageSize?: number;

    /**
     * @type {string}
     * @memberof DescribeScalingInstancesRequest
     */
    ScalingConfigurationId?: string;

    /**
     * @type {string}
     * @memberof DescribeScalingInstancesRequest
     */
    ScalingGroupId?: string;

    /**
     * @type {string}
     * @memberof DescribeScalingInstancesRequest
     */
    Status?: string;
}
