/* tslint:disable */
/* eslint-disable */
/**
 * auto_scaling
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface InstancesDistributionForCreateScalingGroupInput
 */
export interface InstancesDistributionForCreateScalingGroupInput {

    /**
     * @type {boolean}
     * @memberof InstancesDistributionForCreateScalingGroupInput
     */
    CompensateWithOnDemand?: boolean;

    /**
     * @type {number}
     * @memberof InstancesDistributionForCreateScalingGroupInput
     */
    OnDemandBaseCapacity?: number;

    /**
     * @type {number}
     * @memberof InstancesDistributionForCreateScalingGroupInput
     */
    OnDemandPercentageAboveBaseCapacity?: number;

    /**
     * @type {boolean}
     * @memberof InstancesDistributionForCreateScalingGroupInput
     */
    SpotInstanceRemedy?: boolean;
}
