/* tslint:disable */
/* eslint-disable */
/**
 * auto_scaling
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { EipForModifyScalingConfigurationInput } from './eip-for-modify-scaling-configuration-input';
import { InstanceTypeOverrideForModifyScalingConfigurationInput } from './instance-type-override-for-modify-scaling-configuration-input';
import { VolumeForModifyScalingConfigurationInput } from './volume-for-modify-scaling-configuration-input';
 /**
 * 
 *
 * @export
 * @interface ModifyScalingConfigurationRequest
 */
export interface ModifyScalingConfigurationRequest {

    /**
     * @type {EipForModifyScalingConfigurationInput}
     * @memberof ModifyScalingConfigurationRequest
     */
    Eip?: EipForModifyScalingConfigurationInput;

    /**
     * @type {string}
     * @memberof ModifyScalingConfigurationRequest
     */
    HostName?: string;

    /**
     * @type {string}
     * @memberof ModifyScalingConfigurationRequest
     */
    HpcClusterId?: string;

    /**
     * @type {string}
     * @memberof ModifyScalingConfigurationRequest
     */
    ImageId?: string;

    /**
     * @type {string}
     * @memberof ModifyScalingConfigurationRequest
     */
    InstanceDescription?: string;

    /**
     * @type {string}
     * @memberof ModifyScalingConfigurationRequest
     */
    InstanceName?: string;

    /**
     * @type {Array<InstanceTypeOverrideForModifyScalingConfigurationInput>}
     * @memberof ModifyScalingConfigurationRequest
     */
    InstanceTypeOverrides?: Array<InstanceTypeOverrideForModifyScalingConfigurationInput>;

    /**
     * @type {Array<string>}
     * @memberof ModifyScalingConfigurationRequest
     */
    InstanceTypes?: Array<string>;

    /**
     * @type {number}
     * @memberof ModifyScalingConfigurationRequest
     */
    Ipv6AddressCount?: number;

    /**
     * @type {string}
     * @memberof ModifyScalingConfigurationRequest
     */
    KeyPairName?: string;

    /**
     * @type {string}
     * @memberof ModifyScalingConfigurationRequest
     */
    Password?: string;

    /**
     * @type {string}
     * @memberof ModifyScalingConfigurationRequest
     */
    ProjectName?: string;

    /**
     * @type {string}
     * @memberof ModifyScalingConfigurationRequest
     */
    ScalingConfigurationId: string;

    /**
     * @type {string}
     * @memberof ModifyScalingConfigurationRequest
     */
    ScalingConfigurationName?: string;

    /**
     * @type {string}
     * @memberof ModifyScalingConfigurationRequest
     */
    SecurityEnhancementStrategy?: string;

    /**
     * @type {Array<string>}
     * @memberof ModifyScalingConfigurationRequest
     */
    SecurityGroupIds?: Array<string>;

    /**
     * @type {string}
     * @memberof ModifyScalingConfigurationRequest
     */
    SpotStrategy?: string;

    /**
     * @type {string}
     * @memberof ModifyScalingConfigurationRequest
     */
    Tags?: string;

    /**
     * @type {string}
     * @memberof ModifyScalingConfigurationRequest
     */
    UserData?: string;

    /**
     * @type {Array<VolumeForModifyScalingConfigurationInput>}
     * @memberof ModifyScalingConfigurationRequest
     */
    Volumes?: Array<VolumeForModifyScalingConfigurationInput>;

    /**
     * @type {string}
     * @memberof ModifyScalingConfigurationRequest
     */
    ZoneId?: string;
}
