/* tslint:disable */
/* eslint-disable */
/**
 * auto_scaling
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { RelatedInstanceForDescribeScalingActivitiesOutput } from './related-instance-for-describe-scaling-activities-output';
 /**
 * 
 *
 * @export
 * @interface ScalingActivityForDescribeScalingActivitiesOutput
 */
export interface ScalingActivityForDescribeScalingActivitiesOutput {

    /**
     * @type {string}
     * @memberof ScalingActivityForDescribeScalingActivitiesOutput
     */
    ActivityType?: string;

    /**
     * @type {number}
     * @memberof ScalingActivityForDescribeScalingActivitiesOutput
     */
    ActualAdjustInstanceNumber?: number;

    /**
     * @type {number}
     * @memberof ScalingActivityForDescribeScalingActivitiesOutput
     */
    Cooldown?: number;

    /**
     * @type {string}
     * @memberof ScalingActivityForDescribeScalingActivitiesOutput
     */
    CreatedAt?: string;

    /**
     * @type {number}
     * @memberof ScalingActivityForDescribeScalingActivitiesOutput
     */
    CurrentInstanceNumber?: number;

    /**
     * @type {string}
     * @memberof ScalingActivityForDescribeScalingActivitiesOutput
     */
    ExpectedRunTime?: string;

    /**
     * @type {number}
     * @memberof ScalingActivityForDescribeScalingActivitiesOutput
     */
    MaxInstanceNumber?: number;

    /**
     * @type {number}
     * @memberof ScalingActivityForDescribeScalingActivitiesOutput
     */
    MinInstanceNumber?: number;

    /**
     * @type {Array<RelatedInstanceForDescribeScalingActivitiesOutput>}
     * @memberof ScalingActivityForDescribeScalingActivitiesOutput
     */
    RelatedInstances?: Array<RelatedInstanceForDescribeScalingActivitiesOutput>;

    /**
     * @type {string}
     * @memberof ScalingActivityForDescribeScalingActivitiesOutput
     */
    ResultMsg?: string;

    /**
     * @type {string}
     * @memberof ScalingActivityForDescribeScalingActivitiesOutput
     */
    ScalingActivityId?: string;

    /**
     * @type {string}
     * @memberof ScalingActivityForDescribeScalingActivitiesOutput
     */
    ScalingGroupId?: string;

    /**
     * @type {string}
     * @memberof ScalingActivityForDescribeScalingActivitiesOutput
     */
    StatusCode?: string;

    /**
     * @type {string}
     * @memberof ScalingActivityForDescribeScalingActivitiesOutput
     */
    StoppedAt?: string;

    /**
     * @type {string}
     * @memberof ScalingActivityForDescribeScalingActivitiesOutput
     */
    TaskCategory?: string;
}
