/* tslint:disable */
/* eslint-disable */
/**
 * auto_scaling
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { InstanceProtectionResultForSetInstancesProtectionOutput } from './instance-protection-result-for-set-instances-protection-output';
 /**
 * 
 *
 * @export
 * @interface SetInstancesProtectionResponse
 */
export interface SetInstancesProtectionResponse {

    /**
     * @type {Array<InstanceProtectionResultForSetInstancesProtectionOutput>}
     * @memberof SetInstancesProtectionResponse
     */
    InstanceProtectionResults?: Array<InstanceProtectionResultForSetInstancesProtectionOutput>;
}
