/* tslint:disable */
/* eslint-disable */
/**
 * smc
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface DescribeMigrationSystemSupportTypesRequest
 */
export interface DescribeMigrationSystemSupportTypesRequest {

    /**
     * @type {string}
     * @memberof DescribeMigrationSystemSupportTypesRequest
     */
    OS: string;

    /**
     * @type {string}
     * @memberof DescribeMigrationSystemSupportTypesRequest
     */
    Platform: string;

    /**
     * @type {string}
     * @memberof DescribeMigrationSystemSupportTypesRequest
     */
    PlatformVersion: string;

    /**
     * @type {string}
     * @memberof DescribeMigrationSystemSupportTypesRequest
     */
    ProjectName?: string;
}
