/* tslint:disable */
/* eslint-disable */
/**
 * smc
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ErrorForUnTagResourcesOutput
 */
export interface ErrorForUnTagResourcesOutput {

    /**
     * @type {string}
     * @memberof ErrorForUnTagResourcesOutput
     */
    Code?: string;

    /**
     * @type {string}
     * @memberof ErrorForUnTagResourcesOutput
     */
    Message?: string;
}
