/* tslint:disable */
/* eslint-disable */
/**
 * smc
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ModifyMigrationJobAttributeRequest
 */
export interface ModifyMigrationJobAttributeRequest {

    /**
     * @type {number}
     * @memberof ModifyMigrationJobAttributeRequest
     */
    Bandwidth?: number;

    /**
     * @type {string}
     * @memberof ModifyMigrationJobAttributeRequest
     */
    MigrationJobDescription?: string;

    /**
     * @type {string}
     * @memberof ModifyMigrationJobAttributeRequest
     */
    MigrationJobId: string;

    /**
     * @type {string}
     * @memberof ModifyMigrationJobAttributeRequest
     */
    MigrationJobName?: string;

    /**
     * @type {string}
     * @memberof ModifyMigrationJobAttributeRequest
     */
    NetworkTransitionMode?: string;
}
