/* tslint:disable */
/* eslint-disable */
/**
 * speech_saas_prod
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { TagForFormalizeResourcePacksInput } from './tag-for-formalize-resource-packs-input';
 /**
 * 
 *
 * @export
 * @interface FormalizeResourcePacksRequest
 */
export interface FormalizeResourcePacksRequest {

    /**
     * @type {string}
     * @memberof FormalizeResourcePacksRequest
     */
    ProjectName: string;

    /**
     * @type {Array<TagForFormalizeResourcePacksInput>}
     * @memberof FormalizeResourcePacksRequest
     */
    Tags?: Array<TagForFormalizeResourcePacksInput>;

    /**
     * @type {number}
     * @memberof FormalizeResourcePacksRequest
     */
    Times: number;

    /**
     * @type {string}
     * @memberof FormalizeResourcePacksRequest
     */
    TrainID: string;
}
