/* tslint:disable */
/* eslint-disable */
/**
 * cen
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface DescribeCenServiceRouteEntriesRequest
 */
export interface DescribeCenServiceRouteEntriesRequest {

    /**
     * @type {string}
     * @memberof DescribeCenServiceRouteEntriesRequest
     */
    CenId?: string;

    /**
     * @type {Array<string>}
     * @memberof DescribeCenServiceRouteEntriesRequest
     */
    CenRouteEntryIds?: Array<string>;

    /**
     * @type {string}
     * @memberof DescribeCenServiceRouteEntriesRequest
     */
    DestinationCidrBlock?: string;

    /**
     * @type {number}
     * @memberof DescribeCenServiceRouteEntriesRequest
     */
    PageNumber?: number;

    /**
     * @type {number}
     * @memberof DescribeCenServiceRouteEntriesRequest
     */
    PageSize?: number;

    /**
     * @type {string}
     * @memberof DescribeCenServiceRouteEntriesRequest
     */
    ServiceRegionId?: string;

    /**
     * @type {string}
     * @memberof DescribeCenServiceRouteEntriesRequest
     */
    ServiceVpcId?: string;
}
