/* tslint:disable */
/* eslint-disable */
/**
 * rabbitmq
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ChargeInfoForCreateInstanceInput } from './charge-info-for-create-instance-input';
import { TagForCreateInstanceInput } from './tag-for-create-instance-input';
 /**
 * 
 *
 * @export
 * @interface CreateInstanceRequest
 */
export interface CreateInstanceRequest {

    /**
     * @type {ChargeInfoForCreateInstanceInput}
     * @memberof CreateInstanceRequest
     */
    ChargeInfo?: ChargeInfoForCreateInstanceInput;

    /**
     * @type {string}
     * @memberof CreateInstanceRequest
     */
    ClientToken: string;

    /**
     * @type {string}
     * @memberof CreateInstanceRequest
     */
    ComputeSpec: string;

    /**
     * @type {string}
     * @memberof CreateInstanceRequest
     */
    EipId?: string;

    /**
     * @type {string}
     * @memberof CreateInstanceRequest
     */
    InstanceDescription?: string;

    /**
     * @type {string}
     * @memberof CreateInstanceRequest
     */
    InstanceName?: string;

    /**
     * @type {string}
     * @memberof CreateInstanceRequest
     */
    ProjectName?: string;

    /**
     * @type {number}
     * @memberof CreateInstanceRequest
     */
    StorageSpace: number;

    /**
     * @type {string}
     * @memberof CreateInstanceRequest
     */
    SubnetId: string;

    /**
     * @type {Array<TagForCreateInstanceInput>}
     * @memberof CreateInstanceRequest
     */
    Tags?: Array<TagForCreateInstanceInput>;

    /**
     * @type {string}
     * @memberof CreateInstanceRequest
     */
    UserName: string;

    /**
     * @type {string}
     * @memberof CreateInstanceRequest
     */
    UserPassword: string;

    /**
     * @type {string}
     * @memberof CreateInstanceRequest
     */
    Version: string;

    /**
     * @type {string}
     * @memberof CreateInstanceRequest
     */
    VpcId: string;

    /**
     * @type {string}
     * @memberof CreateInstanceRequest
     */
    ZoneId: string;
}
