/* tslint:disable */
/* eslint-disable */
/**
 * storage_ebs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { TagForCreateSnapshotInput } from './tag-for-create-snapshot-input';
 /**
 * 
 *
 * @export
 * @interface CreateSnapshotRequest
 */
export interface CreateSnapshotRequest {

    /**
     * @type {string}
     * @memberof CreateSnapshotRequest
     */
    ClientToken?: string;

    /**
     * @type {string}
     * @memberof CreateSnapshotRequest
     */
    Description?: string;

    /**
     * @type {string}
     * @memberof CreateSnapshotRequest
     */
    ProjectName?: string;

    /**
     * @type {number}
     * @memberof CreateSnapshotRequest
     */
    RetentionDays?: number;

    /**
     * @type {string}
     * @memberof CreateSnapshotRequest
     */
    SnapshotName: string;

    /**
     * @type {Array<TagForCreateSnapshotInput>}
     * @memberof CreateSnapshotRequest
     */
    Tags?: Array<TagForCreateSnapshotInput>;

    /**
     * @type {string}
     * @memberof CreateSnapshotRequest
     */
    VolumeId: string;
}
