/* tslint:disable */
/* eslint-disable */
/**
 * vei_api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { FillColorForUpdateVideoAnalysisTaskOutput } from './fill-color-for-update-video-analysis-task-output';
import { PointForUpdateVideoAnalysisTaskOutput } from './point-for-update-video-analysis-task-output';
 /**
 * 
 *
 * @export
 * @interface CropConfigForUpdateVideoAnalysisTaskOutput
 */
export interface CropConfigForUpdateVideoAnalysisTaskOutput {

    /**
     * @type {boolean}
     * @memberof CropConfigForUpdateVideoAnalysisTaskOutput
     */
    blur_edges?: boolean;

    /**
     * @type {number}
     * @memberof CropConfigForUpdateVideoAnalysisTaskOutput
     */
    blur_radius?: number;

    /**
     * @type {number}
     * @memberof CropConfigForUpdateVideoAnalysisTaskOutput
     */
    center_x?: number;

    /**
     * @type {number}
     * @memberof CropConfigForUpdateVideoAnalysisTaskOutput
     */
    center_y?: number;

    /**
     * @type {string}
     * @memberof CropConfigForUpdateVideoAnalysisTaskOutput
     */
    crop_type?: CropConfigForUpdateVideoAnalysisTaskOutputCropTypeEnum;

    /**
     * @type {FillColorForUpdateVideoAnalysisTaskOutput}
     * @memberof CropConfigForUpdateVideoAnalysisTaskOutput
     */
    fill_color?: FillColorForUpdateVideoAnalysisTaskOutput;

    /**
     * @type {number}
     * @memberof CropConfigForUpdateVideoAnalysisTaskOutput
     */
    height?: number;

    /**
     * @type {boolean}
     * @memberof CropConfigForUpdateVideoAnalysisTaskOutput
     */
    invert_mask?: boolean;

    /**
     * @type {Array<PointForUpdateVideoAnalysisTaskOutput>}
     * @memberof CropConfigForUpdateVideoAnalysisTaskOutput
     */
    points?: Array<PointForUpdateVideoAnalysisTaskOutput>;

    /**
     * @type {number}
     * @memberof CropConfigForUpdateVideoAnalysisTaskOutput
     */
    radius?: number;

    /**
     * @type {number}
     * @memberof CropConfigForUpdateVideoAnalysisTaskOutput
     */
    radius_x?: number;

    /**
     * @type {number}
     * @memberof CropConfigForUpdateVideoAnalysisTaskOutput
     */
    radius_y?: number;

    /**
     * @type {number}
     * @memberof CropConfigForUpdateVideoAnalysisTaskOutput
     */
    width?: number;

    /**
     * @type {number}
     * @memberof CropConfigForUpdateVideoAnalysisTaskOutput
     */
    x?: number;

    /**
     * @type {number}
     * @memberof CropConfigForUpdateVideoAnalysisTaskOutput
     */
    y?: number;
}

/**
 * @export
 * @enum {string}
 */
export enum CropConfigForUpdateVideoAnalysisTaskOutputCropTypeEnum {
    Rect = 'rect',
    Circle = 'circle',
    Ellipse = 'ellipse',
    Polygon = 'polygon'
}

