/* tslint:disable */
/* eslint-disable */
/**
 * vei_api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface FilterForListLLModelsV2Input
 */
export interface FilterForListLLModelsV2Input {

    /**
     * @type {number}
     * @memberof FilterForListLLModelsV2Input
     */
    category?: number;

    /**
     * @type {number}
     * @memberof FilterForListLLModelsV2Input
     */
    channel_source?: number;

    /**
     * @type {string}
     * @memberof FilterForListLLModelsV2Input
     */
    model?: string;

    /**
     * @type {string}
     * @memberof FilterForListLLModelsV2Input
     */
    provider?: string;

    /**
     * @type {Array<string>}
     * @memberof FilterForListLLModelsV2Input
     */
    tags?: Array<string>;
}
