/* tslint:disable */
/* eslint-disable */
/**
 * vei_api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { TagFilterForListProjectInput } from './tag-filter-for-list-project-input';
 /**
 * 
 *
 * @export
 * @interface ListProjectRequest
 */
export interface ListProjectRequest {

    /**
     * @type {number}
     * @memberof ListProjectRequest
     */
    created_from?: number;

    /**
     * @type {number}
     * @memberof ListProjectRequest
     */
    created_orderby: number;

    /**
     * @type {string}
     * @memberof ListProjectRequest
     */
    created_to?: string;

    /**
     * @type {string}
     * @memberof ListProjectRequest
     */
    iam_project_name?: string;

    /**
     * @type {Array<string>}
     * @memberof ListProjectRequest
     */
    iam_projects?: Array<string>;

    /**
     * @type {number}
     * @memberof ListProjectRequest
     */
    page_index: number;

    /**
     * @type {number}
     * @memberof ListProjectRequest
     */
    page_size: number;

    /**
     * @type {string}
     * @memberof ListProjectRequest
     */
    project_name?: string;

    /**
     * @type {Array<TagFilterForListProjectInput>}
     * @memberof ListProjectRequest
     */
    tag_filters?: Array<TagFilterForListProjectInput>;
}
