/* tslint:disable */
/* eslint-disable */
/**
 * vei_api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ReadingForEdgeCallOutput
 */
export interface ReadingForEdgeCallOutput {

    /**
     * @type {string}
     * @memberof ReadingForEdgeCallOutput
     */
    id?: string;

    /**
     * @type {number}
     * @memberof ReadingForEdgeCallOutput
     */
    origin?: number;

    /**
     * @type {string}
     * @memberof ReadingForEdgeCallOutput
     */
    type?: string;

    /**
     * @type {string}
     * @memberof ReadingForEdgeCallOutput
     */
    value?: string;
}
