/* tslint:disable */
/* eslint-disable */
/**
 * vepfs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface CapacityInfoForDescribeFileSystemStatisticsOutput
 */
export interface CapacityInfoForDescribeFileSystemStatisticsOutput {

    /**
     * @type {number}
     * @memberof CapacityInfoForDescribeFileSystemStatisticsOutput
     */
    TotalTiB?: number;

    /**
     * @type {number}
     * @memberof CapacityInfoForDescribeFileSystemStatisticsOutput
     */
    UsedGiB?: number;
}
