/* tslint:disable */
/* eslint-disable */
/**
 * vepfs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { FilterForDescribeMountServicesInput } from './filter-for-describe-mount-services-input';
 /**
 * 
 *
 * @export
 * @interface DescribeMountServicesRequest
 */
export interface DescribeMountServicesRequest {

    /**
     * @type {Array<FilterForDescribeMountServicesInput>}
     * @memberof DescribeMountServicesRequest
     */
    Filters?: Array<FilterForDescribeMountServicesInput>;

    /**
     * @type {string}
     * @memberof DescribeMountServicesRequest
     */
    LanguageCode?: DescribeMountServicesRequestLanguageCodeEnum;

    /**
     * @type {string}
     * @memberof DescribeMountServicesRequest
     */
    OrderBy?: DescribeMountServicesRequestOrderByEnum;

    /**
     * @type {number}
     * @memberof DescribeMountServicesRequest
     */
    PageNumber?: number;

    /**
     * @type {number}
     * @memberof DescribeMountServicesRequest
     */
    PageSize?: number;

    /**
     * @type {string}
     * @memberof DescribeMountServicesRequest
     */
    Project?: string;
}

/**
 * @export
 * @enum {string}
 */
export enum DescribeMountServicesRequestLanguageCodeEnum {
    Zh = 'zh',
    En = 'en'
}
/**
 * @export
 * @enum {string}
 */
export enum DescribeMountServicesRequestOrderByEnum {
    CreateTimeDesc = 'CreateTimeDesc',
    CreateTimeAsc = 'CreateTimeAsc',
    NameDesc = 'NameDesc',
    NameAsc = 'NameAsc',
    VersionNumberDesc = 'VersionNumberDesc',
    VersionNumberAsc = 'VersionNumberAsc'
}

