/* tslint:disable */
/* eslint-disable */
/**
 * vepfs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { RuleForCreateLensPolicyInput } from './rule-for-create-lens-policy-input';
 /**
 * 
 *
 * @export
 * @interface RuleGroupForCreateLensPolicyInput
 */
export interface RuleGroupForCreateLensPolicyInput {

    /**
     * @type {string}
     * @memberof RuleGroupForCreateLensPolicyInput
     */
    LogicOperator?: RuleGroupForCreateLensPolicyInputLogicOperatorEnum;

    /**
     * @type {Array<RuleForCreateLensPolicyInput>}
     * @memberof RuleGroupForCreateLensPolicyInput
     */
    Rules?: Array<RuleForCreateLensPolicyInput>;
}

/**
 * @export
 * @enum {string}
 */
export enum RuleGroupForCreateLensPolicyInputLogicOperatorEnum {
    Or = 'Or',
    And = 'And'
}

