/* tslint:disable */
/* eslint-disable */
/**
 * vepfs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { TagForUpdateFileSystemInput } from './tag-for-update-file-system-input';
 /**
 * 
 *
 * @export
 * @interface UpdateFileSystemRequest
 */
export interface UpdateFileSystemRequest {

    /**
     * @type {string}
     * @memberof UpdateFileSystemRequest
     */
    Description?: string;

    /**
     * @type {string}
     * @memberof UpdateFileSystemRequest
     */
    FileSystemId: string;

    /**
     * @type {string}
     * @memberof UpdateFileSystemRequest
     */
    FileSystemName?: string;

    /**
     * @type {Array<TagForUpdateFileSystemInput>}
     * @memberof UpdateFileSystemRequest
     */
    Tags?: Array<TagForUpdateFileSystemInput>;
}
