/* tslint:disable */
/* eslint-disable */
/**
 * dms
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface PrivateLinkForQueryDataMigrateTaskOutput
 */
export interface PrivateLinkForQueryDataMigrateTaskOutput {

    /**
     * @type {string}
     * @memberof PrivateLinkForQueryDataMigrateTaskOutput
     */
    ENIRole?: string;

    /**
     * @type {string}
     * @memberof PrivateLinkForQueryDataMigrateTaskOutput
     */
    IdcIP?: string;

    /**
     * @type {number}
     * @memberof PrivateLinkForQueryDataMigrateTaskOutput
     */
    IdcPort?: number;

    /**
     * @type {Array<string>}
     * @memberof PrivateLinkForQueryDataMigrateTaskOutput
     */
    SecurityGroupIDs?: Array<string>;

    /**
     * @type {string}
     * @memberof PrivateLinkForQueryDataMigrateTaskOutput
     */
    SubnetID?: string;

    /**
     * @type {string}
     * @memberof PrivateLinkForQueryDataMigrateTaskOutput
     */
    VpcID?: string;
}
