/* tslint:disable */
/* eslint-disable */
/**
 * bmq
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface EnableOverlayAccessRequest
 */
export interface EnableOverlayAccessRequest {

    /**
     * @type {string}
     * @memberof EnableOverlayAccessRequest
     */
    InstanceId: string;
}
