/* tslint:disable */
/* eslint-disable */
/**
 * bmq
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ItemForListAvailableVPCForBMQOutput
 */
export interface ItemForListAvailableVPCForBMQOutput {

    /**
     * @type {string}
     * @memberof ItemForListAvailableVPCForBMQOutput
     */
    CidrBlock?: string;

    /**
     * @type {string}
     * @memberof ItemForListAvailableVPCForBMQOutput
     */
    CreateTime?: string;

    /**
     * @type {string}
     * @memberof ItemForListAvailableVPCForBMQOutput
     */
    Description?: string;

    /**
     * @type {string}
     * @memberof ItemForListAvailableVPCForBMQOutput
     */
    Name?: string;

    /**
     * @type {Array<string>}
     * @memberof ItemForListAvailableVPCForBMQOutput
     */
    SecurityGroupIds?: Array<string>;

    /**
     * @type {string}
     * @memberof ItemForListAvailableVPCForBMQOutput
     */
    Status?: string;

    /**
     * @type {Array<string>}
     * @memberof ItemForListAvailableVPCForBMQOutput
     */
    SubnetIds?: Array<string>;

    /**
     * @type {string}
     * @memberof ItemForListAvailableVPCForBMQOutput
     */
    VpcId?: string;
}
