/* tslint:disable */
/* eslint-disable */
/**
 * cp
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ConvertFilterForListTriggersOutput } from './convert-filter-for-list-triggers-output';
 /**
 * 
 *
 * @export
 * @interface GitForListTriggersOutput
 */
export interface GitForListTriggersOutput {

    /**
     * @type {Array<ConvertFilterForListTriggersOutput>}
     * @memberof GitForListTriggersOutput
     */
    Filters?: Array<ConvertFilterForListTriggersOutput>;

    /**
     * @type {string}
     * @memberof GitForListTriggersOutput
     */
    ResourceId?: string;
}
