/* tslint:disable */
/* eslint-disable */
/**
 * cp
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface GitForUpdateResourceInput
 */
export interface GitForUpdateResourceInput {

    /**
     * @type {string}
     * @memberof GitForUpdateResourceInput
     */
    AccessKey?: string;

    /**
     * @type {number}
     * @memberof GitForUpdateResourceInput
     */
    CloneDepth?: number;

    /**
     * @type {string}
     * @memberof GitForUpdateResourceInput
     */
    Password?: string;

    /**
     * @type {string}
     * @memberof GitForUpdateResourceInput
     */
    SecretKey?: string;

    /**
     * @type {string}
     * @memberof GitForUpdateResourceInput
     */
    Url?: string;

    /**
     * @type {string}
     * @memberof GitForUpdateResourceInput
     */
    UserName?: string;

    /**
     * @type {string}
     * @memberof GitForUpdateResourceInput
     */
    UserToken?: string;
}
