/* tslint:disable */
/* eslint-disable */
/**
 * cp
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { UiConfigForListComponentStepOutput } from './ui-config-for-list-component-step-output';
 /**
 * 
 *
 * @export
 * @interface InputForListComponentStepOutput
 */
export interface InputForListComponentStepOutput {

    /**
     * @type {string}
     * @memberof InputForListComponentStepOutput
     */
    DefaultValue?: string;

    /**
     * @type {string}
     * @memberof InputForListComponentStepOutput
     */
    Description?: string;

    /**
     * @type {string}
     * @memberof InputForListComponentStepOutput
     */
    DisplayName?: string;

    /**
     * @type {string}
     * @memberof InputForListComponentStepOutput
     */
    Name?: string;

    /**
     * @type {boolean}
     * @memberof InputForListComponentStepOutput
     */
    Required?: boolean;

    /**
     * @type {string}
     * @memberof InputForListComponentStepOutput
     */
    Type?: string;

    /**
     * @type {UiConfigForListComponentStepOutput}
     * @memberof InputForListComponentStepOutput
     */
    UiConfig?: UiConfigForListComponentStepOutput;
}
