/* tslint:disable */
/* eslint-disable */
/**
 * resource_share
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ResourceShareInvitationForDescribeResourceShareInvitationsOutput
 */
export interface ResourceShareInvitationForDescribeResourceShareInvitationsOutput {

    /**
     * @type {string}
     * @memberof ResourceShareInvitationForDescribeResourceShareInvitationsOutput
     */
    InvitatedTime?: string;

    /**
     * @type {number}
     * @memberof ResourceShareInvitationForDescribeResourceShareInvitationsOutput
     */
    OwningAccountId?: number;

    /**
     * @type {number}
     * @memberof ResourceShareInvitationForDescribeResourceShareInvitationsOutput
     */
    ReceiverAccountId?: number;

    /**
     * @type {string}
     * @memberof ResourceShareInvitationForDescribeResourceShareInvitationsOutput
     */
    ResourceShareId?: string;

    /**
     * @type {string}
     * @memberof ResourceShareInvitationForDescribeResourceShareInvitationsOutput
     */
    ResourceShareInvitationTrn?: string;

    /**
     * @type {string}
     * @memberof ResourceShareInvitationForDescribeResourceShareInvitationsOutput
     */
    ResourceShareName?: string;

    /**
     * @type {string}
     * @memberof ResourceShareInvitationForDescribeResourceShareInvitationsOutput
     */
    ResourceShareTrn?: string;

    /**
     * @type {string}
     * @memberof ResourceShareInvitationForDescribeResourceShareInvitationsOutput
     */
    Status?: string;
}
