/* tslint:disable */
/* eslint-disable */
/**
 * organization
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { OrganizationUnitForDescribeOrganizationalUnitOutput } from './organization-unit-for-describe-organizational-unit-output';
 /**
 * 
 *
 * @export
 * @interface DescribeOrganizationalUnitResponse
 */
export interface DescribeOrganizationalUnitResponse {

    /**
     * @type {OrganizationUnitForDescribeOrganizationalUnitOutput}
     * @memberof DescribeOrganizationalUnitResponse
     */
    OrganizationUnit?: OrganizationUnitForDescribeOrganizationalUnitOutput;
}
