/* tslint:disable */
/* eslint-disable */
/**
 * organization
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface InviteAccountRequest
 */
export interface InviteAccountRequest {

    /**
     * @type {string}
     * @memberof InviteAccountRequest
     */
    AccountId: string;

    /**
     * @type {number}
     * @memberof InviteAccountRequest
     */
    AllowExit: number;

    /**
     * @type {string}
     * @memberof InviteAccountRequest
     */
    Description?: string;

    /**
     * @type {string}
     * @memberof InviteAccountRequest
     */
    OrgUnitId?: string;

    /**
     * @type {string}
     * @memberof InviteAccountRequest
     */
    ShowName: string;
}
