/* tslint:disable */
/* eslint-disable */
/**
 * organization
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { SubUnitListForListOrganizationalUnitsForParentOutput } from './sub-unit-list-for-list-organizational-units-for-parent-output';
 /**
 * 
 *
 * @export
 * @interface ListOrganizationalUnitsForParentResponse
 */
export interface ListOrganizationalUnitsForParentResponse {

    /**
     * @type {number}
     * @memberof ListOrganizationalUnitsForParentResponse
     */
    Limit?: number;

    /**
     * @type {number}
     * @memberof ListOrganizationalUnitsForParentResponse
     */
    Offset?: number;

    /**
     * @type {Array<SubUnitListForListOrganizationalUnitsForParentOutput>}
     * @memberof ListOrganizationalUnitsForParentResponse
     */
    SubUnitList?: Array<SubUnitListForListOrganizationalUnitsForParentOutput>;

    /**
     * @type {number}
     * @memberof ListOrganizationalUnitsForParentResponse
     */
    Total?: number;
}
