/* tslint:disable */
/* eslint-disable */
/**
 * organization
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ListInvitationsRequest
 */
export interface ListInvitationsRequest {

    /**
     * @type {number}
     * @memberof ListInvitationsRequest
     */
    Limit?: number;

    /**
     * @type {number}
     * @memberof ListInvitationsRequest
     */
    Offset?: number;

    /**
     * @type {number}
     * @memberof ListInvitationsRequest
     */
    OrderBy?: number;

    /**
     * @type {string}
     * @memberof ListInvitationsRequest
     */
    OrderStr?: string;

    /**
     * @type {string}
     * @memberof ListInvitationsRequest
     */
    OrgUnitId?: string;

    /**
     * @type {string}
     * @memberof ListInvitationsRequest
     */
    Search?: string;
}
