/* tslint:disable */
/* eslint-disable */
/**
 * dbw
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface DescribeTicketsRequest
 */
export interface DescribeTicketsRequest {

    /**
     * @type {string}
     * @memberof DescribeTicketsRequest
     */
    ListType: string;

    /**
     * @type {string}
     * @memberof DescribeTicketsRequest
     */
    OrderBy?: string;

    /**
     * @type {number}
     * @memberof DescribeTicketsRequest
     */
    PageNumber?: number;

    /**
     * @type {number}
     * @memberof DescribeTicketsRequest
     */
    PageSize?: number;

    /**
     * @type {string}
     * @memberof DescribeTicketsRequest
     */
    SortBy?: string;
}
