/* tslint:disable */
/* eslint-disable */
/**
 * dbw
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { SearchParamForDescribeSlowLogsInput } from './search-param-for-describe-slow-logs-input';
 /**
 * 
 *
 * @export
 * @interface DescribeSlowLogsRequest
 */
export interface DescribeSlowLogsRequest {

    /**
     * @type {number}
     * @memberof DescribeSlowLogsRequest
     */
    EndTime: number;

    /**
     * @type {string}
     * @memberof DescribeSlowLogsRequest
     */
    InstanceId: string;

    /**
     * @type {string}
     * @memberof DescribeSlowLogsRequest
     */
    InstanceType?: DescribeSlowLogsRequestInstanceTypeEnum;

    /**
     * @type {string}
     * @memberof DescribeSlowLogsRequest
     */
    NodeId?: string;

    /**
     * @type {string}
     * @memberof DescribeSlowLogsRequest
     */
    OrderBy?: DescribeSlowLogsRequestOrderByEnum;

    /**
     * @type {number}
     * @memberof DescribeSlowLogsRequest
     */
    PageNumber?: number;

    /**
     * @type {number}
     * @memberof DescribeSlowLogsRequest
     */
    PageSize?: number;

    /**
     * @type {string}
     * @memberof DescribeSlowLogsRequest
     */
    RegionId: string;

    /**
     * @type {SearchParamForDescribeSlowLogsInput}
     * @memberof DescribeSlowLogsRequest
     */
    SearchParam?: SearchParamForDescribeSlowLogsInput;

    /**
     * @type {string}
     * @memberof DescribeSlowLogsRequest
     */
    SortBy?: DescribeSlowLogsRequestSortByEnum;

    /**
     * @type {number}
     * @memberof DescribeSlowLogsRequest
     */
    StartTime: number;
}

/**
 * @export
 * @enum {string}
 */
export enum DescribeSlowLogsRequestInstanceTypeEnum {
    MySQL = 'MySQL',
    Postgres = 'Postgres',
    Mongo = 'Mongo',
    Redis = 'Redis',
    VeDBMySQL = 'VeDBMySQL',
    MetaRDS = 'MetaRDS',
    MSSQL = 'MSSQL',
    ByteRDS = 'ByteRDS',
    MySQLSharding = 'MySQLSharding',
    MetaMySQL = 'MetaMySQL'
}
/**
 * @export
 * @enum {string}
 */
export enum DescribeSlowLogsRequestOrderByEnum {
    Timestamp = 'Timestamp',
    QueryTime = 'QueryTime',
    LockTime = 'LockTime',
    RowsExamined = 'RowsExamined',
    RowsSent = 'RowsSent'
}
/**
 * @export
 * @enum {string}
 */
export enum DescribeSlowLogsRequestSortByEnum {
    ASC = 'ASC',
    DESC = 'DESC'
}

