/* tslint:disable */
/* eslint-disable */
/**
 * volc_observe
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { NotifyTemplateForUpdateNotificationInput } from './notify-template-for-update-notification-input';
 /**
 * 
 *
 * @export
 * @interface NotificationForUpdateNotificationInput
 */
export interface NotificationForUpdateNotificationInput {

    /**
     * @type {Array<string>}
     * @memberof NotificationForUpdateNotificationInput
     */
    AlertMethods?: Array<NotificationForUpdateNotificationInputAlertMethodsEnum>;

    /**
     * @type {Array<string>}
     * @memberof NotificationForUpdateNotificationInput
     */
    ContactGroupIds?: Array<string>;

    /**
     * @type {string}
     * @memberof NotificationForUpdateNotificationInput
     */
    Level?: NotificationForUpdateNotificationInputLevelEnum;

    /**
     * @type {Array<NotifyTemplateForUpdateNotificationInput>}
     * @memberof NotificationForUpdateNotificationInput
     */
    NotifyTemplates?: Array<NotifyTemplateForUpdateNotificationInput>;

    /**
     * @type {Array<string>}
     * @memberof NotificationForUpdateNotificationInput
     */
    WebhookIds?: Array<string>;
}

/**
 * @export
 * @enum {string}
 */
export enum NotificationForUpdateNotificationInputAlertMethodsEnum {
    Email = 'Email',
    Phone = 'Phone',
    SMS = 'SMS',
    Webhook = 'Webhook'
}
/**
 * @export
 * @enum {string}
 */
export enum NotificationForUpdateNotificationInputLevelEnum {
    Notice = 'notice',
    Warning = 'warning',
    Critical = 'critical',
    Recovery = 'recovery'
}

