/* tslint:disable */
/* eslint-disable */
/**
 * edx
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { VIFForDescribeVirtualInterfaceOutput } from './viffor-describe-virtual-interface-output';
 /**
 * 
 *
 * @export
 * @interface DescribeVirtualInterfaceResponse
 */
export interface DescribeVirtualInterfaceResponse {

    /**
     * @type {VIFForDescribeVirtualInterfaceOutput}
     * @memberof DescribeVirtualInterfaceResponse
     */
    VIF?: VIFForDescribeVirtualInterfaceOutput;
}
