/* tslint:disable */
/* eslint-disable */
/**
 * edx
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AggregationListForListRouteAggregationOutput } from './aggregation-list-for-list-route-aggregation-output';
 /**
 * 
 *
 * @export
 * @interface ListRouteAggregationResponse
 */
export interface ListRouteAggregationResponse {

    /**
     * @type {Array<AggregationListForListRouteAggregationOutput>}
     * @memberof ListRouteAggregationResponse
     */
    AggregationList?: Array<AggregationListForListRouteAggregationOutput>;

    /**
     * @type {number}
     * @memberof ListRouteAggregationResponse
     */
    PageNumber?: number;

    /**
     * @type {number}
     * @memberof ListRouteAggregationResponse
     */
    PageSize?: number;

    /**
     * @type {number}
     * @memberof ListRouteAggregationResponse
     */
    TotalCount?: number;
}
