/* tslint:disable */
/* eslint-disable */
/**
 * edx
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface VIFForDescribeVirtualInterfaceOutput
 */
export interface VIFForDescribeVirtualInterfaceOutput {

    /**
     * @type {string}
     * @memberof VIFForDescribeVirtualInterfaceOutput
     */
    AccessPoint?: string;

    /**
     * @type {number}
     * @memberof VIFForDescribeVirtualInterfaceOutput
     */
    AccountId?: number;

    /**
     * @type {string}
     * @memberof VIFForDescribeVirtualInterfaceOutput
     */
    CreateTime?: string;

    /**
     * @type {boolean}
     * @memberof VIFForDescribeVirtualInterfaceOutput
     */
    CrossAccount?: boolean;

    /**
     * @type {string}
     * @memberof VIFForDescribeVirtualInterfaceOutput
     */
    DXPInstanceId?: string;

    /**
     * @type {string}
     * @memberof VIFForDescribeVirtualInterfaceOutput
     */
    DXPInstanceName?: string;

    /**
     * @type {string}
     * @memberof VIFForDescribeVirtualInterfaceOutput
     */
    InstanceId?: string;

    /**
     * @type {string}
     * @memberof VIFForDescribeVirtualInterfaceOutput
     */
    LocalIP?: string;

    /**
     * @type {number}
     * @memberof VIFForDescribeVirtualInterfaceOutput
     */
    MaxBandwidth?: number;

    /**
     * @type {string}
     * @memberof VIFForDescribeVirtualInterfaceOutput
     */
    Name?: string;

    /**
     * @type {string}
     * @memberof VIFForDescribeVirtualInterfaceOutput
     */
    PeerIP?: string;

    /**
     * @type {string}
     * @memberof VIFForDescribeVirtualInterfaceOutput
     */
    State?: string;

    /**
     * @type {string}
     * @memberof VIFForDescribeVirtualInterfaceOutput
     */
    VIFVGWInstanceId?: string;

    /**
     * @type {number}
     * @memberof VIFForDescribeVirtualInterfaceOutput
     */
    VlanId?: number;
}
