/* tslint:disable */
/* eslint-disable */
/**
 * gtm
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { PoolSetForGetRuleOutput } from './pool-set-for-get-rule-output';
import { ProbeForGetRuleOutput } from './probe-for-get-rule-output';
 /**
 * 
 *
 * @export
 * @interface GetRuleResponse
 */
export interface GetRuleResponse {

    /**
     * @type {string}
     * @memberof GetRuleResponse
     */
    CreateTime?: string;

    /**
     * @type {boolean}
     * @memberof GetRuleResponse
     */
    Disable?: boolean;

    /**
     * @type {number}
     * @memberof GetRuleResponse
     */
    EffectivePoolSetIndex?: number;

    /**
     * @type {string}
     * @memberof GetRuleResponse
     */
    Line?: string;

    /**
     * @type {string}
     * @memberof GetRuleResponse
     */
    Name?: string;

    /**
     * @type {string}
     * @memberof GetRuleResponse
     */
    PoolSetMode?: string;

    /**
     * @type {Array<PoolSetForGetRuleOutput>}
     * @memberof GetRuleResponse
     */
    PoolSets?: Array<PoolSetForGetRuleOutput>;

    /**
     * @type {ProbeForGetRuleOutput}
     * @memberof GetRuleResponse
     */
    Probe?: ProbeForGetRuleOutput;

    /**
     * @type {string}
     * @memberof GetRuleResponse
     */
    Remark?: string;

    /**
     * @type {string}
     * @memberof GetRuleResponse
     */
    RuleId?: string;

    /**
     * @type {string}
     * @memberof GetRuleResponse
     */
    UpdateTime?: string;

    /**
     * @type {number}
     * @memberof GetRuleResponse
     */
    Weight?: number;
}
