/* tslint:disable */
/* eslint-disable */
/**
 * gtm
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AddressForGetPoolOutput } from './address-for-get-pool-output';
 /**
 * 
 *
 * @export
 * @interface GetPoolResponse
 */
export interface GetPoolResponse {

    /**
     * @type {string}
     * @memberof GetPoolResponse
     */
    AddrType?: string;

    /**
     * @type {Array<AddressForGetPoolOutput>}
     * @memberof GetPoolResponse
     */
    Addresses?: Array<AddressForGetPoolOutput>;

    /**
     * @type {number}
     * @memberof GetPoolResponse
     */
    Capacity?: number;

    /**
     * @type {string}
     * @memberof GetPoolResponse
     */
    CapacityMode?: string;

    /**
     * @type {string}
     * @memberof GetPoolResponse
     */
    CreateTime?: string;

    /**
     * @type {boolean}
     * @memberof GetPoolResponse
     */
    Deletable?: boolean;

    /**
     * @type {string}
     * @memberof GetPoolResponse
     */
    Name?: string;

    /**
     * @type {string}
     * @memberof GetPoolResponse
     */
    PoolId?: string;

    /**
     * @type {string}
     * @memberof GetPoolResponse
     */
    Remark?: string;

    /**
     * @type {string}
     * @memberof GetPoolResponse
     */
    UpdateTime?: string;
}
