/* tslint:disable */
/* eslint-disable */
/**
 * gtm
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ListPoolsRequest
 */
export interface ListPoolsRequest {

    /**
     * @type {string}
     * @memberof ListPoolsRequest
     */
    AddrType?: string;

    /**
     * @type {string}
     * @memberof ListPoolsRequest
     */
    Address?: string;

    /**
     * @type {string}
     * @memberof ListPoolsRequest
     */
    GtmId: string;

    /**
     * @type {string}
     * @memberof ListPoolsRequest
     */
    Name?: string;

    /**
     * @type {number}
     * @memberof ListPoolsRequest
     */
    PageNumber?: number;

    /**
     * @type {number}
     * @memberof ListPoolsRequest
     */
    PageSize?: number;

    /**
     * @type {string}
     * @memberof ListPoolsRequest
     */
    PoolId?: string;

    /**
     * @type {string}
     * @memberof ListPoolsRequest
     */
    Remark?: string;

    /**
     * @type {string}
     * @memberof ListPoolsRequest
     */
    SearchMode?: string;

    /**
     * @type {string}
     * @memberof ListPoolsRequest
     */
    SortBy?: string;

    /**
     * @type {string}
     * @memberof ListPoolsRequest
     */
    SortOrder?: string;
}
