/* tslint:disable */
/* eslint-disable */
/**
 * gtm
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface StatisticsForGetPolicyOutput
 */
export interface StatisticsForGetPolicyOutput {

    /**
     * @type {number}
     * @memberof StatisticsForGetPolicyOutput
     */
    ActiveAddr?: number;

    /**
     * @type {number}
     * @memberof StatisticsForGetPolicyOutput
     */
    InactiveAddr?: number;
}
