/* tslint:disable */
/* eslint-disable */
/**
 * cbr
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Client, ClientConfig, Command, buildRequestConfigFromMetaPath, CommandOutput } from '@volcengine/sdk-core';

import { CreateBackupJobRequest } from './types/index';
import { CreateBackupJobResponse } from './types/index';
import { CreateBackupPlanRequest } from './types/index';
import { CreateBackupPlanResponse } from './types/index';
import { CreateBackupPolicyRequest } from './types/index';
import { CreateBackupPolicyResponse } from './types/index';
import { CreateBackupResourceRequest } from './types/index';
import { CreateBackupResourceResponse } from './types/index';
import { CreateRestoreJobRequest } from './types/index';
import { CreateRestoreJobResponse } from './types/index';
import { CreateVaultRequest } from './types/index';
import { CreateVaultResponse } from './types/index';
import { DeleteBackupPlanRequest } from './types/index';
import { DeleteBackupPlanResponse } from './types/index';
import { DeleteBackupPolicyRequest } from './types/index';
import { DeleteBackupPolicyResponse } from './types/index';
import { DeleteBackupResourceRequest } from './types/index';
import { DeleteBackupResourceResponse } from './types/index';
import { DeleteRecoveryPointRequest } from './types/index';
import { DeleteRecoveryPointResponse } from './types/index';
import { DeleteVaultRequest } from './types/index';
import { DeleteVaultResponse } from './types/index';
import { DescribeBackupPlansRequest } from './types/index';
import { DescribeBackupPlansResponse } from './types/index';
import { DescribeBackupPoliciesRequest } from './types/index';
import { DescribeBackupPoliciesResponse } from './types/index';
import { DescribeBackupResourcesRequest } from './types/index';
import { DescribeBackupResourcesResponse } from './types/index';
import { DescribeRecoveryPointsRequest } from './types/index';
import { DescribeRecoveryPointsResponse } from './types/index';
import { DescribeRegionsRequest } from './types/index';
import { DescribeRegionsResponse } from './types/index';
import { DescribeRestoreJobsRequest } from './types/index';
import { DescribeRestoreJobsResponse } from './types/index';
import { DescribeVaultsRequest } from './types/index';
import { DescribeVaultsResponse } from './types/index';
import { DescribeZonesRequest } from './types/index';
import { DescribeZonesResponse } from './types/index';
import { DisableBackupPolicyRequest } from './types/index';
import { DisableBackupPolicyResponse } from './types/index';
import { EnableBackupPolicyRequest } from './types/index';
import { EnableBackupPolicyResponse } from './types/index';
import { ListTagsForResourcesRequest } from './types/index';
import { ListTagsForResourcesResponse } from './types/index';
import { TagResourcesRequest } from './types/index';
import { TagResourcesResponse } from './types/index';
import { UntagResourcesRequest } from './types/index';
import { UntagResourcesResponse } from './types/index';
import { UpdateBackupPlanRequest } from './types/index';
import { UpdateBackupPlanResponse } from './types/index';
import { UpdateBackupPolicyRequest } from './types/index';
import { UpdateBackupPolicyResponse } from './types/index';
import { UpdateRecoveryPointRequest } from './types/index';
import { UpdateRecoveryPointResponse } from './types/index';
import { UpdateRestoreJobRequest } from './types/index';
import { UpdateRestoreJobResponse } from './types/index';

// ============================================================================
// Output Type Definitions
// ============================================================================
export type CreateBackupJobCommandOutput = CommandOutput<CreateBackupJobResponse>;
export type CreateBackupPlanCommandOutput = CommandOutput<CreateBackupPlanResponse>;
export type CreateBackupPolicyCommandOutput = CommandOutput<CreateBackupPolicyResponse>;
export type CreateBackupResourceCommandOutput = CommandOutput<CreateBackupResourceResponse>;
export type CreateRestoreJobCommandOutput = CommandOutput<CreateRestoreJobResponse>;
export type CreateVaultCommandOutput = CommandOutput<CreateVaultResponse>;
export type DeleteBackupPlanCommandOutput = CommandOutput<DeleteBackupPlanResponse>;
export type DeleteBackupPolicyCommandOutput = CommandOutput<DeleteBackupPolicyResponse>;
export type DeleteBackupResourceCommandOutput = CommandOutput<DeleteBackupResourceResponse>;
export type DeleteRecoveryPointCommandOutput = CommandOutput<DeleteRecoveryPointResponse>;
export type DeleteVaultCommandOutput = CommandOutput<DeleteVaultResponse>;
export type DescribeBackupPlansCommandOutput = CommandOutput<DescribeBackupPlansResponse>;
export type DescribeBackupPoliciesCommandOutput = CommandOutput<DescribeBackupPoliciesResponse>;
export type DescribeBackupResourcesCommandOutput = CommandOutput<DescribeBackupResourcesResponse>;
export type DescribeRecoveryPointsCommandOutput = CommandOutput<DescribeRecoveryPointsResponse>;
export type DescribeRegionsCommandOutput = CommandOutput<DescribeRegionsResponse>;
export type DescribeRestoreJobsCommandOutput = CommandOutput<DescribeRestoreJobsResponse>;
export type DescribeVaultsCommandOutput = CommandOutput<DescribeVaultsResponse>;
export type DescribeZonesCommandOutput = CommandOutput<DescribeZonesResponse>;
export type DisableBackupPolicyCommandOutput = CommandOutput<DisableBackupPolicyResponse>;
export type EnableBackupPolicyCommandOutput = CommandOutput<EnableBackupPolicyResponse>;
export type ListTagsForResourcesCommandOutput = CommandOutput<ListTagsForResourcesResponse>;
export type TagResourcesCommandOutput = CommandOutput<TagResourcesResponse>;
export type UntagResourcesCommandOutput = CommandOutput<UntagResourcesResponse>;
export type UpdateBackupPlanCommandOutput = CommandOutput<UpdateBackupPlanResponse>;
export type UpdateBackupPolicyCommandOutput = CommandOutput<UpdateBackupPolicyResponse>;
export type UpdateRecoveryPointCommandOutput = CommandOutput<UpdateRecoveryPointResponse>;
export type UpdateRestoreJobCommandOutput = CommandOutput<UpdateRestoreJobResponse>;

/**
 * CBRClient Service Client
 */
export class CBRClient extends Client {
  constructor(config: ClientConfig = {}) {
    super({
      protocol: 'https',
      region: 'cn-beijing',
      ...config,
    });
  }
}

/**
 * Command to CreateBackupJob
 */
export class CreateBackupJobCommand extends Command<
  CreateBackupJobRequest,
  CreateBackupJobCommandOutput,
  'CreateBackupJobCommand'
> {
  static readonly metaPath = '/CreateBackupJob/2024-03-01/cbr/post/application_json/';

  constructor(input: CreateBackupJobRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(CreateBackupJobCommand.metaPath);
  }
}
/**
 * Command to CreateBackupPlan
 */
export class CreateBackupPlanCommand extends Command<
  CreateBackupPlanRequest,
  CreateBackupPlanCommandOutput,
  'CreateBackupPlanCommand'
> {
  static readonly metaPath = '/CreateBackupPlan/2024-03-01/cbr/post/application_json/';

  constructor(input: CreateBackupPlanRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(CreateBackupPlanCommand.metaPath);
  }
}
/**
 * Command to CreateBackupPolicy
 */
export class CreateBackupPolicyCommand extends Command<
  CreateBackupPolicyRequest,
  CreateBackupPolicyCommandOutput,
  'CreateBackupPolicyCommand'
> {
  static readonly metaPath = '/CreateBackupPolicy/2024-03-01/cbr/post/application_json/';

  constructor(input: CreateBackupPolicyRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(CreateBackupPolicyCommand.metaPath);
  }
}
/**
 * Command to CreateBackupResource
 */
export class CreateBackupResourceCommand extends Command<
  CreateBackupResourceRequest,
  CreateBackupResourceCommandOutput,
  'CreateBackupResourceCommand'
> {
  static readonly metaPath = '/CreateBackupResource/2024-03-01/cbr/post/application_json/';

  constructor(input: CreateBackupResourceRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(CreateBackupResourceCommand.metaPath);
  }
}
/**
 * Command to CreateRestoreJob
 */
export class CreateRestoreJobCommand extends Command<
  CreateRestoreJobRequest,
  CreateRestoreJobCommandOutput,
  'CreateRestoreJobCommand'
> {
  static readonly metaPath = '/CreateRestoreJob/2024-03-01/cbr/post/application_json/';

  constructor(input: CreateRestoreJobRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(CreateRestoreJobCommand.metaPath);
  }
}
/**
 * Command to CreateVault
 */
export class CreateVaultCommand extends Command<
  CreateVaultRequest,
  CreateVaultCommandOutput,
  'CreateVaultCommand'
> {
  static readonly metaPath = '/CreateVault/2024-03-01/cbr/post/application_json/';

  constructor(input: CreateVaultRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(CreateVaultCommand.metaPath);
  }
}
/**
 * Command to DeleteBackupPlan
 */
export class DeleteBackupPlanCommand extends Command<
  DeleteBackupPlanRequest,
  DeleteBackupPlanCommandOutput,
  'DeleteBackupPlanCommand'
> {
  static readonly metaPath = '/DeleteBackupPlan/2024-03-01/cbr/post/application_json/';

  constructor(input: DeleteBackupPlanRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(DeleteBackupPlanCommand.metaPath);
  }
}
/**
 * Command to DeleteBackupPolicy
 */
export class DeleteBackupPolicyCommand extends Command<
  DeleteBackupPolicyRequest,
  DeleteBackupPolicyCommandOutput,
  'DeleteBackupPolicyCommand'
> {
  static readonly metaPath = '/DeleteBackupPolicy/2024-03-01/cbr/post/application_json/';

  constructor(input: DeleteBackupPolicyRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(DeleteBackupPolicyCommand.metaPath);
  }
}
/**
 * Command to DeleteBackupResource
 */
export class DeleteBackupResourceCommand extends Command<
  DeleteBackupResourceRequest,
  DeleteBackupResourceCommandOutput,
  'DeleteBackupResourceCommand'
> {
  static readonly metaPath = '/DeleteBackupResource/2024-03-01/cbr/post/application_json/';

  constructor(input: DeleteBackupResourceRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(DeleteBackupResourceCommand.metaPath);
  }
}
/**
 * Command to DeleteRecoveryPoint
 */
export class DeleteRecoveryPointCommand extends Command<
  DeleteRecoveryPointRequest,
  DeleteRecoveryPointCommandOutput,
  'DeleteRecoveryPointCommand'
> {
  static readonly metaPath = '/DeleteRecoveryPoint/2024-03-01/cbr/post/application_json/';

  constructor(input: DeleteRecoveryPointRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(DeleteRecoveryPointCommand.metaPath);
  }
}
/**
 * Command to DeleteVault
 */
export class DeleteVaultCommand extends Command<
  DeleteVaultRequest,
  DeleteVaultCommandOutput,
  'DeleteVaultCommand'
> {
  static readonly metaPath = '/DeleteVault/2024-03-01/cbr/post/application_json/';

  constructor(input: DeleteVaultRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(DeleteVaultCommand.metaPath);
  }
}
/**
 * Command to DescribeBackupPlans
 */
export class DescribeBackupPlansCommand extends Command<
  DescribeBackupPlansRequest,
  DescribeBackupPlansCommandOutput,
  'DescribeBackupPlansCommand'
> {
  static readonly metaPath = '/DescribeBackupPlans/2024-03-01/cbr/post/application_json/';

  constructor(input: DescribeBackupPlansRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(DescribeBackupPlansCommand.metaPath);
  }
}
/**
 * Command to DescribeBackupPolicies
 */
export class DescribeBackupPoliciesCommand extends Command<
  DescribeBackupPoliciesRequest,
  DescribeBackupPoliciesCommandOutput,
  'DescribeBackupPoliciesCommand'
> {
  static readonly metaPath = '/DescribeBackupPolicies/2024-03-01/cbr/post/application_json/';

  constructor(input: DescribeBackupPoliciesRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(DescribeBackupPoliciesCommand.metaPath);
  }
}
/**
 * Command to DescribeBackupResources
 */
export class DescribeBackupResourcesCommand extends Command<
  DescribeBackupResourcesRequest,
  DescribeBackupResourcesCommandOutput,
  'DescribeBackupResourcesCommand'
> {
  static readonly metaPath = '/DescribeBackupResources/2024-03-01/cbr/post/application_json/';

  constructor(input: DescribeBackupResourcesRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(DescribeBackupResourcesCommand.metaPath);
  }
}
/**
 * Command to DescribeRecoveryPoints
 */
export class DescribeRecoveryPointsCommand extends Command<
  DescribeRecoveryPointsRequest,
  DescribeRecoveryPointsCommandOutput,
  'DescribeRecoveryPointsCommand'
> {
  static readonly metaPath = '/DescribeRecoveryPoints/2024-03-01/cbr/post/application_json/';

  constructor(input: DescribeRecoveryPointsRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(DescribeRecoveryPointsCommand.metaPath);
  }
}
/**
 * Command to DescribeRegions
 */
export class DescribeRegionsCommand extends Command<
  DescribeRegionsRequest,
  DescribeRegionsCommandOutput,
  'DescribeRegionsCommand'
> {
  static readonly metaPath = '/DescribeRegions/2024-03-01/cbr/post/application_json/';

  constructor(input: DescribeRegionsRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(DescribeRegionsCommand.metaPath);
  }
}
/**
 * Command to DescribeRestoreJobs
 */
export class DescribeRestoreJobsCommand extends Command<
  DescribeRestoreJobsRequest,
  DescribeRestoreJobsCommandOutput,
  'DescribeRestoreJobsCommand'
> {
  static readonly metaPath = '/DescribeRestoreJobs/2024-03-01/cbr/post/application_json/';

  constructor(input: DescribeRestoreJobsRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(DescribeRestoreJobsCommand.metaPath);
  }
}
/**
 * Command to DescribeVaults
 */
export class DescribeVaultsCommand extends Command<
  DescribeVaultsRequest,
  DescribeVaultsCommandOutput,
  'DescribeVaultsCommand'
> {
  static readonly metaPath = '/DescribeVaults/2024-03-01/cbr/post/application_json/';

  constructor(input: DescribeVaultsRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(DescribeVaultsCommand.metaPath);
  }
}
/**
 * Command to DescribeZones
 */
export class DescribeZonesCommand extends Command<
  DescribeZonesRequest,
  DescribeZonesCommandOutput,
  'DescribeZonesCommand'
> {
  static readonly metaPath = '/DescribeZones/2024-03-01/cbr/post/application_json/';

  constructor(input: DescribeZonesRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(DescribeZonesCommand.metaPath);
  }
}
/**
 * Command to DisableBackupPolicy
 */
export class DisableBackupPolicyCommand extends Command<
  DisableBackupPolicyRequest,
  DisableBackupPolicyCommandOutput,
  'DisableBackupPolicyCommand'
> {
  static readonly metaPath = '/DisableBackupPolicy/2024-03-01/cbr/post/application_json/';

  constructor(input: DisableBackupPolicyRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(DisableBackupPolicyCommand.metaPath);
  }
}
/**
 * Command to EnableBackupPolicy
 */
export class EnableBackupPolicyCommand extends Command<
  EnableBackupPolicyRequest,
  EnableBackupPolicyCommandOutput,
  'EnableBackupPolicyCommand'
> {
  static readonly metaPath = '/EnableBackupPolicy/2024-03-01/cbr/post/application_json/';

  constructor(input: EnableBackupPolicyRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(EnableBackupPolicyCommand.metaPath);
  }
}
/**
 * Command to ListTagsForResources
 */
export class ListTagsForResourcesCommand extends Command<
  ListTagsForResourcesRequest,
  ListTagsForResourcesCommandOutput,
  'ListTagsForResourcesCommand'
> {
  static readonly metaPath = '/ListTagsForResources/2024-03-01/cbr/post/application_json/';

  constructor(input: ListTagsForResourcesRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(ListTagsForResourcesCommand.metaPath);
  }
}
/**
 * Command to TagResources
 */
export class TagResourcesCommand extends Command<
  TagResourcesRequest,
  TagResourcesCommandOutput,
  'TagResourcesCommand'
> {
  static readonly metaPath = '/TagResources/2024-03-01/cbr/post/application_json/';

  constructor(input: TagResourcesRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(TagResourcesCommand.metaPath);
  }
}
/**
 * Command to UntagResources
 */
export class UntagResourcesCommand extends Command<
  UntagResourcesRequest,
  UntagResourcesCommandOutput,
  'UntagResourcesCommand'
> {
  static readonly metaPath = '/UntagResources/2024-03-01/cbr/post/application_json/';

  constructor(input: UntagResourcesRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(UntagResourcesCommand.metaPath);
  }
}
/**
 * Command to UpdateBackupPlan
 */
export class UpdateBackupPlanCommand extends Command<
  UpdateBackupPlanRequest,
  UpdateBackupPlanCommandOutput,
  'UpdateBackupPlanCommand'
> {
  static readonly metaPath = '/UpdateBackupPlan/2024-03-01/cbr/post/application_json/';

  constructor(input: UpdateBackupPlanRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(UpdateBackupPlanCommand.metaPath);
  }
}
/**
 * Command to UpdateBackupPolicy
 */
export class UpdateBackupPolicyCommand extends Command<
  UpdateBackupPolicyRequest,
  UpdateBackupPolicyCommandOutput,
  'UpdateBackupPolicyCommand'
> {
  static readonly metaPath = '/UpdateBackupPolicy/2024-03-01/cbr/post/application_json/';

  constructor(input: UpdateBackupPolicyRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(UpdateBackupPolicyCommand.metaPath);
  }
}
/**
 * Command to UpdateRecoveryPoint
 */
export class UpdateRecoveryPointCommand extends Command<
  UpdateRecoveryPointRequest,
  UpdateRecoveryPointCommandOutput,
  'UpdateRecoveryPointCommand'
> {
  static readonly metaPath = '/UpdateRecoveryPoint/2024-03-01/cbr/post/application_json/';

  constructor(input: UpdateRecoveryPointRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(UpdateRecoveryPointCommand.metaPath);
  }
}
/**
 * Command to UpdateRestoreJob
 */
export class UpdateRestoreJobCommand extends Command<
  UpdateRestoreJobRequest,
  UpdateRestoreJobCommandOutput,
  'UpdateRestoreJobCommand'
> {
  static readonly metaPath = '/UpdateRestoreJob/2024-03-01/cbr/post/application_json/';

  constructor(input: UpdateRestoreJobRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(UpdateRestoreJobCommand.metaPath);
  }
}

export default {
  CBRClient,
  CreateBackupJobCommand,
  CreateBackupPlanCommand,
  CreateBackupPolicyCommand,
  CreateBackupResourceCommand,
  CreateRestoreJobCommand,
  CreateVaultCommand,
  DeleteBackupPlanCommand,
  DeleteBackupPolicyCommand,
  DeleteBackupResourceCommand,
  DeleteRecoveryPointCommand,
  DeleteVaultCommand,
  DescribeBackupPlansCommand,
  DescribeBackupPoliciesCommand,
  DescribeBackupResourcesCommand,
  DescribeRecoveryPointsCommand,
  DescribeRegionsCommand,
  DescribeRestoreJobsCommand,
  DescribeVaultsCommand,
  DescribeZonesCommand,
  DisableBackupPolicyCommand,
  EnableBackupPolicyCommand,
  ListTagsForResourcesCommand,
  TagResourcesCommand,
  UntagResourcesCommand,
  UpdateBackupPlanCommand,
  UpdateBackupPolicyCommand,
  UpdateRecoveryPointCommand,
  UpdateRestoreJobCommand,
};
