/* tslint:disable */
/* eslint-disable */
/**
 * clb
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ConvertLoadBalancerBillingTypeResponse
 */
export interface ConvertLoadBalancerBillingTypeResponse {

    /**
     * @type {string}
     * @memberof ConvertLoadBalancerBillingTypeResponse
     */
    OrderId?: string;

    /**
     * @type {string}
     * @memberof ConvertLoadBalancerBillingTypeResponse
     */
    RequestId?: string;
}
