/* tslint:disable */
/* eslint-disable */
/**
 * clb
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { TagForCreateNLBSecurityPolicyInput } from './tag-for-create-nlbsecurity-policy-input';
 /**
 * 
 *
 * @export
 * @interface CreateNLBSecurityPolicyRequest
 */
export interface CreateNLBSecurityPolicyRequest {

    /**
     * @type {Array<string>}
     * @memberof CreateNLBSecurityPolicyRequest
     */
    Ciphers?: Array<string>;

    /**
     * @type {string}
     * @memberof CreateNLBSecurityPolicyRequest
     */
    ClientToken?: string;

    /**
     * @type {string}
     * @memberof CreateNLBSecurityPolicyRequest
     */
    ProjectName?: string;

    /**
     * @type {string}
     * @memberof CreateNLBSecurityPolicyRequest
     */
    SecurityPolicyName?: string;

    /**
     * @type {Array<TagForCreateNLBSecurityPolicyInput>}
     * @memberof CreateNLBSecurityPolicyRequest
     */
    Tags?: Array<TagForCreateNLBSecurityPolicyInput>;

    /**
     * @type {Array<string>}
     * @memberof CreateNLBSecurityPolicyRequest
     */
    TlsVersions?: Array<string>;
}
