/* tslint:disable */
/* eslint-disable */
/**
 * clb
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface DescribeListenerHealthRequest
 */
export interface DescribeListenerHealthRequest {

    /**
     * @type {string}
     * @memberof DescribeListenerHealthRequest
     */
    ListenerId: string;

    /**
     * @type {boolean}
     * @memberof DescribeListenerHealthRequest
     */
    OnlyUnHealthy?: boolean;

    /**
     * @type {number}
     * @memberof DescribeListenerHealthRequest
     */
    PageNumber?: number;

    /**
     * @type {number}
     * @memberof DescribeListenerHealthRequest
     */
    PageSize?: number;
}
