/* tslint:disable */
/* eslint-disable */
/**
 * clb
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { CertificateForDescribeCertificatesOutput } from './certificate-for-describe-certificates-output';
 /**
 * 
 *
 * @export
 * @interface DescribeCertificatesResponse
 */
export interface DescribeCertificatesResponse {

    /**
     * @type {Array<CertificateForDescribeCertificatesOutput>}
     * @memberof DescribeCertificatesResponse
     */
    Certificates?: Array<CertificateForDescribeCertificatesOutput>;

    /**
     * @type {number}
     * @memberof DescribeCertificatesResponse
     */
    PageNumber?: number;

    /**
     * @type {number}
     * @memberof DescribeCertificatesResponse
     */
    PageSize?: number;

    /**
     * @type {string}
     * @memberof DescribeCertificatesResponse
     */
    RequestId?: string;

    /**
     * @type {number}
     * @memberof DescribeCertificatesResponse
     */
    TotalCount?: number;
}
