/* tslint:disable */
/* eslint-disable */
/**
 * clb
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface RenewLoadBalancerRequest
 */
export interface RenewLoadBalancerRequest {

    /**
     * @type {string}
     * @memberof RenewLoadBalancerRequest
     */
    LoadBalancerId: string;

    /**
     * @type {number}
     * @memberof RenewLoadBalancerRequest
     */
    Period?: number;

    /**
     * @type {string}
     * @memberof RenewLoadBalancerRequest
     */
    PeriodUnit?: string;
}
