/* tslint:disable */
/* eslint-disable */
/**
 * clb
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { TagForTagResourcesInput } from './tag-for-tag-resources-input';
 /**
 * 
 *
 * @export
 * @interface TagResourcesRequest
 */
export interface TagResourcesRequest {

    /**
     * @type {Array<string>}
     * @memberof TagResourcesRequest
     */
    ResourceIds?: Array<string>;

    /**
     * @type {string}
     * @memberof TagResourcesRequest
     */
    ResourceType: TagResourcesRequestResourceTypeEnum;

    /**
     * @type {Array<TagForTagResourcesInput>}
     * @memberof TagResourcesRequest
     */
    Tags?: Array<TagForTagResourcesInput>;
}

/**
 * @export
 * @enum {string}
 */
export enum TagResourcesRequestResourceTypeEnum {
    CLB = 'CLB',
    Acl = 'acl',
    Certificate = 'certificate',
    Listener = 'listener',
    Servergroup = 'servergroup',
    Rule = 'rule',
    Ec = 'ec'
}

