/* tslint:disable */
/* eslint-disable */
/**
 * mcdn
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { StaticWeightForAddDnsScheduleStaticWeightOutput } from './static-weight-for-add-dns-schedule-static-weight-output';
 /**
 * 
 *
 * @export
 * @interface AddDnsScheduleStaticWeightResponse
 */
export interface AddDnsScheduleStaticWeightResponse {

    /**
     * @type {StaticWeightForAddDnsScheduleStaticWeightOutput}
     * @memberof AddDnsScheduleStaticWeightResponse
     */
    StaticWeight?: StaticWeightForAddDnsScheduleStaticWeightOutput;
}
