/* tslint:disable */
/* eslint-disable */
/**
 * mcdn
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ConditionForDescribeAlertStrategyOutput } from './condition-for-describe-alert-strategy-output';
 /**
 * 
 *
 * @export
 * @interface AlertRuleForDescribeAlertStrategyOutput
 */
export interface AlertRuleForDescribeAlertStrategyOutput {

    /**
     * @type {Array<ConditionForDescribeAlertStrategyOutput>}
     * @memberof AlertRuleForDescribeAlertStrategyOutput
     */
    Conditions?: Array<ConditionForDescribeAlertStrategyOutput>;

    /**
     * @type {string}
     * @memberof AlertRuleForDescribeAlertStrategyOutput
     */
    EnableEndTime?: string;

    /**
     * @type {string}
     * @memberof AlertRuleForDescribeAlertStrategyOutput
     */
    EnableStartTime?: string;

    /**
     * @type {number}
     * @memberof AlertRuleForDescribeAlertStrategyOutput
     */
    Frequency?: number;

    /**
     * @type {string}
     * @memberof AlertRuleForDescribeAlertStrategyOutput
     */
    Level?: string;

    /**
     * @type {string}
     * @memberof AlertRuleForDescribeAlertStrategyOutput
     */
    Logic?: string;
}
