/* tslint:disable */
/* eslint-disable */
/**
 * mcdn
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { DnsScheduleInfoForDescribeDnsScheduleOutput } from './dns-schedule-info-for-describe-dns-schedule-output';
import { WeightInfoForDescribeDnsScheduleOutput } from './weight-info-for-describe-dns-schedule-output';
 /**
 * 
 *
 * @export
 * @interface DescribeDnsScheduleResponse
 */
export interface DescribeDnsScheduleResponse {

    /**
     * @type {DnsScheduleInfoForDescribeDnsScheduleOutput}
     * @memberof DescribeDnsScheduleResponse
     */
    DnsScheduleInfo?: DnsScheduleInfoForDescribeDnsScheduleOutput;

    /**
     * @type {Array<WeightInfoForDescribeDnsScheduleOutput>}
     * @memberof DescribeDnsScheduleResponse
     */
    WeightInfos?: Array<WeightInfoForDescribeDnsScheduleOutput>;
}
