/* tslint:disable */
/* eslint-disable */
/**
 * mcdn
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { DataForListAlertStrategiesOutput } from './data-for-list-alert-strategies-output';
import { PaginationForListAlertStrategiesOutput } from './pagination-for-list-alert-strategies-output';
 /**
 * 
 *
 * @export
 * @interface ListAlertStrategiesResponse
 */
export interface ListAlertStrategiesResponse {

    /**
     * @type {Array<DataForListAlertStrategiesOutput>}
     * @memberof ListAlertStrategiesResponse
     */
    Data?: Array<DataForListAlertStrategiesOutput>;

    /**
     * @type {PaginationForListAlertStrategiesOutput}
     * @memberof ListAlertStrategiesResponse
     */
    Pagination?: PaginationForListAlertStrategiesOutput;
}
