/* tslint:disable */
/* eslint-disable */
/**
 * iam20210801
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface GetProjectResponse
 */
export interface GetProjectResponse {

    /**
     * @type {number}
     * @memberof GetProjectResponse
     */
    AccountID?: number;

    /**
     * @type {string}
     * @memberof GetProjectResponse
     */
    CreateDate?: string;

    /**
     * @type {string}
     * @memberof GetProjectResponse
     */
    Description?: string;

    /**
     * @type {string}
     * @memberof GetProjectResponse
     */
    DisplayName?: string;

    /**
     * @type {string}
     * @memberof GetProjectResponse
     */
    ParentProjectName?: string;

    /**
     * @type {string}
     * @memberof GetProjectResponse
     */
    Path?: string;

    /**
     * @type {string}
     * @memberof GetProjectResponse
     */
    ProjectName?: string;

    /**
     * @type {string}
     * @memberof GetProjectResponse
     */
    Status?: string;

    /**
     * @type {string}
     * @memberof GetProjectResponse
     */
    UpdateDate?: string;
}
