/* tslint:disable */
/* eslint-disable */
/**
 * cloudidentity
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ListGroupsRequest
 */
export interface ListGroupsRequest {

    /**
     * @type {string}
     * @memberof ListGroupsRequest
     */
    JoinType?: ListGroupsRequestJoinTypeEnum;

    /**
     * @type {number}
     * @memberof ListGroupsRequest
     */
    PageNumber?: number;

    /**
     * @type {number}
     * @memberof ListGroupsRequest
     */
    PageSize?: number;

    /**
     * @type {string}
     * @memberof ListGroupsRequest
     */
    QueryString?: string;
}

/**
 * @export
 * @enum {string}
 */
export enum ListGroupsRequestJoinTypeEnum {
    Manual = 'Manual',
    Auto = 'Auto'
}

