/* tslint:disable */
/* eslint-disable */
/**
 * cloudidentity
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ListGroupMembersRequest
 */
export interface ListGroupMembersRequest {

    /**
     * @type {string}
     * @memberof ListGroupMembersRequest
     */
    GroupId: string;

    /**
     * @type {number}
     * @memberof ListGroupMembersRequest
     */
    PageNumber?: number;

    /**
     * @type {number}
     * @memberof ListGroupMembersRequest
     */
    PageSize?: number;

    /**
     * @type {string}
     * @memberof ListGroupMembersRequest
     */
    QueryString?: string;
}
