/* tslint:disable */
/* eslint-disable */
/**
 * cloudidentity
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { SCIMServerCredentialForListSCIMServerCredentialsOutput } from './scimserver-credential-for-list-scimserver-credentials-output';
 /**
 * 
 *
 * @export
 * @interface ListSCIMServerCredentialsResponse
 */
export interface ListSCIMServerCredentialsResponse {

    /**
     * @type {Array<SCIMServerCredentialForListSCIMServerCredentialsOutput>}
     * @memberof ListSCIMServerCredentialsResponse
     */
    SCIMServerCredentials?: Array<SCIMServerCredentialForListSCIMServerCredentialsOutput>;
}
