/* tslint:disable */
/* eslint-disable */
/**
 * dcdn
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface BackupOriginForUpdateSingleDomainConfigInput
 */
export interface BackupOriginForUpdateSingleDomainConfigInput {

    /**
     * @type {string}
     * @memberof BackupOriginForUpdateSingleDomainConfigInput
     */
    Name?: string;

    /**
     * @type {number}
     * @memberof BackupOriginForUpdateSingleDomainConfigInput
     */
    Port?: number;

    /**
     * @type {string}
     * @memberof BackupOriginForUpdateSingleDomainConfigInput
     */
    Type?: string;

    /**
     * @type {number}
     * @memberof BackupOriginForUpdateSingleDomainConfigInput
     */
    Weight?: number;
}
