/* tslint:disable */
/* eslint-disable */
/**
 * dcdn
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface CacheRuleForDescribeDomainDetailOutput
 */
export interface CacheRuleForDescribeDomainDetailOutput {

    /**
     * @type {number}
     * @memberof CacheRuleForDescribeDomainDetailOutput
     */
    CacheTime?: number;

    /**
     * @type {string}
     * @memberof CacheRuleForDescribeDomainDetailOutput
     */
    CacheTimeUnit?: string;

    /**
     * @type {string}
     * @memberof CacheRuleForDescribeDomainDetailOutput
     */
    Contents?: string;

    /**
     * @type {boolean}
     * @memberof CacheRuleForDescribeDomainDetailOutput
     */
    IgnoreCase?: boolean;

    /**
     * @type {string}
     * @memberof CacheRuleForDescribeDomainDetailOutput
     */
    ParamsFilterType?: string;

    /**
     * @type {string}
     * @memberof CacheRuleForDescribeDomainDetailOutput
     */
    ParamsReserveList?: string;

    /**
     * @type {string}
     * @memberof CacheRuleForDescribeDomainDetailOutput
     */
    Policy?: string;

    /**
     * @type {string}
     * @memberof CacheRuleForDescribeDomainDetailOutput
     */
    Type?: string;
}
