/* tslint:disable */
/* eslint-disable */
/**
 * dcdn
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { BackupOriginForUpdateSingleDomainConfigInput } from './backup-origin-for-update-single-domain-config-input';
 /**
 * 
 *
 * @export
 * @interface ConditionalOriginForUpdateSingleDomainConfigInput
 */
export interface ConditionalOriginForUpdateSingleDomainConfigInput {

    /**
     * @type {Array<BackupOriginForUpdateSingleDomainConfigInput>}
     * @memberof ConditionalOriginForUpdateSingleDomainConfigInput
     */
    BackupOrigins?: Array<BackupOriginForUpdateSingleDomainConfigInput>;

    /**
     * @type {string}
     * @memberof ConditionalOriginForUpdateSingleDomainConfigInput
     */
    MatchingRuleGroupJSON?: string;

    /**
     * @type {string}
     * @memberof ConditionalOriginForUpdateSingleDomainConfigInput
     */
    Name?: string;

    /**
     * @type {Array<BackupOriginForUpdateSingleDomainConfigInput>}
     * @memberof ConditionalOriginForUpdateSingleDomainConfigInput
     */
    Origins?: Array<BackupOriginForUpdateSingleDomainConfigInput>;
}
