/* tslint:disable */
/* eslint-disable */
/**
 * dcdn
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface DescribeTopDomainsRequest
 */
export interface DescribeTopDomainsRequest {

    /**
     * @type {string}
     * @memberof DescribeTopDomainsRequest
     */
    AcceleratingRegion?: string;

    /**
     * @type {string}
     * @memberof DescribeTopDomainsRequest
     */
    Area?: string;

    /**
     * @type {Array<string>}
     * @memberof DescribeTopDomainsRequest
     */
    Domains?: Array<string>;

    /**
     * @type {string}
     * @memberof DescribeTopDomainsRequest
     */
    EndTime: string;

    /**
     * @type {string}
     * @memberof DescribeTopDomainsRequest
     */
    IPVersion?: string;

    /**
     * @type {Array<string>}
     * @memberof DescribeTopDomainsRequest
     */
    IspNameEn?: Array<string>;

    /**
     * @type {number}
     * @memberof DescribeTopDomainsRequest
     */
    Limit?: number;

    /**
     * @type {Array<string>}
     * @memberof DescribeTopDomainsRequest
     */
    ProjectName?: Array<string>;

    /**
     * @type {Array<string>}
     * @memberof DescribeTopDomainsRequest
     */
    Protocol?: Array<string>;

    /**
     * @type {Array<string>}
     * @memberof DescribeTopDomainsRequest
     */
    Region?: Array<string>;

    /**
     * @type {string}
     * @memberof DescribeTopDomainsRequest
     */
    Sort: string;

    /**
     * @type {string}
     * @memberof DescribeTopDomainsRequest
     */
    StartTime: string;

    /**
     * @type {string}
     * @memberof DescribeTopDomainsRequest
     */
    Type?: string;
}
