/* tslint:disable */
/* eslint-disable */
/**
 * dcdn
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface DescribeDomainLogsRequest
 */
export interface DescribeDomainLogsRequest {

    /**
     * @type {string}
     * @memberof DescribeDomainLogsRequest
     */
    Domain: string;

    /**
     * @type {string}
     * @memberof DescribeDomainLogsRequest
     */
    EndTime: string;

    /**
     * @type {number}
     * @memberof DescribeDomainLogsRequest
     */
    PageNum?: number;

    /**
     * @type {number}
     * @memberof DescribeDomainLogsRequest
     */
    PageSize?: number;

    /**
     * @type {Array<string>}
     * @memberof DescribeDomainLogsRequest
     */
    ProjectName?: Array<string>;

    /**
     * @type {string}
     * @memberof DescribeDomainLogsRequest
     */
    StartTime: string;
}
