/* tslint:disable */
/* eslint-disable */
/**
 * dcdn
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { HeaderInfoForDescribeDomainDetailOutput } from './header-info-for-describe-domain-detail-output';
 /**
 * 
 *
 * @export
 * @interface ResponseHeaderForDescribeDomainDetailOutput
 */
export interface ResponseHeaderForDescribeDomainDetailOutput {

    /**
     * @type {boolean}
     * @memberof ResponseHeaderForDescribeDomainDetailOutput
     */
    Enable?: boolean;

    /**
     * @type {Array<HeaderInfoForDescribeDomainDetailOutput>}
     * @memberof ResponseHeaderForDescribeDomainDetailOutput
     */
    HeaderInfo?: Array<HeaderInfoForDescribeDomainDetailOutput>;
}
