/* tslint:disable */
/* eslint-disable */
/**
 * redis
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface CreateDBAccountRequest
 */
export interface CreateDBAccountRequest {

    /**
     * @type {string}
     * @memberof CreateDBAccountRequest
     */
    AccountName: string;

    /**
     * @type {string}
     * @memberof CreateDBAccountRequest
     */
    ClientToken?: string;

    /**
     * @type {string}
     * @memberof CreateDBAccountRequest
     */
    Description?: string;

    /**
     * @type {string}
     * @memberof CreateDBAccountRequest
     */
    InstanceId: string;

    /**
     * @type {string}
     * @memberof CreateDBAccountRequest
     */
    Password: string;

    /**
     * @type {string}
     * @memberof CreateDBAccountRequest
     */
    RoleName: string;
}
