/* tslint:disable */
/* eslint-disable */
/**
 * redis
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ParameterGroupForDescribeParameterGroupsOutput } from './parameter-group-for-describe-parameter-groups-output';
 /**
 * 
 *
 * @export
 * @interface DescribeParameterGroupsResponse
 */
export interface DescribeParameterGroupsResponse {

    /**
     * @type {Array<ParameterGroupForDescribeParameterGroupsOutput>}
     * @memberof DescribeParameterGroupsResponse
     */
    ParameterGroups?: Array<ParameterGroupForDescribeParameterGroupsOutput>;

    /**
     * @type {number}
     * @memberof DescribeParameterGroupsResponse
     */
    Total?: number;
}
