/* tslint:disable */
/* eslint-disable */
/**
 * redis
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface SlowQueryForDescribeSlowLogsOutput
 */
export interface SlowQueryForDescribeSlowLogsOutput {

    /**
     * @type {string}
     * @memberof SlowQueryForDescribeSlowLogsOutput
     */
    DBName?: string;

    /**
     * @type {string}
     * @memberof SlowQueryForDescribeSlowLogsOutput
     */
    ExecutionStartTime?: string;

    /**
     * @type {string}
     * @memberof SlowQueryForDescribeSlowLogsOutput
     */
    HostAddress?: string;

    /**
     * @type {string}
     * @memberof SlowQueryForDescribeSlowLogsOutput
     */
    InstanceId?: string;

    /**
     * @type {string}
     * @memberof SlowQueryForDescribeSlowLogsOutput
     */
    NodeId?: string;

    /**
     * @type {string}
     * @memberof SlowQueryForDescribeSlowLogsOutput
     */
    QueryText?: string;

    /**
     * @type {number}
     * @memberof SlowQueryForDescribeSlowLogsOutput
     */
    QueryTimes?: number;

    /**
     * @type {string}
     * @memberof SlowQueryForDescribeSlowLogsOutput
     */
    UserName?: string;
}
