/* tslint:disable */
/* eslint-disable */
/**
 * milvus
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ChargeConfigForCreateInstanceOneStepInput } from './charge-config-for-create-instance-one-step-input';
import { InstanceConfigurationForCreateInstanceOneStepInput } from './instance-configuration-for-create-instance-one-step-input';
import { NetworkConfigForCreateInstanceOneStepInput } from './network-config-for-create-instance-one-step-input';
import { TagForCreateInstanceOneStepInput } from './tag-for-create-instance-one-step-input';
 /**
 * 
 *
 * @export
 * @interface CreateInstanceOneStepRequest
 */
export interface CreateInstanceOneStepRequest {

    /**
     * @type {ChargeConfigForCreateInstanceOneStepInput}
     * @memberof CreateInstanceOneStepRequest
     */
    ChargeConfig?: ChargeConfigForCreateInstanceOneStepInput;

    /**
     * @type {boolean}
     * @memberof CreateInstanceOneStepRequest
     */
    DeleteProtectEnabled?: boolean;

    /**
     * @type {InstanceConfigurationForCreateInstanceOneStepInput}
     * @memberof CreateInstanceOneStepRequest
     */
    InstanceConfiguration?: InstanceConfigurationForCreateInstanceOneStepInput;

    /**
     * @type {NetworkConfigForCreateInstanceOneStepInput}
     * @memberof CreateInstanceOneStepRequest
     */
    NetworkConfig?: NetworkConfigForCreateInstanceOneStepInput;

    /**
     * @type {string}
     * @memberof CreateInstanceOneStepRequest
     */
    ProjectName?: string;

    /**
     * @type {string}
     * @memberof CreateInstanceOneStepRequest
     */
    Region: string;

    /**
     * @type {Array<TagForCreateInstanceOneStepInput>}
     * @memberof CreateInstanceOneStepRequest
     */
    Tags?: Array<TagForCreateInstanceOneStepInput>;

    /**
     * @type {Array<string>}
     * @memberof CreateInstanceOneStepRequest
     */
    Zones?: Array<string>;
}
