/* tslint:disable */
/* eslint-disable */
/**
 * cr
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { FailureForDeleteTagsOutput } from './failure-for-delete-tags-output';
import { SuccessForDeleteTagsOutput } from './success-for-delete-tags-output';
 /**
 * 
 *
 * @export
 * @interface DeleteTagsResponse
 */
export interface DeleteTagsResponse {

    /**
     * @type {Array<FailureForDeleteTagsOutput>}
     * @memberof DeleteTagsResponse
     */
    Failures?: Array<FailureForDeleteTagsOutput>;

    /**
     * @type {Array<SuccessForDeleteTagsOutput>}
     * @memberof DeleteTagsResponse
     */
    Successes?: Array<SuccessForDeleteTagsOutput>;
}
