/* tslint:disable */
/* eslint-disable */
/**
 * cr
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface UpdateRobotAccountPasswordRequest
 */
export interface UpdateRobotAccountPasswordRequest {

    /**
     * @type {string}
     * @memberof UpdateRobotAccountPasswordRequest
     */
    Password?: string;

    /**
     * @type {boolean}
     * @memberof UpdateRobotAccountPasswordRequest
     */
    Random: boolean;

    /**
     * @type {string}
     * @memberof UpdateRobotAccountPasswordRequest
     */
    Registry: string;

    /**
     * @type {string}
     * @memberof UpdateRobotAccountPasswordRequest
     */
    Username: string;
}
