/* tslint:disable */
/* eslint-disable */
/**
 * rds_mysql_v2
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { KeywordRouteStrategyForDescribeDBInstanceEndpointsOutput } from './keyword-route-strategy-for-describe-dbinstance-endpoints-output';
 /**
 * 
 *
 * @export
 * @interface CustomRouteStrategyForDescribeDBInstanceEndpointsOutput
 */
export interface CustomRouteStrategyForDescribeDBInstanceEndpointsOutput {

    /**
     * @type {Array<KeywordRouteStrategyForDescribeDBInstanceEndpointsOutput>}
     * @memberof CustomRouteStrategyForDescribeDBInstanceEndpointsOutput
     */
    KeywordRouteStrategy?: Array<KeywordRouteStrategyForDescribeDBInstanceEndpointsOutput>;
}
