/* tslint:disable */
/* eslint-disable */
/**
 * rds_mysql_v2
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ModifyBackupPublicAccessPolicyResponse
 */
export interface ModifyBackupPublicAccessPolicyResponse {

    /**
     * @type {string}
     * @memberof ModifyBackupPublicAccessPolicyResponse
     */
    InstanceId?: string;

    /**
     * @type {boolean}
     * @memberof ModifyBackupPublicAccessPolicyResponse
     */
    PublicDownloadEnable?: boolean;
}
