/* tslint:disable */
/* eslint-disable */
/**
 * rds_mysql_v2
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { NodeParameterValueDetailForDescribeDBNodeParameterDifferencesOutput } from './node-parameter-value-detail-for-describe-dbnode-parameter-differences-output';
 /**
 * 
 *
 * @export
 * @interface NodeDifferentParameterForDescribeDBNodeParameterDifferencesOutput
 */
export interface NodeDifferentParameterForDescribeDBNodeParameterDifferencesOutput {

    /**
     * @type {Array<NodeParameterValueDetailForDescribeDBNodeParameterDifferencesOutput>}
     * @memberof NodeDifferentParameterForDescribeDBNodeParameterDifferencesOutput
     */
    NodeParameterValueDetails?: Array<NodeParameterValueDetailForDescribeDBNodeParameterDifferencesOutput>;

    /**
     * @type {string}
     * @memberof NodeDifferentParameterForDescribeDBNodeParameterDifferencesOutput
     */
    ParameterName?: string;
}
