/* tslint:disable */
/* eslint-disable */
/**
 * graph
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { NetworkResourceForGetVegraphNetworkResourceOutput } from './network-resource-for-get-vegraph-network-resource-output';
 /**
 * 
 *
 * @export
 * @interface GetVegraphNetworkResourceResponse
 */
export interface GetVegraphNetworkResourceResponse {

    /**
     * @type {Array<NetworkResourceForGetVegraphNetworkResourceOutput>}
     * @memberof GetVegraphNetworkResourceResponse
     */
    NetworkResources?: Array<NetworkResourceForGetVegraphNetworkResourceOutput>;
}
