/* tslint:disable */
/* eslint-disable */
/**
 * hbase
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface CreateAllowListRequest
 */
export interface CreateAllowListRequest {

    /**
     * @type {string}
     * @memberof CreateAllowListRequest
     */
    AllowList?: string;

    /**
     * @type {string}
     * @memberof CreateAllowListRequest
     */
    AllowListDesc?: string;

    /**
     * @type {string}
     * @memberof CreateAllowListRequest
     */
    AllowListName?: string;

    /**
     * @type {string}
     * @memberof CreateAllowListRequest
     */
    AllowListType?: string;

    /**
     * @type {string}
     * @memberof CreateAllowListRequest
     */
    ProjectName?: string;
}
