/* tslint:disable */
/* eslint-disable */
/**
 * config
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { PreviousConfigurationForGetResourceConfigHistoryOutput } from './previous-configuration-for-get-resource-config-history-output';
import { RelationshipForGetResourceConfigHistoryOutput } from './relationship-for-get-resource-config-history-output';
import { TagForGetResourceConfigHistoryOutput } from './tag-for-get-resource-config-history-output';
 /**
 * 
 *
 * @export
 * @interface ConfigurationItemForGetResourceConfigHistoryOutput
 */
export interface ConfigurationItemForGetResourceConfigHistoryOutput {

    /**
     * @type {string}
     * @memberof ConfigurationItemForGetResourceConfigHistoryOutput
     */
    AccountId?: string;

    /**
     * @type {{ [key: string]: any; }}
     * @memberof ConfigurationItemForGetResourceConfigHistoryOutput
     */
    Configuration?: { [key: string]: any; };

    /**
     * @type {string}
     * @memberof ConfigurationItemForGetResourceConfigHistoryOutput
     */
    ConfigurationCaptureTime?: string;

    /**
     * @type {PreviousConfigurationForGetResourceConfigHistoryOutput}
     * @memberof ConfigurationItemForGetResourceConfigHistoryOutput
     */
    PreviousConfiguration?: PreviousConfigurationForGetResourceConfigHistoryOutput;

    /**
     * @type {string}
     * @memberof ConfigurationItemForGetResourceConfigHistoryOutput
     */
    ProjectName?: string;

    /**
     * @type {string}
     * @memberof ConfigurationItemForGetResourceConfigHistoryOutput
     */
    Region?: string;

    /**
     * @type {Array<RelationshipForGetResourceConfigHistoryOutput>}
     * @memberof ConfigurationItemForGetResourceConfigHistoryOutput
     */
    Relationships?: Array<RelationshipForGetResourceConfigHistoryOutput>;

    /**
     * @type {string}
     * @memberof ConfigurationItemForGetResourceConfigHistoryOutput
     */
    ResourceCreationTime?: string;

    /**
     * @type {string}
     * @memberof ConfigurationItemForGetResourceConfigHistoryOutput
     */
    ResourceEventType?: string;

    /**
     * @type {string}
     * @memberof ConfigurationItemForGetResourceConfigHistoryOutput
     */
    ResourceIdentifier?: string;

    /**
     * @type {string}
     * @memberof ConfigurationItemForGetResourceConfigHistoryOutput
     */
    ResourceName?: string;

    /**
     * @type {string}
     * @memberof ConfigurationItemForGetResourceConfigHistoryOutput
     */
    ResourceType?: string;

    /**
     * @type {Array<TagForGetResourceConfigHistoryOutput>}
     * @memberof ConfigurationItemForGetResourceConfigHistoryOutput
     */
    Tags?: Array<TagForGetResourceConfigHistoryOutput>;
}
