/* tslint:disable */
/* eslint-disable */
/**
 * config
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface GetAccountGroupDiscoveredResourceRequest
 */
export interface GetAccountGroupDiscoveredResourceRequest {

    /**
     * @type {string}
     * @memberof GetAccountGroupDiscoveredResourceRequest
     */
    AccountGroupId: string;

    /**
     * @type {number}
     * @memberof GetAccountGroupDiscoveredResourceRequest
     */
    AccountId: number;

    /**
     * @type {string}
     * @memberof GetAccountGroupDiscoveredResourceRequest
     */
    Region: string;

    /**
     * @type {string}
     * @memberof GetAccountGroupDiscoveredResourceRequest
     */
    ResourceIdentifier: string;

    /**
     * @type {string}
     * @memberof GetAccountGroupDiscoveredResourceRequest
     */
    ResourceType: string;
}
