/* tslint:disable */
/* eslint-disable */
/**
 * alb
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { TagForDescribeAllCertificatesOutput } from './tag-for-describe-all-certificates-output';
 /**
 * 
 *
 * @export
 * @interface CertificateForDescribeAllCertificatesOutput
 */
export interface CertificateForDescribeAllCertificatesOutput {

    /**
     * @type {string}
     * @memberof CertificateForDescribeAllCertificatesOutput
     */
    CertificateId?: string;

    /**
     * @type {string}
     * @memberof CertificateForDescribeAllCertificatesOutput
     */
    CertificateName?: string;

    /**
     * @type {string}
     * @memberof CertificateForDescribeAllCertificatesOutput
     */
    CertificateType?: string;

    /**
     * @type {string}
     * @memberof CertificateForDescribeAllCertificatesOutput
     */
    CreateTime?: string;

    /**
     * @type {string}
     * @memberof CertificateForDescribeAllCertificatesOutput
     */
    Description?: string;

    /**
     * @type {string}
     * @memberof CertificateForDescribeAllCertificatesOutput
     */
    DomainName?: string;

    /**
     * @type {string}
     * @memberof CertificateForDescribeAllCertificatesOutput
     */
    ExpiredAt?: string;

    /**
     * @type {Array<string>}
     * @memberof CertificateForDescribeAllCertificatesOutput
     */
    Listeners?: Array<string>;

    /**
     * @type {string}
     * @memberof CertificateForDescribeAllCertificatesOutput
     */
    ProjectName?: string;

    /**
     * @type {string}
     * @memberof CertificateForDescribeAllCertificatesOutput
     */
    San?: string;

    /**
     * @type {string}
     * @memberof CertificateForDescribeAllCertificatesOutput
     */
    Status?: string;

    /**
     * @type {Array<TagForDescribeAllCertificatesOutput>}
     * @memberof CertificateForDescribeAllCertificatesOutput
     */
    Tags?: Array<TagForDescribeAllCertificatesOutput>;
}
