/* tslint:disable */
/* eslint-disable */
/**
 * alb
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { DomainExtensionForCreateListenerInput } from './domain-extension-for-create-listener-input';
import { TagForCreateListenerInput } from './tag-for-create-listener-input';
 /**
 * 
 *
 * @export
 * @interface CreateListenerRequest
 */
export interface CreateListenerRequest {

    /**
     * @type {string}
     * @memberof CreateListenerRequest
     */
    AccessLogRecordCustomizedHeadersEnabled?: string;

    /**
     * @type {Array<string>}
     * @memberof CreateListenerRequest
     */
    AclIds?: Array<string>;

    /**
     * @type {string}
     * @memberof CreateListenerRequest
     */
    AclStatus?: string;

    /**
     * @type {string}
     * @memberof CreateListenerRequest
     */
    AclType?: string;

    /**
     * @type {string}
     * @memberof CreateListenerRequest
     */
    CACertificateId?: string;

    /**
     * @type {string}
     * @memberof CreateListenerRequest
     */
    CACertificateSource?: string;

    /**
     * @type {string}
     * @memberof CreateListenerRequest
     */
    CertCenterCertificateId?: string;

    /**
     * @type {string}
     * @memberof CreateListenerRequest
     */
    CertificateId?: string;

    /**
     * @type {string}
     * @memberof CreateListenerRequest
     */
    CertificateSource?: string;

    /**
     * @type {string}
     * @memberof CreateListenerRequest
     */
    Description?: string;

    /**
     * @type {Array<DomainExtensionForCreateListenerInput>}
     * @memberof CreateListenerRequest
     */
    DomainExtensions?: Array<DomainExtensionForCreateListenerInput>;

    /**
     * @type {string}
     * @memberof CreateListenerRequest
     */
    EnableHttp2?: string;

    /**
     * @type {string}
     * @memberof CreateListenerRequest
     */
    EnableQuic?: string;

    /**
     * @type {string}
     * @memberof CreateListenerRequest
     */
    Enabled?: string;

    /**
     * @type {string}
     * @memberof CreateListenerRequest
     */
    ListenerName?: string;

    /**
     * @type {string}
     * @memberof CreateListenerRequest
     */
    LoadBalancerId: string;

    /**
     * @type {string}
     * @memberof CreateListenerRequest
     */
    PcaLeafCertificateId?: string;

    /**
     * @type {string}
     * @memberof CreateListenerRequest
     */
    PcaRootCACertificateId?: string;

    /**
     * @type {string}
     * @memberof CreateListenerRequest
     */
    PcaSubCACertificateId?: string;

    /**
     * @type {number}
     * @memberof CreateListenerRequest
     */
    Port: number;

    /**
     * @type {string}
     * @memberof CreateListenerRequest
     */
    Protocol: string;

    /**
     * @type {string}
     * @memberof CreateListenerRequest
     */
    ServerGroupId: string;

    /**
     * @type {Array<TagForCreateListenerInput>}
     * @memberof CreateListenerRequest
     */
    Tags?: Array<TagForCreateListenerInput>;
}
