/* tslint:disable */
/* eslint-disable */
/**
 * alb
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ServerForDescribeServerGroupBackendServersOutput } from './server-for-describe-server-group-backend-servers-output';
 /**
 * 
 *
 * @export
 * @interface DescribeServerGroupBackendServersResponse
 */
export interface DescribeServerGroupBackendServersResponse {

    /**
     * @type {number}
     * @memberof DescribeServerGroupBackendServersResponse
     */
    PageNumber?: number;

    /**
     * @type {number}
     * @memberof DescribeServerGroupBackendServersResponse
     */
    PageSize?: number;

    /**
     * @type {string}
     * @memberof DescribeServerGroupBackendServersResponse
     */
    RequestId?: string;

    /**
     * @type {Array<ServerForDescribeServerGroupBackendServersOutput>}
     * @memberof DescribeServerGroupBackendServersResponse
     */
    Servers?: Array<ServerForDescribeServerGroupBackendServersOutput>;

    /**
     * @type {number}
     * @memberof DescribeServerGroupBackendServersResponse
     */
    TotalCount?: number;
}
