/* tslint:disable */
/* eslint-disable */
/**
 * alb
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface EnableHealthLogRequest
 */
export interface EnableHealthLogRequest {

    /**
     * @type {string}
     * @memberof EnableHealthLogRequest
     */
    LoadBalancerId: string;

    /**
     * @type {string}
     * @memberof EnableHealthLogRequest
     */
    ProjectId: string;

    /**
     * @type {string}
     * @memberof EnableHealthLogRequest
     */
    TopicId: string;
}
