/* tslint:disable */
/* eslint-disable */
/**
 * alb
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ServerForDescribeServerGroupBackendServersOutput
 */
export interface ServerForDescribeServerGroupBackendServersOutput {

    /**
     * @type {string}
     * @memberof ServerForDescribeServerGroupBackendServersOutput
     */
    Description?: string;

    /**
     * @type {string}
     * @memberof ServerForDescribeServerGroupBackendServersOutput
     */
    InstanceId?: string;

    /**
     * @type {string}
     * @memberof ServerForDescribeServerGroupBackendServersOutput
     */
    Ip?: string;

    /**
     * @type {number}
     * @memberof ServerForDescribeServerGroupBackendServersOutput
     */
    Port?: number;

    /**
     * @type {string}
     * @memberof ServerForDescribeServerGroupBackendServersOutput
     */
    RemoteEnabled?: string;

    /**
     * @type {string}
     * @memberof ServerForDescribeServerGroupBackendServersOutput
     */
    ServerId?: string;

    /**
     * @type {string}
     * @memberof ServerForDescribeServerGroupBackendServersOutput
     */
    Type?: string;

    /**
     * @type {number}
     * @memberof ServerForDescribeServerGroupBackendServersOutput
     */
    Weight?: number;
}
