/* tslint:disable */
/* eslint-disable */
/**
 * rocketmq
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface AccessPolicyForDescribeTopicAccessPoliciesOutput
 */
export interface AccessPolicyForDescribeTopicAccessPoliciesOutput {

    /**
     * @type {string}
     * @memberof AccessPolicyForDescribeTopicAccessPoliciesOutput
     */
    AccessKey?: string;

    /**
     * @type {string}
     * @memberof AccessPolicyForDescribeTopicAccessPoliciesOutput
     */
    Authority?: string;
}
