/* tslint:disable */
/* eslint-disable */
/**
 * rocketmq
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ResendDLQMessageByIdRequest
 */
export interface ResendDLQMessageByIdRequest {

    /**
     * @type {string}
     * @memberof ResendDLQMessageByIdRequest
     */
    GroupId: string;

    /**
     * @type {string}
     * @memberof ResendDLQMessageByIdRequest
     */
    InstanceId: string;

    /**
     * @type {Array<string>}
     * @memberof ResendDLQMessageByIdRequest
     */
    MessageIds?: Array<string>;
}
