/* tslint:disable */
/* eslint-disable */
/**
 * id
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ApiKeyMetadataForCreateApiKeyCredentialProviderInput
 */
export interface ApiKeyMetadataForCreateApiKeyCredentialProviderInput {

    /**
     * @type {string}
     * @memberof ApiKeyMetadataForCreateApiKeyCredentialProviderInput
     */
    Location?: string;

    /**
     * @type {string}
     * @memberof ApiKeyMetadataForCreateApiKeyCredentialProviderInput
     */
    ParameterName?: string;

    /**
     * @type {string}
     * @memberof ApiKeyMetadataForCreateApiKeyCredentialProviderInput
     */
    Prefix?: string;
}
