/* tslint:disable */
/* eslint-disable */
/**
 * id
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface AttributeForCreateRouteOutput
 */
export interface AttributeForCreateRouteOutput {

    /**
     * @type {string}
     * @memberof AttributeForCreateRouteOutput
     */
    Field?: string;

    /**
     * @type {string}
     * @memberof AttributeForCreateRouteOutput
     */
    Target?: string;
}
