/* tslint:disable */
/* eslint-disable */
/**
 * id
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { CreatedForBatchCreateRoutesOutput } from './created-for-batch-create-routes-output';
import { FailedForBatchCreateRoutesOutput } from './failed-for-batch-create-routes-output';
import { UpdatedForBatchCreateRoutesOutput } from './updated-for-batch-create-routes-output';
 /**
 * 
 *
 * @export
 * @interface BatchCreateRoutesResponse
 */
export interface BatchCreateRoutesResponse {

    /**
     * @type {Array<CreatedForBatchCreateRoutesOutput>}
     * @memberof BatchCreateRoutesResponse
     */
    Created?: Array<CreatedForBatchCreateRoutesOutput>;

    /**
     * @type {Array<string>}
     * @memberof BatchCreateRoutesResponse
     */
    Deleted?: Array<string>;

    /**
     * @type {Array<FailedForBatchCreateRoutesOutput>}
     * @memberof BatchCreateRoutesResponse
     */
    Failed?: Array<FailedForBatchCreateRoutesOutput>;

    /**
     * @type {Array<string>}
     * @memberof BatchCreateRoutesResponse
     */
    Skipped?: Array<string>;

    /**
     * @type {Array<UpdatedForBatchCreateRoutesOutput>}
     * @memberof BatchCreateRoutesResponse
     */
    Updated?: Array<UpdatedForBatchCreateRoutesOutput>;
}
