/* tslint:disable */
/* eslint-disable */
/**
 * id
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ClaimRuleForUpdateIdentityProviderOIDCOutput } from './claim-rule-for-update-identity-provider-oidcoutput';
 /**
 * 
 *
 * @export
 * @interface ClaimsPropagationConfigForUpdateIdentityProviderOIDCOutput
 */
export interface ClaimsPropagationConfigForUpdateIdentityProviderOIDCOutput {

    /**
     * @type {Array<ClaimRuleForUpdateIdentityProviderOIDCOutput>}
     * @memberof ClaimsPropagationConfigForUpdateIdentityProviderOIDCOutput
     */
    ClaimRules?: Array<ClaimRuleForUpdateIdentityProviderOIDCOutput>;

    /**
     * @type {string}
     * @memberof ClaimsPropagationConfigForUpdateIdentityProviderOIDCOutput
     */
    Mode?: string;
}
