/* tslint:disable */
/* eslint-disable */
/**
 * id
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface CreateApiKeyCredentialProviderResponse
 */
export interface CreateApiKeyCredentialProviderResponse {

    /**
     * @type {string}
     * @memberof CreateApiKeyCredentialProviderResponse
     */
    CredentialProviderTrn?: string;

    /**
     * @type {string}
     * @memberof CreateApiKeyCredentialProviderResponse
     */
    Name?: string;

    /**
     * @type {string}
     * @memberof CreateApiKeyCredentialProviderResponse
     */
    SecretTrn?: string;
}
