/* tslint:disable */
/* eslint-disable */
/**
 * id
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface DataForListPoliciesOutput
 */
export interface DataForListPoliciesOutput {

    /**
     * @type {string}
     * @memberof DataForListPoliciesOutput
     */
    CreateTime?: string;

    /**
     * @type {string}
     * @memberof DataForListPoliciesOutput
     */
    Description?: string;

    /**
     * @type {string}
     * @memberof DataForListPoliciesOutput
     */
    NamespaceId?: string;

    /**
     * @type {string}
     * @memberof DataForListPoliciesOutput
     */
    Policy?: string;

    /**
     * @type {string}
     * @memberof DataForListPoliciesOutput
     */
    PolicyId?: string;

    /**
     * @type {string}
     * @memberof DataForListPoliciesOutput
     */
    PolicyName?: string;

    /**
     * @type {string}
     * @memberof DataForListPoliciesOutput
     */
    Trn?: string;

    /**
     * @type {string}
     * @memberof DataForListPoliciesOutput
     */
    UpdateTime?: string;
}
