/* tslint:disable */
/* eslint-disable */
/**
 * id
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface GetWorkloadAccessTokenForJWTRequest
 */
export interface GetWorkloadAccessTokenForJWTRequest {

    /**
     * @type {Array<string>}
     * @memberof GetWorkloadAccessTokenForJWTRequest
     */
    Audience?: Array<string>;

    /**
     * @type {number}
     * @memberof GetWorkloadAccessTokenForJWTRequest
     */
    DurationSeconds?: number;

    /**
     * @type {string}
     * @memberof GetWorkloadAccessTokenForJWTRequest
     */
    Name?: string;

    /**
     * @type {string}
     * @memberof GetWorkloadAccessTokenForJWTRequest
     */
    UserToken: string;

    /**
     * @type {string}
     * @memberof GetWorkloadAccessTokenForJWTRequest
     */
    WorkloadPoolName?: string;
}
