/* tslint:disable */
/* eslint-disable */
/**
 * id
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { FilterForListUserPoolsInput } from './filter-for-list-user-pools-input';
 /**
 * 
 *
 * @export
 * @interface ListUserPoolsRequest
 */
export interface ListUserPoolsRequest {

    /**
     * @type {FilterForListUserPoolsInput}
     * @memberof ListUserPoolsRequest
     */
    Filter?: FilterForListUserPoolsInput;

    /**
     * @type {number}
     * @memberof ListUserPoolsRequest
     */
    PageNumber: number;

    /**
     * @type {number}
     * @memberof ListUserPoolsRequest
     */
    PageSize: number;

    /**
     * @type {string}
     * @memberof ListUserPoolsRequest
     */
    ProjectName?: string;

    /**
     * @type {string}
     * @memberof ListUserPoolsRequest
     */
    SortDirection?: string;

    /**
     * @type {string}
     * @memberof ListUserPoolsRequest
     */
    SortField?: string;
}
