/* tslint:disable */
/* eslint-disable */
/**
 * id
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { FilterForListCredentialProvidersInput } from './filter-for-list-credential-providers-input';
 /**
 * 
 *
 * @export
 * @interface ListCredentialProvidersRequest
 */
export interface ListCredentialProvidersRequest {

    /**
     * @type {FilterForListCredentialProvidersInput}
     * @memberof ListCredentialProvidersRequest
     */
    Filter?: FilterForListCredentialProvidersInput;

    /**
     * @type {number}
     * @memberof ListCredentialProvidersRequest
     */
    PageNumber: number;

    /**
     * @type {number}
     * @memberof ListCredentialProvidersRequest
     */
    PageSize: number;

    /**
     * @type {string}
     * @memberof ListCredentialProvidersRequest
     */
    PoolName?: string;

    /**
     * @type {boolean}
     * @memberof ListCredentialProvidersRequest
     */
    SortDesc?: boolean;

    /**
     * @type {string}
     * @memberof ListCredentialProvidersRequest
     */
    SortField?: string;
}
