/* tslint:disable */
/* eslint-disable */
/**
 * id
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ProviderOptionsForUpdateIdentityProviderOAuthOutput
 */
export interface ProviderOptionsForUpdateIdentityProviderOAuthOutput {

    /**
     * @type {string}
     * @memberof ProviderOptionsForUpdateIdentityProviderOAuthOutput
     */
    AutoLinking?: string;

    /**
     * @type {boolean}
     * @memberof ProviderOptionsForUpdateIdentityProviderOAuthOutput
     */
    IsAutoCreation?: boolean;

    /**
     * @type {boolean}
     * @memberof ProviderOptionsForUpdateIdentityProviderOAuthOutput
     */
    IsAutoUpdate?: boolean;

    /**
     * @type {boolean}
     * @memberof ProviderOptionsForUpdateIdentityProviderOAuthOutput
     */
    IsCreationAllowed?: boolean;

    /**
     * @type {boolean}
     * @memberof ProviderOptionsForUpdateIdentityProviderOAuthOutput
     */
    IsLinkingAllowed?: boolean;
}
