/* tslint:disable */
/* eslint-disable */
/**
 * id
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface UpdateUserRequest
 */
export interface UpdateUserRequest {

    /**
     * @type {string}
     * @memberof UpdateUserRequest
     */
    Birthdate?: string;

    /**
     * @type {string}
     * @memberof UpdateUserRequest
     */
    Email?: string;

    /**
     * @type {boolean}
     * @memberof UpdateUserRequest
     */
    EmailVerified?: boolean;

    /**
     * @type {string}
     * @memberof UpdateUserRequest
     */
    FamilyName?: string;

    /**
     * @type {string}
     * @memberof UpdateUserRequest
     */
    Gender?: string;

    /**
     * @type {string}
     * @memberof UpdateUserRequest
     */
    GivenName?: string;

    /**
     * @type {string}
     * @memberof UpdateUserRequest
     */
    Locale?: string;

    /**
     * @type {string}
     * @memberof UpdateUserRequest
     */
    MiddleName?: string;

    /**
     * @type {string}
     * @memberof UpdateUserRequest
     */
    Name?: string;

    /**
     * @type {string}
     * @memberof UpdateUserRequest
     */
    Nickname?: string;

    /**
     * @type {string}
     * @memberof UpdateUserRequest
     */
    Password?: string;

    /**
     * @type {string}
     * @memberof UpdateUserRequest
     */
    PhoneNumber?: string;

    /**
     * @type {boolean}
     * @memberof UpdateUserRequest
     */
    PhoneNumberVerified?: boolean;

    /**
     * @type {string}
     * @memberof UpdateUserRequest
     */
    Picture?: string;

    /**
     * @type {string}
     * @memberof UpdateUserRequest
     */
    PreferredUsername?: string;

    /**
     * @type {string}
     * @memberof UpdateUserRequest
     */
    Profile?: string;

    /**
     * @type {string}
     * @memberof UpdateUserRequest
     */
    UserMetadata?: string;

    /**
     * @type {string}
     * @memberof UpdateUserRequest
     */
    UserPoolUid: string;

    /**
     * @type {string}
     * @memberof UpdateUserRequest
     */
    UserState?: string;

    /**
     * @type {string}
     * @memberof UpdateUserRequest
     */
    UserUid: string;

    /**
     * @type {string}
     * @memberof UpdateUserRequest
     */
    Website?: string;

    /**
     * @type {string}
     * @memberof UpdateUserRequest
     */
    Zoneinfo?: string;
}
