/* tslint:disable */
/* eslint-disable */
/**
 * id
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ClaimsPropagationConfigForUpdateIdentityProviderOAuthInput } from './claims-propagation-config-for-update-identity-provider-oauth-input';
import { ProviderOptionsForUpdateIdentityProviderOAuthInput } from './provider-options-for-update-identity-provider-oauth-input';
 /**
 * 
 *
 * @export
 * @interface UpdateIdentityProviderOAuthRequest
 */
export interface UpdateIdentityProviderOAuthRequest {

    /**
     * @type {string}
     * @memberof UpdateIdentityProviderOAuthRequest
     */
    AuthorizationEndpoint?: string;

    /**
     * @type {ClaimsPropagationConfigForUpdateIdentityProviderOAuthInput}
     * @memberof UpdateIdentityProviderOAuthRequest
     */
    ClaimsPropagationConfig?: ClaimsPropagationConfigForUpdateIdentityProviderOAuthInput;

    /**
     * @type {string}
     * @memberof UpdateIdentityProviderOAuthRequest
     */
    ClientId: string;

    /**
     * @type {string}
     * @memberof UpdateIdentityProviderOAuthRequest
     */
    ClientSecret?: string;

    /**
     * @type {string}
     * @memberof UpdateIdentityProviderOAuthRequest
     */
    ConnectionUid: string;

    /**
     * @type {boolean}
     * @memberof UpdateIdentityProviderOAuthRequest
     */
    Enabled?: boolean;

    /**
     * @type {string}
     * @memberof UpdateIdentityProviderOAuthRequest
     */
    IdAttribute: string;

    /**
     * @type {string}
     * @memberof UpdateIdentityProviderOAuthRequest
     */
    Name?: string;

    /**
     * @type {ProviderOptionsForUpdateIdentityProviderOAuthInput}
     * @memberof UpdateIdentityProviderOAuthRequest
     */
    ProviderOptions?: ProviderOptionsForUpdateIdentityProviderOAuthInput;

    /**
     * @type {Array<string>}
     * @memberof UpdateIdentityProviderOAuthRequest
     */
    ScopesList?: Array<string>;

    /**
     * @type {string}
     * @memberof UpdateIdentityProviderOAuthRequest
     */
    TokenEndpoint?: string;

    /**
     * @type {boolean}
     * @memberof UpdateIdentityProviderOAuthRequest
     */
    UsePkce: boolean;

    /**
     * @type {string}
     * @memberof UpdateIdentityProviderOAuthRequest
     */
    UserEndpoint?: string;

    /**
     * @type {string}
     * @memberof UpdateIdentityProviderOAuthRequest
     */
    UserPoolUid: string;
}
