/* tslint:disable */
/* eslint-disable */
/**
 * waf
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { IpFailedForAddProhibitionBlackOutput } from './ip-failed-for-add-prohibition-black-output';
 /**
 * 
 *
 * @export
 * @interface AddProhibitionBlackResponse
 */
export interface AddProhibitionBlackResponse {

    /**
     * @type {Array<IpFailedForAddProhibitionBlackOutput>}
     * @memberof AddProhibitionBlackResponse
     */
    IpFailed?: Array<IpFailedForAddProhibitionBlackOutput>;

    /**
     * @type {Array<string>}
     * @memberof AddProhibitionBlackResponse
     */
    IpSuccess?: Array<string>;
}
