/* tslint:disable */
/* eslint-disable */
/**
 * waf
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface DeleteCustomPageRequest
 */
export interface DeleteCustomPageRequest {

    /**
     * @type {string}
     * @memberof DeleteCustomPageRequest
     */
    Host: string;

    /**
     * @type {number}
     * @memberof DeleteCustomPageRequest
     */
    Id: number;

    /**
     * @type {string}
     * @memberof DeleteCustomPageRequest
     */
    ProjectName?: string;
}
