/* tslint:disable */
/* eslint-disable */
/**
 * waf
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { IpFailedForDeleteProhibitionBlackOutput } from './ip-failed-for-delete-prohibition-black-output';
 /**
 * 
 *
 * @export
 * @interface DeleteProhibitionBlackResponse
 */
export interface DeleteProhibitionBlackResponse {

    /**
     * @type {Array<IpFailedForDeleteProhibitionBlackOutput>}
     * @memberof DeleteProhibitionBlackResponse
     */
    IpFailed?: Array<IpFailedForDeleteProhibitionBlackOutput>;

    /**
     * @type {Array<string>}
     * @memberof DeleteProhibitionBlackResponse
     */
    IpSuccess?: Array<string>;
}
