/* tslint:disable */
/* eslint-disable */
/**
 * waf
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface GetReqQPSAnalysisResponse
 */
export interface GetReqQPSAnalysisResponse {

    /**
     * @type {number}
     * @memberof GetReqQPSAnalysisResponse
     */
    AverageQPS?: number;

    /**
     * @type {number}
     * @memberof GetReqQPSAnalysisResponse
     */
    PeakQPS?: number;
}
