/* tslint:disable */
/* eslint-disable */
/**
 * waf
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AccurateGroupForListAclRuleOutput } from './accurate-group-for-list-acl-rule-output';
import { HostGroupForListAclRuleOutput } from './host-group-for-list-acl-rule-output';
import { IpGroupForListAclRuleOutput } from './ip-group-for-list-acl-rule-output';
 /**
 * 
 *
 * @export
 * @interface RuleForListAclRuleOutput
 */
export interface RuleForListAclRuleOutput {

    /**
     * @type {AccurateGroupForListAclRuleOutput}
     * @memberof RuleForListAclRuleOutput
     */
    AccurateGroup?: AccurateGroupForListAclRuleOutput;

    /**
     * @type {string}
     * @memberof RuleForListAclRuleOutput
     */
    Action?: string;

    /**
     * @type {number}
     * @memberof RuleForListAclRuleOutput
     */
    Advanced?: number;

    /**
     * @type {string}
     * @memberof RuleForListAclRuleOutput
     */
    ClientIp?: string;

    /**
     * @type {string}
     * @memberof RuleForListAclRuleOutput
     */
    Description?: string;

    /**
     * @type {number}
     * @memberof RuleForListAclRuleOutput
     */
    Enable?: number;

    /**
     * @type {number}
     * @memberof RuleForListAclRuleOutput
     */
    HostAddType?: number;

    /**
     * @type {Array<number>}
     * @memberof RuleForListAclRuleOutput
     */
    HostGroupId?: Array<number>;

    /**
     * @type {Array<HostGroupForListAclRuleOutput>}
     * @memberof RuleForListAclRuleOutput
     */
    HostGroups?: Array<HostGroupForListAclRuleOutput>;

    /**
     * @type {Array<string>}
     * @memberof RuleForListAclRuleOutput
     */
    HostList?: Array<string>;

    /**
     * @type {number}
     * @memberof RuleForListAclRuleOutput
     */
    ID?: number;

    /**
     * @type {number}
     * @memberof RuleForListAclRuleOutput
     */
    IpAddType?: number;

    /**
     * @type {Array<number>}
     * @memberof RuleForListAclRuleOutput
     */
    IpGroupId?: Array<number>;

    /**
     * @type {Array<IpGroupForListAclRuleOutput>}
     * @memberof RuleForListAclRuleOutput
     */
    IpGroups?: Array<IpGroupForListAclRuleOutput>;

    /**
     * @type {Array<string>}
     * @memberof RuleForListAclRuleOutput
     */
    IpList?: Array<string>;

    /**
     * @type {Array<string>}
     * @memberof RuleForListAclRuleOutput
     */
    IpLocationCountry?: Array<string>;

    /**
     * @type {Array<string>}
     * @memberof RuleForListAclRuleOutput
     */
    IpLocationSubregion?: Array<string>;

    /**
     * @type {string}
     * @memberof RuleForListAclRuleOutput
     */
    Name?: string;

    /**
     * @type {string}
     * @memberof RuleForListAclRuleOutput
     */
    RuleTag?: string;

    /**
     * @type {string}
     * @memberof RuleForListAclRuleOutput
     */
    UpdateTime?: string;

    /**
     * @type {string}
     * @memberof RuleForListAclRuleOutput
     */
    Url?: string;
}
