/* tslint:disable */
/* eslint-disable */
/**
 * fwcenter
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface AddAclBackupRequest
 */
export interface AddAclBackupRequest {

    /**
     * @type {string}
     * @memberof AddAclBackupRequest
     */
    AclBackupName: string;

    /**
     * @type {string}
     * @memberof AddAclBackupRequest
     */
    CloudFirewallId?: string;
}
