/* tslint:disable */
/* eslint-disable */
/**
 * fwcenter
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface CreateNatFirewallResponse
 */
export interface CreateNatFirewallResponse {

    /**
     * @type {string}
     * @memberof CreateNatFirewallResponse
     */
    AccountId?: string;

    /**
     * @type {string}
     * @memberof CreateNatFirewallResponse
     */
    NatFirewallId?: string;
}
