/* tslint:disable */
/* eslint-disable */
/**
 * fwcenter
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { DataForDescribeNatFirewallListOutput } from './data-for-describe-nat-firewall-list-output';
 /**
 * 
 *
 * @export
 * @interface DescribeNatFirewallListResponse
 */
export interface DescribeNatFirewallListResponse {

    /**
     * @type {number}
     * @memberof DescribeNatFirewallListResponse
     */
    Count?: number;

    /**
     * @type {Array<DataForDescribeNatFirewallListOutput>}
     * @memberof DescribeNatFirewallListResponse
     */
    Data?: Array<DataForDescribeNatFirewallListOutput>;

    /**
     * @type {number}
     * @memberof DescribeNatFirewallListResponse
     */
    PageNumber?: number;

    /**
     * @type {number}
     * @memberof DescribeNatFirewallListResponse
     */
    PageSize?: number;

    /**
     * @type {number}
     * @memberof DescribeNatFirewallListResponse
     */
    TotalCount?: number;
}
