/* tslint:disable */
/* eslint-disable */
/**
 * vmp
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface CrossWorkspaceForUpdateAggregateWorkspaceInput
 */
export interface CrossWorkspaceForUpdateAggregateWorkspaceInput {

    /**
     * @type {number}
     * @memberof CrossWorkspaceForUpdateAggregateWorkspaceInput
     */
    AccountId?: number;

    /**
     * @type {string}
     * @memberof CrossWorkspaceForUpdateAggregateWorkspaceInput
     */
    Id?: string;

    /**
     * @type {string}
     * @memberof CrossWorkspaceForUpdateAggregateWorkspaceInput
     */
    Region?: string;
}
