/* tslint:disable */
/* eslint-disable */
/**
 * vmp
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface DeleteRuleFileRequest
 */
export interface DeleteRuleFileRequest {

    /**
     * @type {string}
     * @memberof DeleteRuleFileRequest
     */
    Id?: string;

    /**
     * @type {string}
     * @memberof DeleteRuleFileRequest
     */
    Name?: string;

    /**
     * @type {string}
     * @memberof DeleteRuleFileRequest
     */
    WorkspaceId?: string;
}
