/* tslint:disable */
/* eslint-disable */
/**
 * vmp
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface FilterForListNotifyTemplatesInput
 */
export interface FilterForListNotifyTemplatesInput {

    /**
     * @type {string}
     * @memberof FilterForListNotifyTemplatesInput
     */
    Channel?: string;

    /**
     * @type {Array<string>}
     * @memberof FilterForListNotifyTemplatesInput
     */
    Ids?: Array<string>;

    /**
     * @type {string}
     * @memberof FilterForListNotifyTemplatesInput
     */
    Name?: string;
}
