/* tslint:disable */
/* eslint-disable */
/**
 * vmp
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { LevelForListNotifyGroupPoliciesOutput } from './level-for-list-notify-group-policies-output';
 /**
 * 
 *
 * @export
 * @interface ItemForListNotifyGroupPoliciesOutput
 */
export interface ItemForListNotifyGroupPoliciesOutput {

    /**
     * @type {string}
     * @memberof ItemForListNotifyGroupPoliciesOutput
     */
    CreateTime?: string;

    /**
     * @type {string}
     * @memberof ItemForListNotifyGroupPoliciesOutput
     */
    Description?: string;

    /**
     * @type {string}
     * @memberof ItemForListNotifyGroupPoliciesOutput
     */
    Id?: string;

    /**
     * @type {Array<LevelForListNotifyGroupPoliciesOutput>}
     * @memberof ItemForListNotifyGroupPoliciesOutput
     */
    Levels?: Array<LevelForListNotifyGroupPoliciesOutput>;

    /**
     * @type {string}
     * @memberof ItemForListNotifyGroupPoliciesOutput
     */
    Name?: string;
}
