/* tslint:disable */
/* eslint-disable */
/**
 * vmp
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ItemForListWorkspaceInstanceTypesOutput } from './item-for-list-workspace-instance-types-output';
 /**
 * 
 *
 * @export
 * @interface ListWorkspaceInstanceTypesResponse
 */
export interface ListWorkspaceInstanceTypesResponse {

    /**
     * @type {Array<ItemForListWorkspaceInstanceTypesOutput>}
     * @memberof ListWorkspaceInstanceTypesResponse
     */
    Items?: Array<ItemForListWorkspaceInstanceTypesOutput>;

    /**
     * @type {number}
     * @memberof ListWorkspaceInstanceTypesResponse
     */
    Total?: number;
}
