/* tslint:disable */
/* eslint-disable */
/**
 * vmp
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { FilterForListContactGroupsInput } from './filter-for-list-contact-groups-input';
 /**
 * 
 *
 * @export
 * @interface ListContactGroupsRequest
 */
export interface ListContactGroupsRequest {

    /**
     * @type {FilterForListContactGroupsInput}
     * @memberof ListContactGroupsRequest
     */
    Filter?: FilterForListContactGroupsInput;

    /**
     * @type {number}
     * @memberof ListContactGroupsRequest
     */
    PageNumber?: number;

    /**
     * @type {number}
     * @memberof ListContactGroupsRequest
     */
    PageSize?: number;

    /**
     * @type {string}
     * @memberof ListContactGroupsRequest
     */
    SortBy?: string;

    /**
     * @type {string}
     * @memberof ListContactGroupsRequest
     */
    SortOrder?: string;
}
