/* tslint:disable */
/* eslint-disable */
/**
 * vmp
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ItemForListNotifyTemplatesOutput } from './item-for-list-notify-templates-output';
 /**
 * 
 *
 * @export
 * @interface ListNotifyTemplatesResponse
 */
export interface ListNotifyTemplatesResponse {

    /**
     * @type {Array<ItemForListNotifyTemplatesOutput>}
     * @memberof ListNotifyTemplatesResponse
     */
    Items?: Array<ItemForListNotifyTemplatesOutput>;

    /**
     * @type {number}
     * @memberof ListNotifyTemplatesResponse
     */
    Total?: number;
}
