/* tslint:disable */
/* eslint-disable */
/**
 * vmp
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { FilterForListNotifyTemplatesInput } from './filter-for-list-notify-templates-input';
 /**
 * 
 *
 * @export
 * @interface ListNotifyTemplatesRequest
 */
export interface ListNotifyTemplatesRequest {

    /**
     * @type {FilterForListNotifyTemplatesInput}
     * @memberof ListNotifyTemplatesRequest
     */
    Filter?: FilterForListNotifyTemplatesInput;

    /**
     * @type {number}
     * @memberof ListNotifyTemplatesRequest
     */
    PageNumber?: number;

    /**
     * @type {number}
     * @memberof ListNotifyTemplatesRequest
     */
    PageSize?: number;

    /**
     * @type {string}
     * @memberof ListNotifyTemplatesRequest
     */
    SortBy?: string;

    /**
     * @type {string}
     * @memberof ListNotifyTemplatesRequest
     */
    SortOrder?: string;
}
