/* tslint:disable */
/* eslint-disable */
/**
 * vmp
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AnnotationForUpdateAlertingRuleInput } from './annotation-for-update-alerting-rule-input';
import { LabelForUpdateAlertingRuleInput } from './label-for-update-alerting-rule-input';
import { LevelForUpdateAlertingRuleInput } from './level-for-update-alerting-rule-input';
import { QueryForUpdateAlertingRuleInput } from './query-for-update-alerting-rule-input';
 /**
 * 
 *
 * @export
 * @interface UpdateAlertingRuleRequest
 */
export interface UpdateAlertingRuleRequest {

    /**
     * @type {Array<AnnotationForUpdateAlertingRuleInput>}
     * @memberof UpdateAlertingRuleRequest
     */
    Annotations?: Array<AnnotationForUpdateAlertingRuleInput>;

    /**
     * @type {string}
     * @memberof UpdateAlertingRuleRequest
     */
    Description?: string;

    /**
     * @type {string}
     * @memberof UpdateAlertingRuleRequest
     */
    Id: string;

    /**
     * @type {Array<LabelForUpdateAlertingRuleInput>}
     * @memberof UpdateAlertingRuleRequest
     */
    Labels?: Array<LabelForUpdateAlertingRuleInput>;

    /**
     * @type {Array<LevelForUpdateAlertingRuleInput>}
     * @memberof UpdateAlertingRuleRequest
     */
    Levels?: Array<LevelForUpdateAlertingRuleInput>;

    /**
     * @type {string}
     * @memberof UpdateAlertingRuleRequest
     */
    Name?: string;

    /**
     * @type {string}
     * @memberof UpdateAlertingRuleRequest
     */
    NotifyGroupPolicyId?: string;

    /**
     * @type {string}
     * @memberof UpdateAlertingRuleRequest
     */
    NotifyPolicyId?: string;

    /**
     * @type {QueryForUpdateAlertingRuleInput}
     * @memberof UpdateAlertingRuleRequest
     */
    _Query?: QueryForUpdateAlertingRuleInput;

    /**
     * @type {string}
     * @memberof UpdateAlertingRuleRequest
     */
    Type?: string;
}
