/* tslint:disable */
/* eslint-disable */
/**
 * dns
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface QueryZoneResponse
 */
export interface QueryZoneResponse {

    /**
     * @type {Array<string>}
     * @memberof QueryZoneResponse
     */
    AllocateDNSServerList?: Array<string>;

    /**
     * @type {boolean}
     * @memberof QueryZoneResponse
     */
    AutoRenew?: boolean;

    /**
     * @type {string}
     * @memberof QueryZoneResponse
     */
    ConfigurationCode?: string;

    /**
     * @type {string}
     * @memberof QueryZoneResponse
     */
    DnsSecurity?: string;

    /**
     * @type {number}
     * @memberof QueryZoneResponse
     */
    ExpiredTime?: number;

    /**
     * @type {string}
     * @memberof QueryZoneResponse
     */
    InstanceNo?: string;

    /**
     * @type {boolean}
     * @memberof QueryZoneResponse
     */
    IsNSCorrect?: boolean;

    /**
     * @type {boolean}
     * @memberof QueryZoneResponse
     */
    IsSubDomain?: boolean;

    /**
     * @type {Array<string>}
     * @memberof QueryZoneResponse
     */
    RealDNSServerList?: Array<string>;

    /**
     * @type {number}
     * @memberof QueryZoneResponse
     */
    RecordCount?: number;

    /**
     * @type {string}
     * @memberof QueryZoneResponse
     */
    Remark?: string;

    /**
     * @type {number}
     * @memberof QueryZoneResponse
     */
    Stage?: number;

    /**
     * @type {number}
     * @memberof QueryZoneResponse
     */
    Status?: number;

    /**
     * @type {string}
     * @memberof QueryZoneResponse
     */
    SubDomainHost?: string;

    /**
     * @type {string}
     * @memberof QueryZoneResponse
     */
    TradeCode?: string;

    /**
     * @type {string}
     * @memberof QueryZoneResponse
     */
    UpdatedAt?: string;

    /**
     * @type {string}
     * @memberof QueryZoneResponse
     */
    ZoneName?: string;
}
