/* tslint:disable */
/* eslint-disable */
/**
 * vpn
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { VpnGatewayRouteForDescribeVpnGatewayRoutesOutput } from './vpn-gateway-route-for-describe-vpn-gateway-routes-output';
 /**
 * 
 *
 * @export
 * @interface DescribeVpnGatewayRoutesResponse
 */
export interface DescribeVpnGatewayRoutesResponse {

    /**
     * @type {number}
     * @memberof DescribeVpnGatewayRoutesResponse
     */
    PageNumber?: number;

    /**
     * @type {number}
     * @memberof DescribeVpnGatewayRoutesResponse
     */
    PageSize?: number;

    /**
     * @type {string}
     * @memberof DescribeVpnGatewayRoutesResponse
     */
    RequestId?: string;

    /**
     * @type {number}
     * @memberof DescribeVpnGatewayRoutesResponse
     */
    TotalCount?: number;

    /**
     * @type {Array<VpnGatewayRouteForDescribeVpnGatewayRoutesOutput>}
     * @memberof DescribeVpnGatewayRoutesResponse
     */
    VpnGatewayRoutes?: Array<VpnGatewayRouteForDescribeVpnGatewayRoutesOutput>;
}
