/* tslint:disable */
/* eslint-disable */
/**
 * vpn
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { BgpInfoForDescribeVpnConnectionAttributesOutput } from './bgp-info-for-describe-vpn-connection-attributes-output';
import { HealthCheckerForDescribeVpnConnectionAttributesOutput } from './health-checker-for-describe-vpn-connection-attributes-output';
import { IkeConfigForDescribeVpnConnectionAttributesOutput } from './ike-config-for-describe-vpn-connection-attributes-output';
import { IpsecConfigForDescribeVpnConnectionAttributesOutput } from './ipsec-config-for-describe-vpn-connection-attributes-output';
import { TagForDescribeVpnConnectionAttributesOutput } from './tag-for-describe-vpn-connection-attributes-output';
import { TunnelOptionForDescribeVpnConnectionAttributesOutput } from './tunnel-option-for-describe-vpn-connection-attributes-output';
 /**
 * 
 *
 * @export
 * @interface DescribeVpnConnectionAttributesResponse
 */
export interface DescribeVpnConnectionAttributesResponse {

    /**
     * @type {string}
     * @memberof DescribeVpnConnectionAttributesResponse
     */
    AccountId?: string;

    /**
     * @type {string}
     * @memberof DescribeVpnConnectionAttributesResponse
     */
    AttachStatus?: string;

    /**
     * @type {string}
     * @memberof DescribeVpnConnectionAttributesResponse
     */
    AttachType?: string;

    /**
     * @type {BgpInfoForDescribeVpnConnectionAttributesOutput}
     * @memberof DescribeVpnConnectionAttributesResponse
     */
    BgpInfo?: BgpInfoForDescribeVpnConnectionAttributesOutput;

    /**
     * @type {string}
     * @memberof DescribeVpnConnectionAttributesResponse
     */
    BusinessStatus?: string;

    /**
     * @type {string}
     * @memberof DescribeVpnConnectionAttributesResponse
     */
    ConnectStatus?: string;

    /**
     * @type {string}
     * @memberof DescribeVpnConnectionAttributesResponse
     */
    CreationTime?: string;

    /**
     * @type {string}
     * @memberof DescribeVpnConnectionAttributesResponse
     */
    CustomerGatewayId?: string;

    /**
     * @type {string}
     * @memberof DescribeVpnConnectionAttributesResponse
     */
    DeletedTime?: string;

    /**
     * @type {string}
     * @memberof DescribeVpnConnectionAttributesResponse
     */
    Description?: string;

    /**
     * @type {string}
     * @memberof DescribeVpnConnectionAttributesResponse
     */
    DpdAction?: string;

    /**
     * @type {boolean}
     * @memberof DescribeVpnConnectionAttributesResponse
     */
    DualTunnelEnabled?: boolean;

    /**
     * @type {boolean}
     * @memberof DescribeVpnConnectionAttributesResponse
     */
    EnableTunnelsBgp?: boolean;

    /**
     * @type {Array<HealthCheckerForDescribeVpnConnectionAttributesOutput>}
     * @memberof DescribeVpnConnectionAttributesResponse
     */
    HealthCheckers?: Array<HealthCheckerForDescribeVpnConnectionAttributesOutput>;

    /**
     * @type {IkeConfigForDescribeVpnConnectionAttributesOutput}
     * @memberof DescribeVpnConnectionAttributesResponse
     */
    IkeConfig?: IkeConfigForDescribeVpnConnectionAttributesOutput;

    /**
     * @type {string}
     * @memberof DescribeVpnConnectionAttributesResponse
     */
    IpAddress?: string;

    /**
     * @type {IpsecConfigForDescribeVpnConnectionAttributesOutput}
     * @memberof DescribeVpnConnectionAttributesResponse
     */
    IpsecConfig?: IpsecConfigForDescribeVpnConnectionAttributesOutput;

    /**
     * @type {boolean}
     * @memberof DescribeVpnConnectionAttributesResponse
     */
    IsBlocked?: boolean;

    /**
     * @type {Array<string>}
     * @memberof DescribeVpnConnectionAttributesResponse
     */
    LocalSubnet?: Array<string>;

    /**
     * @type {boolean}
     * @memberof DescribeVpnConnectionAttributesResponse
     */
    LogEnabled?: boolean;

    /**
     * @type {boolean}
     * @memberof DescribeVpnConnectionAttributesResponse
     */
    NatTraversal?: boolean;

    /**
     * @type {boolean}
     * @memberof DescribeVpnConnectionAttributesResponse
     */
    NegotiateInstantly?: boolean;

    /**
     * @type {string}
     * @memberof DescribeVpnConnectionAttributesResponse
     */
    OverdueTime?: string;

    /**
     * @type {string}
     * @memberof DescribeVpnConnectionAttributesResponse
     */
    ProjectName?: string;

    /**
     * @type {Array<string>}
     * @memberof DescribeVpnConnectionAttributesResponse
     */
    RemoteSubnet?: Array<string>;

    /**
     * @type {string}
     * @memberof DescribeVpnConnectionAttributesResponse
     */
    RequestId?: string;

    /**
     * @type {string}
     * @memberof DescribeVpnConnectionAttributesResponse
     */
    Spec?: string;

    /**
     * @type {string}
     * @memberof DescribeVpnConnectionAttributesResponse
     */
    Status?: string;

    /**
     * @type {Array<TagForDescribeVpnConnectionAttributesOutput>}
     * @memberof DescribeVpnConnectionAttributesResponse
     */
    Tags?: Array<TagForDescribeVpnConnectionAttributesOutput>;

    /**
     * @type {string}
     * @memberof DescribeVpnConnectionAttributesResponse
     */
    TransitRouterId?: string;

    /**
     * @type {Array<TunnelOptionForDescribeVpnConnectionAttributesOutput>}
     * @memberof DescribeVpnConnectionAttributesResponse
     */
    TunnelOptions?: Array<TunnelOptionForDescribeVpnConnectionAttributesOutput>;

    /**
     * @type {string}
     * @memberof DescribeVpnConnectionAttributesResponse
     */
    UpdateTime?: string;

    /**
     * @type {string}
     * @memberof DescribeVpnConnectionAttributesResponse
     */
    VpnConnectionId?: string;

    /**
     * @type {string}
     * @memberof DescribeVpnConnectionAttributesResponse
     */
    VpnConnectionName?: string;

    /**
     * @type {string}
     * @memberof DescribeVpnConnectionAttributesResponse
     */
    VpnGatewayId?: string;

    /**
     * @type {string}
     * @memberof DescribeVpnConnectionAttributesResponse
     */
    ZoneId?: string;
}
