/* tslint:disable */
/* eslint-disable */
/**
 * vpn
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface IkeConfigForModifyVpnConnectionAttributesInput
 */
export interface IkeConfigForModifyVpnConnectionAttributesInput {

    /**
     * @type {string}
     * @memberof IkeConfigForModifyVpnConnectionAttributesInput
     */
    AuthAlg?: IkeConfigForModifyVpnConnectionAttributesInputAuthAlgEnum;

    /**
     * @type {string}
     * @memberof IkeConfigForModifyVpnConnectionAttributesInput
     */
    DhGroup?: IkeConfigForModifyVpnConnectionAttributesInputDhGroupEnum;

    /**
     * @type {string}
     * @memberof IkeConfigForModifyVpnConnectionAttributesInput
     */
    EncAlg?: IkeConfigForModifyVpnConnectionAttributesInputEncAlgEnum;

    /**
     * @type {number}
     * @memberof IkeConfigForModifyVpnConnectionAttributesInput
     */
    Lifetime?: number;

    /**
     * @type {string}
     * @memberof IkeConfigForModifyVpnConnectionAttributesInput
     */
    LocalId?: string;

    /**
     * @type {string}
     * @memberof IkeConfigForModifyVpnConnectionAttributesInput
     */
    Mode?: IkeConfigForModifyVpnConnectionAttributesInputModeEnum;

    /**
     * @type {string}
     * @memberof IkeConfigForModifyVpnConnectionAttributesInput
     */
    Psk?: string;

    /**
     * @type {string}
     * @memberof IkeConfigForModifyVpnConnectionAttributesInput
     */
    RemoteId?: string;

    /**
     * @type {string}
     * @memberof IkeConfigForModifyVpnConnectionAttributesInput
     */
    Version?: IkeConfigForModifyVpnConnectionAttributesInputVersionEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum IkeConfigForModifyVpnConnectionAttributesInputAuthAlgEnum {
    Sha1 = 'sha1',
    Md5 = 'md5',
    Sha256 = 'sha256',
    Sha384 = 'sha384',
    Sha512 = 'sha512',
    Sm3 = 'sm3'
}
/**
 * @export
 * @enum {string}
 */
export enum IkeConfigForModifyVpnConnectionAttributesInputDhGroupEnum {
    Group1 = 'group1',
    Group2 = 'group2',
    Group5 = 'group5',
    Group14 = 'group14'
}
/**
 * @export
 * @enum {string}
 */
export enum IkeConfigForModifyVpnConnectionAttributesInputEncAlgEnum {
    Aes = 'aes',
    Aes192 = 'aes192',
    Aes256 = 'aes256',
    Des = 'des',
    _3des = '3des',
    Sm4 = 'sm4'
}
/**
 * @export
 * @enum {string}
 */
export enum IkeConfigForModifyVpnConnectionAttributesInputModeEnum {
    Main = 'main',
    Aggressive = 'aggressive'
}
/**
 * @export
 * @enum {string}
 */
export enum IkeConfigForModifyVpnConnectionAttributesInputVersionEnum {
    Ikev1 = 'ikev1',
    Ikev2 = 'ikev2'
}

