/* tslint:disable */
/* eslint-disable */
/**
 * apig
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { CustomBodyParamsForListUpstreamsOutput } from './custom-body-params-for-list-upstreams-output';
import { CustomHeaderParamsForListUpstreamsOutput } from './custom-header-params-for-list-upstreams-output';
import { CustomModelServiceForListUpstreamsOutput } from './custom-model-service-for-list-upstreams-output';
 /**
 * 
 *
 * @export
 * @interface AIProviderForListUpstreamsOutput
 */
export interface AIProviderForListUpstreamsOutput {

    /**
     * @type {string}
     * @memberof AIProviderForListUpstreamsOutput
     */
    BaseUrl?: string;

    /**
     * @type {CustomBodyParamsForListUpstreamsOutput}
     * @memberof AIProviderForListUpstreamsOutput
     */
    CustomBodyParams?: CustomBodyParamsForListUpstreamsOutput;

    /**
     * @type {CustomHeaderParamsForListUpstreamsOutput}
     * @memberof AIProviderForListUpstreamsOutput
     */
    CustomHeaderParams?: CustomHeaderParamsForListUpstreamsOutput;

    /**
     * @type {CustomModelServiceForListUpstreamsOutput}
     * @memberof AIProviderForListUpstreamsOutput
     */
    CustomModelService?: CustomModelServiceForListUpstreamsOutput;

    /**
     * @type {string}
     * @memberof AIProviderForListUpstreamsOutput
     */
    Name?: string;

    /**
     * @type {string}
     * @memberof AIProviderForListUpstreamsOutput
     */
    Token?: string;
}
