/* tslint:disable */
/* eslint-disable */
/**
 * apig
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { BasicForGetUpstreamSourceOutput } from './basic-for-get-upstream-source-output';
 /**
 * 
 *
 * @export
 * @interface AuthConfigForGetUpstreamSourceOutput
 */
export interface AuthConfigForGetUpstreamSourceOutput {

    /**
     * @type {BasicForGetUpstreamSourceOutput}
     * @memberof AuthConfigForGetUpstreamSourceOutput
     */
    Basic?: BasicForGetUpstreamSourceOutput;
}
