/* tslint:disable */
/* eslint-disable */
/**
 * apig
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface DeleteUpstreamVersionRequest
 */
export interface DeleteUpstreamVersionRequest {

    /**
     * @type {string}
     * @memberof DeleteUpstreamVersionRequest
     */
    UpstreamId: string;

    /**
     * @type {string}
     * @memberof DeleteUpstreamVersionRequest
     */
    UpstreamVersionName: string;
}
