/* tslint:disable */
/* eslint-disable */
/**
 * apig
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface FilterForListUpstreamsInput
 */
export interface FilterForListUpstreamsInput {

    /**
     * @type {Array<string>}
     * @memberof FilterForListUpstreamsInput
     */
    Ids?: Array<string>;

    /**
     * @type {string}
     * @memberof FilterForListUpstreamsInput
     */
    Name?: string;
}
