/* tslint:disable */
/* eslint-disable */
/**
 * apig
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { UpstreamSourceForGetUpstreamSourceOutput } from './upstream-source-for-get-upstream-source-output';
 /**
 * 
 *
 * @export
 * @interface GetUpstreamSourceResponse
 */
export interface GetUpstreamSourceResponse {

    /**
     * @type {UpstreamSourceForGetUpstreamSourceOutput}
     * @memberof GetUpstreamSourceResponse
     */
    UpstreamSource?: UpstreamSourceForGetUpstreamSourceOutput;
}
