/* tslint:disable */
/* eslint-disable */
/**
 * apig
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ServiceNetworkSpecForCreateGatewayServiceInput
 */
export interface ServiceNetworkSpecForCreateGatewayServiceInput {

    /**
     * @type {boolean}
     * @memberof ServiceNetworkSpecForCreateGatewayServiceInput
     */
    EnablePrivateNetwork?: boolean;

    /**
     * @type {boolean}
     * @memberof ServiceNetworkSpecForCreateGatewayServiceInput
     */
    EnablePublicNetwork?: boolean;

    /**
     * @type {Array<string>}
     * @memberof ServiceNetworkSpecForCreateGatewayServiceInput
     */
    PrivateNetworkIP?: Array<string>;
}
