/* tslint:disable */
/* eslint-disable */
/**
 * transitrouter
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface CreateTransitRouterRoutePolicyTableRequest
 */
export interface CreateTransitRouterRoutePolicyTableRequest {

    /**
     * @type {string}
     * @memberof CreateTransitRouterRoutePolicyTableRequest
     */
    ClientToken?: string;

    /**
     * @type {string}
     * @memberof CreateTransitRouterRoutePolicyTableRequest
     */
    Description?: string;

    /**
     * @type {string}
     * @memberof CreateTransitRouterRoutePolicyTableRequest
     */
    Direction: string;

    /**
     * @type {string}
     * @memberof CreateTransitRouterRoutePolicyTableRequest
     */
    TransitRouterId: string;

    /**
     * @type {string}
     * @memberof CreateTransitRouterRoutePolicyTableRequest
     */
    TransitRouterRoutePolicyTableName?: string;
}
