/* tslint:disable */
/* eslint-disable */
/**
 * transitrouter
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { TransitRouterForwardPolicyEntryForDescribeTransitRouterForwardPolicyEntriesOutput } from './transit-router-forward-policy-entry-for-describe-transit-router-forward-policy-entries-output';
 /**
 * 
 *
 * @export
 * @interface DescribeTransitRouterForwardPolicyEntriesResponse
 */
export interface DescribeTransitRouterForwardPolicyEntriesResponse {

    /**
     * @type {number}
     * @memberof DescribeTransitRouterForwardPolicyEntriesResponse
     */
    PageNumber?: number;

    /**
     * @type {number}
     * @memberof DescribeTransitRouterForwardPolicyEntriesResponse
     */
    PageSize?: number;

    /**
     * @type {number}
     * @memberof DescribeTransitRouterForwardPolicyEntriesResponse
     */
    TotalCount?: number;

    /**
     * @type {Array<TransitRouterForwardPolicyEntryForDescribeTransitRouterForwardPolicyEntriesOutput>}
     * @memberof DescribeTransitRouterForwardPolicyEntriesResponse
     */
    TransitRouterForwardPolicyEntries?: Array<TransitRouterForwardPolicyEntryForDescribeTransitRouterForwardPolicyEntriesOutput>;
}
