/* tslint:disable */
/* eslint-disable */
/**
 * transitrouter
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { TransitRouterAttachmentForDescribeTransitRouterLocalPeerAttachmentsOutput } from './transit-router-attachment-for-describe-transit-router-local-peer-attachments-output';
 /**
 * 
 *
 * @export
 * @interface DescribeTransitRouterLocalPeerAttachmentsResponse
 */
export interface DescribeTransitRouterLocalPeerAttachmentsResponse {

    /**
     * @type {number}
     * @memberof DescribeTransitRouterLocalPeerAttachmentsResponse
     */
    PageNumber?: number;

    /**
     * @type {number}
     * @memberof DescribeTransitRouterLocalPeerAttachmentsResponse
     */
    PageSize?: number;

    /**
     * @type {number}
     * @memberof DescribeTransitRouterLocalPeerAttachmentsResponse
     */
    TotalCount?: number;

    /**
     * @type {Array<TransitRouterAttachmentForDescribeTransitRouterLocalPeerAttachmentsOutput>}
     * @memberof DescribeTransitRouterLocalPeerAttachmentsResponse
     */
    TransitRouterAttachments?: Array<TransitRouterAttachmentForDescribeTransitRouterLocalPeerAttachmentsOutput>;
}
