/* tslint:disable */
/* eslint-disable */
/**
 * transitrouter
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { TransitRouterTrafficQosQueuePolicyForDescribeTransitRouterTrafficQosQueuePoliciesOutput } from './transit-router-traffic-qos-queue-policy-for-describe-transit-router-traffic-qos-queue-policies-output';
 /**
 * 
 *
 * @export
 * @interface DescribeTransitRouterTrafficQosQueuePoliciesResponse
 */
export interface DescribeTransitRouterTrafficQosQueuePoliciesResponse {

    /**
     * @type {number}
     * @memberof DescribeTransitRouterTrafficQosQueuePoliciesResponse
     */
    PageNumber?: number;

    /**
     * @type {number}
     * @memberof DescribeTransitRouterTrafficQosQueuePoliciesResponse
     */
    PageSize?: number;

    /**
     * @type {number}
     * @memberof DescribeTransitRouterTrafficQosQueuePoliciesResponse
     */
    TotalCount?: number;

    /**
     * @type {Array<TransitRouterTrafficQosQueuePolicyForDescribeTransitRouterTrafficQosQueuePoliciesOutput>}
     * @memberof DescribeTransitRouterTrafficQosQueuePoliciesResponse
     */
    TransitRouterTrafficQosQueuePolicies?: Array<TransitRouterTrafficQosQueuePolicyForDescribeTransitRouterTrafficQosQueuePoliciesOutput>;
}
