/* tslint:disable */
/* eslint-disable */
/**
 * transitrouter
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface TagFilterForDescribeTransitRouterFlowLogsInput
 */
export interface TagFilterForDescribeTransitRouterFlowLogsInput {

    /**
     * @type {string}
     * @memberof TagFilterForDescribeTransitRouterFlowLogsInput
     */
    Key?: string;

    /**
     * @type {Array<string>}
     * @memberof TagFilterForDescribeTransitRouterFlowLogsInput
     */
    Values?: Array<string>;
}
