/* tslint:disable */
/* eslint-disable */
/**
 * seccenter20240508
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface DataForListCleanHistoryOutput
 */
export interface DataForListCleanHistoryOutput {

    /**
     * @type {number}
     * @memberof DataForListCleanHistoryOutput
     */
    CleanTime?: number;

    /**
     * @type {string}
     * @memberof DataForListCleanHistoryOutput
     */
    CloudProvider?: string;

    /**
     * @type {string}
     * @memberof DataForListCleanHistoryOutput
     */
    GroupName?: string;

    /**
     * @type {string}
     * @memberof DataForListCleanHistoryOutput
     */
    HostId?: string;

    /**
     * @type {string}
     * @memberof DataForListCleanHistoryOutput
     */
    HostName?: string;

    /**
     * @type {number}
     * @memberof DataForListCleanHistoryOutput
     */
    OfflineTime?: number;

    /**
     * @type {string}
     * @memberof DataForListCleanHistoryOutput
     */
    Platform?: string;

    /**
     * @type {string}
     * @memberof DataForListCleanHistoryOutput
     */
    PrivateIP?: string;

    /**
     * @type {string}
     * @memberof DataForListCleanHistoryOutput
     */
    PublicIP?: string;

    /**
     * @type {string}
     * @memberof DataForListCleanHistoryOutput
     */
    Region?: string;

    /**
     * @type {Array<string>}
     * @memberof DataForListCleanHistoryOutput
     */
    Tags?: Array<string>;

    /**
     * @type {string}
     * @memberof DataForListCleanHistoryOutput
     */
    VpcId?: string;
}
