/* tslint:disable */
/* eslint-disable */
/**
 * seccenter20240508
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface GetVarmorTLSInfoResponse
 */
export interface GetVarmorTLSInfoResponse {

    /**
     * @type {string}
     * @memberof GetVarmorTLSInfoResponse
     */
    ProjectId?: string;

    /**
     * @type {number}
     * @memberof GetVarmorTLSInfoResponse
     */
    QuotaUsed?: number;

    /**
     * @type {number}
     * @memberof GetVarmorTLSInfoResponse
     */
    StorageDays?: number;

    /**
     * @type {string}
     * @memberof GetVarmorTLSInfoResponse
     */
    TopicId?: string;
}
