/* tslint:disable */
/* eslint-disable */
/**
 * directconnect
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface EngineerForApplyDirectConnectConnectionLoaInput
 */
export interface EngineerForApplyDirectConnectConnectionLoaInput {

    /**
     * @type {string}
     * @memberof EngineerForApplyDirectConnectConnectionLoaInput
     */
    CertificateNo: string;

    /**
     * @type {string}
     * @memberof EngineerForApplyDirectConnectConnectionLoaInput
     */
    CertificateType: string;

    /**
     * @type {string}
     * @memberof EngineerForApplyDirectConnectConnectionLoaInput
     */
    ContactPhone: string;

    /**
     * @type {string}
     * @memberof EngineerForApplyDirectConnectConnectionLoaInput
     */
    Name: string;
}
