/* tslint:disable */
/* eslint-disable */
/**
 * directconnect
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ModifyDirectConnectConnectionAttributesRequest
 */
export interface ModifyDirectConnectConnectionAttributesRequest {

    /**
     * @type {string}
     * @memberof ModifyDirectConnectConnectionAttributesRequest
     */
    CustomerContactEmail?: string;

    /**
     * @type {string}
     * @memberof ModifyDirectConnectConnectionAttributesRequest
     */
    CustomerContactPhone?: string;

    /**
     * @type {string}
     * @memberof ModifyDirectConnectConnectionAttributesRequest
     */
    CustomerName?: string;

    /**
     * @type {string}
     * @memberof ModifyDirectConnectConnectionAttributesRequest
     */
    Description?: string;

    /**
     * @type {string}
     * @memberof ModifyDirectConnectConnectionAttributesRequest
     */
    DirectConnectConnectionId: string;

    /**
     * @type {string}
     * @memberof ModifyDirectConnectConnectionAttributesRequest
     */
    DirectConnectConnectionName?: string;

    /**
     * @type {string}
     * @memberof ModifyDirectConnectConnectionAttributesRequest
     */
    ProjectName?: string;
}
