/* tslint:disable */
/* eslint-disable */
/**
 * directconnect
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { TagForDescribeDirectConnectVirtualInterfacesOutput } from './tag-for-describe-direct-connect-virtual-interfaces-output';
 /**
 * 
 *
 * @export
 * @interface VirtualInterfaceForDescribeDirectConnectVirtualInterfacesOutput
 */
export interface VirtualInterfaceForDescribeDirectConnectVirtualInterfacesOutput {

    /**
     * @type {string}
     * @memberof VirtualInterfaceForDescribeDirectConnectVirtualInterfacesOutput
     */
    AccountId?: string;

    /**
     * @type {number}
     * @memberof VirtualInterfaceForDescribeDirectConnectVirtualInterfacesOutput
     */
    Bandwidth?: number;

    /**
     * @type {number}
     * @memberof VirtualInterfaceForDescribeDirectConnectVirtualInterfacesOutput
     */
    BfdDetectInterval?: number;

    /**
     * @type {number}
     * @memberof VirtualInterfaceForDescribeDirectConnectVirtualInterfacesOutput
     */
    BfdDetectMultiplier?: number;

    /**
     * @type {string}
     * @memberof VirtualInterfaceForDescribeDirectConnectVirtualInterfacesOutput
     */
    CreationTime?: string;

    /**
     * @type {string}
     * @memberof VirtualInterfaceForDescribeDirectConnectVirtualInterfacesOutput
     */
    Description?: string;

    /**
     * @type {string}
     * @memberof VirtualInterfaceForDescribeDirectConnectVirtualInterfacesOutput
     */
    DirectConnectConnectionId?: string;

    /**
     * @type {string}
     * @memberof VirtualInterfaceForDescribeDirectConnectVirtualInterfacesOutput
     */
    DirectConnectGatewayId?: string;

    /**
     * @type {boolean}
     * @memberof VirtualInterfaceForDescribeDirectConnectVirtualInterfacesOutput
     */
    EnableBfd?: boolean;

    /**
     * @type {boolean}
     * @memberof VirtualInterfaceForDescribeDirectConnectVirtualInterfacesOutput
     */
    EnableNqa?: boolean;

    /**
     * @type {string}
     * @memberof VirtualInterfaceForDescribeDirectConnectVirtualInterfacesOutput
     */
    LocalIp?: string;

    /**
     * @type {string}
     * @memberof VirtualInterfaceForDescribeDirectConnectVirtualInterfacesOutput
     */
    LocalIpv6Ip?: string;

    /**
     * @type {number}
     * @memberof VirtualInterfaceForDescribeDirectConnectVirtualInterfacesOutput
     */
    NqaDetectInterval?: number;

    /**
     * @type {number}
     * @memberof VirtualInterfaceForDescribeDirectConnectVirtualInterfacesOutput
     */
    NqaDetectMultiplier?: number;

    /**
     * @type {string}
     * @memberof VirtualInterfaceForDescribeDirectConnectVirtualInterfacesOutput
     */
    PeerIp?: string;

    /**
     * @type {string}
     * @memberof VirtualInterfaceForDescribeDirectConnectVirtualInterfacesOutput
     */
    PeerIpv6Ip?: string;

    /**
     * @type {string}
     * @memberof VirtualInterfaceForDescribeDirectConnectVirtualInterfacesOutput
     */
    RouteType?: string;

    /**
     * @type {string}
     * @memberof VirtualInterfaceForDescribeDirectConnectVirtualInterfacesOutput
     */
    Status?: string;

    /**
     * @type {Array<TagForDescribeDirectConnectVirtualInterfacesOutput>}
     * @memberof VirtualInterfaceForDescribeDirectConnectVirtualInterfacesOutput
     */
    Tags?: Array<TagForDescribeDirectConnectVirtualInterfacesOutput>;

    /**
     * @type {string}
     * @memberof VirtualInterfaceForDescribeDirectConnectVirtualInterfacesOutput
     */
    UpdateTime?: string;

    /**
     * @type {string}
     * @memberof VirtualInterfaceForDescribeDirectConnectVirtualInterfacesOutput
     */
    VirtualInterfaceId?: string;

    /**
     * @type {string}
     * @memberof VirtualInterfaceForDescribeDirectConnectVirtualInterfacesOutput
     */
    VirtualInterfaceName?: string;

    /**
     * @type {number}
     * @memberof VirtualInterfaceForDescribeDirectConnectVirtualInterfacesOutput
     */
    VlanId?: number;
}
