/* tslint:disable */
/* eslint-disable */
/**
 * advdefence20230308
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface AvgFlowForDescribeBizFlowAndConnCountOutput
 */
export interface AvgFlowForDescribeBizFlowAndConnCountOutput {

    /**
     * @type {number}
     * @memberof AvgFlowForDescribeBizFlowAndConnCountOutput
     */
    Timestamp?: number;

    /**
     * @type {number}
     * @memberof AvgFlowForDescribeBizFlowAndConnCountOutput
     */
    Value?: number;
}
