/* tslint:disable */
/* eslint-disable */
/**
 * advdefence20230308
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface DropKBpsFlowForDescribeAttackFlowOutput
 */
export interface DropKBpsFlowForDescribeAttackFlowOutput {

    /**
     * @type {string}
     * @memberof DropKBpsFlowForDescribeAttackFlowOutput
     */
    Ip?: string;

    /**
     * @type {number}
     * @memberof DropKBpsFlowForDescribeAttackFlowOutput
     */
    Timestamp?: number;

    /**
     * @type {number}
     * @memberof DropKBpsFlowForDescribeAttackFlowOutput
     */
    Value?: number;
}
