/* tslint:disable */
/* eslint-disable */
/**
 * seccenter
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface SwitchCloudEnvSyncRequest
 */
export interface SwitchCloudEnvSyncRequest {

    /**
     * @type {string}
     * @memberof SwitchCloudEnvSyncRequest
     */
    ID: string;

    /**
     * @type {number}
     * @memberof SwitchCloudEnvSyncRequest
     */
    Status: number;
}
