/* tslint:disable */
/* eslint-disable */
/**
 * speech_saas_prod20250521
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface BatchListMegaTTSTrainStatusRequest
 */
export interface BatchListMegaTTSTrainStatusRequest {

    /**
     * @type {number}
     * @memberof BatchListMegaTTSTrainStatusRequest
     */
    ExpireTimeEnd?: number;

    /**
     * @type {number}
     * @memberof BatchListMegaTTSTrainStatusRequest
     */
    ExpireTimeStart?: number;

    /**
     * @type {number}
     * @memberof BatchListMegaTTSTrainStatusRequest
     */
    MaxResults?: number;

    /**
     * @type {string}
     * @memberof BatchListMegaTTSTrainStatusRequest
     */
    NextToken?: string;

    /**
     * @type {number}
     * @memberof BatchListMegaTTSTrainStatusRequest
     */
    OrderTimeEnd?: number;

    /**
     * @type {number}
     * @memberof BatchListMegaTTSTrainStatusRequest
     */
    OrderTimeStart?: number;

    /**
     * @type {number}
     * @memberof BatchListMegaTTSTrainStatusRequest
     */
    PageNumber?: number;

    /**
     * @type {number}
     * @memberof BatchListMegaTTSTrainStatusRequest
     */
    PageSize?: number;

    /**
     * @type {string}
     * @memberof BatchListMegaTTSTrainStatusRequest
     */
    ProjectName: string;

    /**
     * @type {Array<string>}
     * @memberof BatchListMegaTTSTrainStatusRequest
     */
    SpeakerIDs?: Array<string>;

    /**
     * @type {string}
     * @memberof BatchListMegaTTSTrainStatusRequest
     */
    State: string;
}
