/* tslint:disable */
/* eslint-disable */
/**
 * escloud
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ExtraPerformanceForCreateInstanceInOneStepInput } from './extra-performance-for-create-instance-in-one-step-input';
 /**
 * 
 *
 * @export
 * @interface NodeSpecsAssignForCreateInstanceInOneStepInput
 */
export interface NodeSpecsAssignForCreateInstanceInOneStepInput {

    /**
     * @type {ExtraPerformanceForCreateInstanceInOneStepInput}
     * @memberof NodeSpecsAssignForCreateInstanceInOneStepInput
     */
    ExtraPerformance?: ExtraPerformanceForCreateInstanceInOneStepInput;

    /**
     * @type {number}
     * @memberof NodeSpecsAssignForCreateInstanceInOneStepInput
     */
    Number?: number;

    /**
     * @type {string}
     * @memberof NodeSpecsAssignForCreateInstanceInOneStepInput
     */
    ResourceSpecName?: string;

    /**
     * @type {number}
     * @memberof NodeSpecsAssignForCreateInstanceInOneStepInput
     */
    StorageSize?: number;

    /**
     * @type {string}
     * @memberof NodeSpecsAssignForCreateInstanceInOneStepInput
     */
    StorageSpecName?: string;

    /**
     * @type {string}
     * @memberof NodeSpecsAssignForCreateInstanceInOneStepInput
     */
    Type?: NodeSpecsAssignForCreateInstanceInOneStepInputTypeEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum NodeSpecsAssignForCreateInstanceInOneStepInputTypeEnum {
    Master = 'Master',
    Kibana = 'Kibana',
    Hot = 'Hot',
    Warm = 'Warm',
    Cold = 'Cold',
    Coordinator = 'Coordinator',
    Other = 'Other'
}

