/* tslint:disable */
/* eslint-disable */
/**
 * mcs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ResourceCloudAccountListForPostApiV1OverviewDescribeAssetInfoInput } from './resource-cloud-account-list-for-post-api-v1-overview-describe-asset-info-input';
 /**
 * 
 *
 * @export
 * @interface PostApiV1OverviewDescribeAssetInfoRequest
 */
export interface PostApiV1OverviewDescribeAssetInfoRequest {

    /**
     * @type {Array<ResourceCloudAccountListForPostApiV1OverviewDescribeAssetInfoInput>}
     * @memberof PostApiV1OverviewDescribeAssetInfoRequest
     */
    resource_cloud_account_list?: Array<ResourceCloudAccountListForPostApiV1OverviewDescribeAssetInfoInput>;

    /**
     * @type {Array<string>}
     * @memberof PostApiV1OverviewDescribeAssetInfoRequest
     */
    resource_vendor?: Array<PostApiV1OverviewDescribeAssetInfoRequestResourceVendorEnum>;
}

/**
 * @export
 * @enum {string}
 */
export enum PostApiV1OverviewDescribeAssetInfoRequestResourceVendorEnum {
    Volcengine = 'volcengine',
    Aliyun = 'aliyun',
    Huaweicloud = 'huaweicloud',
    Tencent = 'tencent'
}

