/* tslint:disable */
/* eslint-disable */
/**
 * billing
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface AuthInfoForListInvitationOutput
 */
export interface AuthInfoForListInvitationOutput {

    /**
     * @type {string}
     * @memberof AuthInfoForListInvitationOutput
     */
    AuthID?: string;

    /**
     * @type {Array<number>}
     * @memberof AuthInfoForListInvitationOutput
     */
    AuthList?: Array<number>;

    /**
     * @type {number}
     * @memberof AuthInfoForListInvitationOutput
     */
    AuthStatus?: number;
}
