/* tslint:disable */
/* eslint-disable */
/**
 * billing
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ListBillDetailRequest
 */
export interface ListBillDetailRequest {

    /**
     * @type {Array<string>}
     * @memberof ListBillDetailRequest
     */
    BillCategory?: Array<string>;

    /**
     * @type {string}
     * @memberof ListBillDetailRequest
     */
    BillPeriod: string;

    /**
     * @type {Array<string>}
     * @memberof ListBillDetailRequest
     */
    BillingMode?: Array<string>;

    /**
     * @type {string}
     * @memberof ListBillDetailRequest
     */
    ExpenseDate?: string;

    /**
     * @type {number}
     * @memberof ListBillDetailRequest
     */
    GroupPeriod?: number;

    /**
     * @type {number}
     * @memberof ListBillDetailRequest
     */
    GroupTerm?: number;

    /**
     * @type {number}
     * @memberof ListBillDetailRequest
     */
    IgnoreZero?: number;

    /**
     * @type {string}
     * @memberof ListBillDetailRequest
     */
    InstanceNo?: string;

    /**
     * @type {number}
     * @memberof ListBillDetailRequest
     */
    Limit: number;

    /**
     * @type {number}
     * @memberof ListBillDetailRequest
     */
    NeedRecordNum?: number;

    /**
     * @type {number}
     * @memberof ListBillDetailRequest
     */
    Offset?: number;

    /**
     * @type {Array<number>}
     * @memberof ListBillDetailRequest
     */
    OwnerID?: Array<number>;

    /**
     * @type {Array<number>}
     * @memberof ListBillDetailRequest
     */
    PayerID?: Array<number>;

    /**
     * @type {Array<string>}
     * @memberof ListBillDetailRequest
     */
    Product?: Array<string>;
}
