/* tslint:disable */
/* eslint-disable */
/**
 * billing
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ZoneInfoListForListBudgetFilterZoneCodeOutput } from './zone-info-list-for-list-budget-filter-zone-code-output';
 /**
 * 
 *
 * @export
 * @interface ListBudgetFilterZoneCodeResponse
 */
export interface ListBudgetFilterZoneCodeResponse {

    /**
     * @type {number}
     * @memberof ListBudgetFilterZoneCodeResponse
     */
    Limit?: number;

    /**
     * @type {number}
     * @memberof ListBudgetFilterZoneCodeResponse
     */
    Offset?: number;

    /**
     * @type {number}
     * @memberof ListBudgetFilterZoneCodeResponse
     */
    Total?: number;

    /**
     * @type {Array<ZoneInfoListForListBudgetFilterZoneCodeOutput>}
     * @memberof ListBudgetFilterZoneCodeResponse
     */
    ZoneInfoList?: Array<ZoneInfoListForListBudgetFilterZoneCodeOutput>;
}
