/* tslint:disable */
/* eslint-disable */
/**
 * billing
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ListForListSplitBillDetailOutput } from './list-for-list-split-bill-detail-output';
 /**
 * 
 *
 * @export
 * @interface ListSplitBillDetailResponse
 */
export interface ListSplitBillDetailResponse {

    /**
     * @type {number}
     * @memberof ListSplitBillDetailResponse
     */
    Limit?: number;

    /**
     * @type {Array<ListForListSplitBillDetailOutput>}
     * @memberof ListSplitBillDetailResponse
     */
    List?: Array<ListForListSplitBillDetailOutput>;

    /**
     * @type {number}
     * @memberof ListSplitBillDetailResponse
     */
    Offset?: number;

    /**
     * @type {number}
     * @memberof ListSplitBillDetailResponse
     */
    Total?: number;
}
