/* tslint:disable */
/* eslint-disable */
/**
 * cdn
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { CustomVariableInstanceForDescribeCdnConfigOutput } from './custom-variable-instance-for-describe-cdn-config-output';
 /**
 * 
 *
 * @export
 * @interface CustomVariableRulesForDescribeCdnConfigOutput
 */
export interface CustomVariableRulesForDescribeCdnConfigOutput {

    /**
     * @type {Array<CustomVariableInstanceForDescribeCdnConfigOutput>}
     * @memberof CustomVariableRulesForDescribeCdnConfigOutput
     */
    CustomVariableInstances?: Array<CustomVariableInstanceForDescribeCdnConfigOutput>;
}
