/* tslint:disable */
/* eslint-disable */
/**
 * cdn
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { TopDataDetailForDescribeOriginRankingOutput } from './top-data-detail-for-describe-origin-ranking-output';
 /**
 * 
 *
 * @export
 * @interface DescribeOriginRankingResponse
 */
export interface DescribeOriginRankingResponse {

    /**
     * @type {string}
     * @memberof DescribeOriginRankingResponse
     */
    Item?: string;

    /**
     * @type {Array<TopDataDetailForDescribeOriginRankingOutput>}
     * @memberof DescribeOriginRankingResponse
     */
    TopDataDetails?: Array<TopDataDetailForDescribeOriginRankingOutput>;
}
