/* tslint:disable */
/* eslint-disable */
/**
 * cdn
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface OriginArgComponentForDescribeCdnConfigOutput
 */
export interface OriginArgComponentForDescribeCdnConfigOutput {

    /**
     * @type {string}
     * @memberof OriginArgComponentForDescribeCdnConfigOutput
     */
    Action?: string;

    /**
     * @type {string}
     * @memberof OriginArgComponentForDescribeCdnConfigOutput
     */
    Object?: string;

    /**
     * @type {string}
     * @memberof OriginArgComponentForDescribeCdnConfigOutput
     */
    Subobject?: string;
}
