/* tslint:disable */
/* eslint-disable */
/**
 * cdn
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface UriParamSupForDescribeCdnConfigOutput
 */
export interface UriParamSupForDescribeCdnConfigOutput {

    /**
     * @type {string}
     * @memberof UriParamSupForDescribeCdnConfigOutput
     */
    JoinSymbol?: string;

    /**
     * @type {string}
     * @memberof UriParamSupForDescribeCdnConfigOutput
     */
    SplitSymbol?: string;

    /**
     * @type {number}
     * @memberof UriParamSupForDescribeCdnConfigOutput
     */
    StartLevel?: number;

    /**
     * @type {number}
     * @memberof UriParamSupForDescribeCdnConfigOutput
     */
    TermLevel?: number;
}
