/* tslint:disable */
/* eslint-disable */
/**
 * apig20221112
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ValueForCreateRouteInput } from './value-for-create-route-input';
 /**
 * 
 *
 * @export
 * @interface HeaderForCreateRouteInput
 */
export interface HeaderForCreateRouteInput {

    /**
     * @type {string}
     * @memberof HeaderForCreateRouteInput
     */
    Key?: string;

    /**
     * @type {ValueForCreateRouteInput}
     * @memberof HeaderForCreateRouteInput
     */
    Value?: ValueForCreateRouteInput;
}
