/* tslint:disable */
/* eslint-disable */
/**
 * apig20221112
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AIProviderSettingsForUpdateRouteInput } from './aiprovider-settings-for-update-route-input';
 /**
 * 
 *
 * @export
 * @interface UpstreamListForUpdateRouteInput
 */
export interface UpstreamListForUpdateRouteInput {

    /**
     * @type {AIProviderSettingsForUpdateRouteInput}
     * @memberof UpstreamListForUpdateRouteInput
     */
    AIProviderSettings?: AIProviderSettingsForUpdateRouteInput;

    /**
     * @type {string}
     * @memberof UpstreamListForUpdateRouteInput
     */
    UpstreamId?: string;

    /**
     * @type {string}
     * @memberof UpstreamListForUpdateRouteInput
     */
    Version?: string;

    /**
     * @type {number}
     * @memberof UpstreamListForUpdateRouteInput
     */
    Weight?: number;
}
