/* tslint:disable */
/* eslint-disable */
/**
 * quota
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { DimensionForGetProductQuotaInput } from './dimension-for-get-product-quota-input';
 /**
 * 
 *
 * @export
 * @interface GetProductQuotaRequest
 */
export interface GetProductQuotaRequest {

    /**
     * @type {Array<DimensionForGetProductQuotaInput>}
     * @memberof GetProductQuotaRequest
     */
    Dimensions?: Array<DimensionForGetProductQuotaInput>;

    /**
     * @type {string}
     * @memberof GetProductQuotaRequest
     */
    ProviderCode: string;

    /**
     * @type {string}
     * @memberof GetProductQuotaRequest
     */
    QuotaCode: string;
}
