/* tslint:disable */
/* eslint-disable */
/**
 * cloudmonitor
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ConditionForListRulesByIdsOutput } from './condition-for-list-rules-by-ids-output';
 /**
 * 
 *
 * @export
 * @interface LevelConditionForListRulesByIdsOutput
 */
export interface LevelConditionForListRulesByIdsOutput {

    /**
     * @type {Array<ConditionForListRulesByIdsOutput>}
     * @memberof LevelConditionForListRulesByIdsOutput
     */
    Conditions?: Array<ConditionForListRulesByIdsOutput>;

    /**
     * @type {string}
     * @memberof LevelConditionForListRulesByIdsOutput
     */
    Level?: string;
}
