/* tslint:disable */
/* eslint-disable */
/**
 * cloudmonitor
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ListContactGroupsRequest
 */
export interface ListContactGroupsRequest {

    /**
     * @type {string}
     * @memberof ListContactGroupsRequest
     */
    Name?: string;

    /**
     * @type {number}
     * @memberof ListContactGroupsRequest
     */
    PageNumber?: number;

    /**
     * @type {number}
     * @memberof ListContactGroupsRequest
     */
    PageSize?: number;
}
