/* tslint:disable */
/* eslint-disable */
/**
 * cloudmonitor
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface NoDataForCreateRuleInput
 */
export interface NoDataForCreateRuleInput {

    /**
     * @type {boolean}
     * @memberof NoDataForCreateRuleInput
     */
    Enable?: boolean;

    /**
     * @type {number}
     * @memberof NoDataForCreateRuleInput
     */
    EvaluationCount?: number;

    /**
     * @type {string}
     * @memberof NoDataForCreateRuleInput
     */
    Level?: string;
}
