/* tslint:disable */
/* eslint-disable */
/**
 * cloudmonitor
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { DimensionConditionsForCreateObjectGroupInput } from './dimension-conditions-for-create-object-group-input';
 /**
 * 
 *
 * @export
 * @interface ObjectForCreateObjectGroupInput
 */
export interface ObjectForCreateObjectGroupInput {

    /**
     * @type {DimensionConditionsForCreateObjectGroupInput}
     * @memberof ObjectForCreateObjectGroupInput
     */
    DimensionConditions?: DimensionConditionsForCreateObjectGroupInput;

    /**
     * @type {{ [key: string]: Array<string>; }}
     * @memberof ObjectForCreateObjectGroupInput
     */
    Dimensions?: { [key: string]: Array<string>; };

    /**
     * @type {string}
     * @memberof ObjectForCreateObjectGroupInput
     */
    Namespace?: string;

    /**
     * @type {string}
     * @memberof ObjectForCreateObjectGroupInput
     */
    Region?: string;

    /**
     * @type {string}
     * @memberof ObjectForCreateObjectGroupInput
     */
    Type?: string;
}
