/* tslint:disable */
/* eslint-disable */
/**
 * ark
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ItemForListFoundationModelVersionsOutput
 */
export interface ItemForListFoundationModelVersionsOutput {

    /**
     * @type {string}
     * @memberof ItemForListFoundationModelVersionsOutput
     */
    ActiveConfigurationId?: string;

    /**
     * @type {string}
     * @memberof ItemForListFoundationModelVersionsOutput
     */
    CreateTime?: string;

    /**
     * @type {string}
     * @memberof ItemForListFoundationModelVersionsOutput
     */
    Description?: string;

    /**
     * @type {string}
     * @memberof ItemForListFoundationModelVersionsOutput
     */
    FoundationModelName?: string;

    /**
     * @type {string}
     * @memberof ItemForListFoundationModelVersionsOutput
     */
    ModelVersion?: string;

    /**
     * @type {string}
     * @memberof ItemForListFoundationModelVersionsOutput
     */
    PublishTime?: string;

    /**
     * @type {string}
     * @memberof ItemForListFoundationModelVersionsOutput
     */
    Status?: string;

    /**
     * @type {string}
     * @memberof ItemForListFoundationModelVersionsOutput
     */
    UpdateTime?: string;
}
