/* tslint:disable */
/* eslint-disable */
/**
 * ark
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ItemForListAuditLogsOutput } from './item-for-list-audit-logs-output';
 /**
 * 
 *
 * @export
 * @interface ListAuditLogsResponse
 */
export interface ListAuditLogsResponse {

    /**
     * @type {Array<ItemForListAuditLogsOutput>}
     * @memberof ListAuditLogsResponse
     */
    Items?: Array<ItemForListAuditLogsOutput>;

    /**
     * @type {number}
     * @memberof ListAuditLogsResponse
     */
    PageNumber?: number;

    /**
     * @type {number}
     * @memberof ListAuditLogsResponse
     */
    PageSize?: number;

    /**
     * @type {number}
     * @memberof ListAuditLogsResponse
     */
    TotalCount?: number;
}
