/* tslint:disable */
/* eslint-disable */
/**
 * ark
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { FilterForListAuditLogsInput } from './filter-for-list-audit-logs-input';
 /**
 * 
 *
 * @export
 * @interface ListAuditLogsRequest
 */
export interface ListAuditLogsRequest {

    /**
     * @type {FilterForListAuditLogsInput}
     * @memberof ListAuditLogsRequest
     */
    Filter?: FilterForListAuditLogsInput;

    /**
     * @type {number}
     * @memberof ListAuditLogsRequest
     */
    PageNumber?: number;

    /**
     * @type {number}
     * @memberof ListAuditLogsRequest
     */
    PageSize?: number;

    /**
     * @type {string}
     * @memberof ListAuditLogsRequest
     */
    ProjectName?: string;

    /**
     * @type {string}
     * @memberof ListAuditLogsRequest
     */
    ResourceId: string;

    /**
     * @type {string}
     * @memberof ListAuditLogsRequest
     */
    ResourceType: ListAuditLogsRequestResourceTypeEnum;

    /**
     * @type {string}
     * @memberof ListAuditLogsRequest
     */
    SortBy?: ListAuditLogsRequestSortByEnum;

    /**
     * @type {string}
     * @memberof ListAuditLogsRequest
     */
    SortOrder?: ListAuditLogsRequestSortOrderEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum ListAuditLogsRequestResourceTypeEnum {
    Endpoint = 'endpoint',
    Modelcustomizationjob = 'modelcustomizationjob'
}
/**
 * @export
 * @enum {string}
 */
export enum ListAuditLogsRequestSortByEnum {
    Timestamp = 'Timestamp'
}
/**
 * @export
 * @enum {string}
 */
export enum ListAuditLogsRequestSortOrderEnum {
    Desc = 'Desc',
    Asc = ' Asc'
}

