/* tslint:disable */
/* eslint-disable */
/**
 * ark
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface StatusForGetModelCustomizationJobOutput
 */
export interface StatusForGetModelCustomizationJobOutput {

    /**
     * @type {number}
     * @memberof StatusForGetModelCustomizationJobOutput
     */
    BillableTokens?: number;

    /**
     * @type {string}
     * @memberof StatusForGetModelCustomizationJobOutput
     */
    Message?: string;

    /**
     * @type {string}
     * @memberof StatusForGetModelCustomizationJobOutput
     */
    OutputExpiredTime?: string;

    /**
     * @type {string}
     * @memberof StatusForGetModelCustomizationJobOutput
     */
    Phase?: StatusForGetModelCustomizationJobOutputPhaseEnum;

    /**
     * @type {string}
     * @memberof StatusForGetModelCustomizationJobOutput
     */
    PhaseTime?: string;

    /**
     * @type {number}
     * @memberof StatusForGetModelCustomizationJobOutput
     */
    QueuePosition?: number;

    /**
     * @type {boolean}
     * @memberof StatusForGetModelCustomizationJobOutput
     */
    Resumable?: boolean;

    /**
     * @type {number}
     * @memberof StatusForGetModelCustomizationJobOutput
     */
    RetryCount?: number;

    /**
     * @type {number}
     * @memberof StatusForGetModelCustomizationJobOutput
     */
    RetryLimit?: number;

    /**
     * @type {number}
     * @memberof StatusForGetModelCustomizationJobOutput
     */
    TrainingTokensPerEpoch?: number;
}

/**
 * @export
 * @enum {string}
 */
export enum StatusForGetModelCustomizationJobOutputPhaseEnum {
    Preprocessing = 'Preprocessing',
    Queued = 'Queued',
    Deploying = 'Deploying',
    Running = 'Running',
    Completing = 'Completing',
    Completed = 'Completed',
    Terminating = 'Terminating',
    Terminated = 'Terminated',
    Failed = 'Failed'
}

