/* tslint:disable */
/* eslint-disable */
/**
 * vpc
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface CreateSubnetResponse
 */
export interface CreateSubnetResponse {

    /**
     * @type {string}
     * @memberof CreateSubnetResponse
     */
    AsyncTaskId?: string;

    /**
     * @type {string}
     * @memberof CreateSubnetResponse
     */
    RequestId?: string;

    /**
     * @type {string}
     * @memberof CreateSubnetResponse
     */
    SubnetId?: string;
}
