/* tslint:disable */
/* eslint-disable */
/**
 * vpc
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface DescribePrefixListEntriesRequest
 */
export interface DescribePrefixListEntriesRequest {

    /**
     * @type {number}
     * @memberof DescribePrefixListEntriesRequest
     */
    MaxResults?: number;

    /**
     * @type {string}
     * @memberof DescribePrefixListEntriesRequest
     */
    NextToken?: string;

    /**
     * @type {number}
     * @memberof DescribePrefixListEntriesRequest
     */
    PageNumber?: number;

    /**
     * @type {number}
     * @memberof DescribePrefixListEntriesRequest
     */
    PageSize?: number;

    /**
     * @type {string}
     * @memberof DescribePrefixListEntriesRequest
     */
    PrefixListId: string;
}
