/* tslint:disable */
/* eslint-disable */
/**
 * vpc
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { HaVipForDescribeHaVipsOutput } from './ha-vip-for-describe-ha-vips-output';
 /**
 * 
 *
 * @export
 * @interface DescribeHaVipsResponse
 */
export interface DescribeHaVipsResponse {

    /**
     * @type {Array<HaVipForDescribeHaVipsOutput>}
     * @memberof DescribeHaVipsResponse
     */
    HaVips?: Array<HaVipForDescribeHaVipsOutput>;

    /**
     * @type {string}
     * @memberof DescribeHaVipsResponse
     */
    NextToken?: string;

    /**
     * @type {number}
     * @memberof DescribeHaVipsResponse
     */
    PageNumber?: number;

    /**
     * @type {number}
     * @memberof DescribeHaVipsResponse
     */
    PageSize?: number;

    /**
     * @type {string}
     * @memberof DescribeHaVipsResponse
     */
    RequestId?: string;

    /**
     * @type {number}
     * @memberof DescribeHaVipsResponse
     */
    TotalCount?: number;
}
