/* tslint:disable */
/* eslint-disable */
/**
 * vpc
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { TagFilterForDescribeVpcsInput } from './tag-filter-for-describe-vpcs-input';
 /**
 * 
 *
 * @export
 * @interface DescribeVpcsRequest
 */
export interface DescribeVpcsRequest {

    /**
     * @type {boolean}
     * @memberof DescribeVpcsRequest
     */
    IsDefault?: boolean;

    /**
     * @type {number}
     * @memberof DescribeVpcsRequest
     */
    MaxResults?: number;

    /**
     * @type {string}
     * @memberof DescribeVpcsRequest
     */
    NextToken?: string;

    /**
     * @type {number}
     * @memberof DescribeVpcsRequest
     */
    PageNumber?: number;

    /**
     * @type {number}
     * @memberof DescribeVpcsRequest
     */
    PageSize?: number;

    /**
     * @type {string}
     * @memberof DescribeVpcsRequest
     */
    ProjectName?: string;

    /**
     * @type {Array<TagFilterForDescribeVpcsInput>}
     * @memberof DescribeVpcsRequest
     */
    TagFilters?: Array<TagFilterForDescribeVpcsInput>;

    /**
     * @type {Array<string>}
     * @memberof DescribeVpcsRequest
     */
    VpcIds?: Array<string>;

    /**
     * @type {string}
     * @memberof DescribeVpcsRequest
     */
    VpcName?: string;

    /**
     * @type {number}
     * @memberof DescribeVpcsRequest
     */
    VpcOwnerId?: number;
}
