/* tslint:disable */
/* eslint-disable */
/**
 * vpc
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AddPrefixListEntryForModifyPrefixListInput } from './add-prefix-list-entry-for-modify-prefix-list-input';
import { RemovePrefixListEntryForModifyPrefixListInput } from './remove-prefix-list-entry-for-modify-prefix-list-input';
 /**
 * 
 *
 * @export
 * @interface ModifyPrefixListRequest
 */
export interface ModifyPrefixListRequest {

    /**
     * @type {Array<AddPrefixListEntryForModifyPrefixListInput>}
     * @memberof ModifyPrefixListRequest
     */
    AddPrefixListEntries?: Array<AddPrefixListEntryForModifyPrefixListInput>;

    /**
     * @type {string}
     * @memberof ModifyPrefixListRequest
     */
    ClientToken?: string;

    /**
     * @type {string}
     * @memberof ModifyPrefixListRequest
     */
    Description?: string;

    /**
     * @type {boolean}
     * @memberof ModifyPrefixListRequest
     */
    DryRun?: boolean;

    /**
     * @type {number}
     * @memberof ModifyPrefixListRequest
     */
    MaxEntries?: number;

    /**
     * @type {string}
     * @memberof ModifyPrefixListRequest
     */
    PrefixListId: string;

    /**
     * @type {string}
     * @memberof ModifyPrefixListRequest
     */
    PrefixListName?: string;

    /**
     * @type {Array<RemovePrefixListEntryForModifyPrefixListInput>}
     * @memberof ModifyPrefixListRequest
     */
    RemovePrefixListEntries?: Array<RemovePrefixListEntryForModifyPrefixListInput>;
}
