/* tslint:disable */
/* eslint-disable */
/**
 * vpc
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface TagForCreateNetworkInterfaceInput
 */
export interface TagForCreateNetworkInterfaceInput {

    /**
     * @type {string}
     * @memberof TagForCreateNetworkInterfaceInput
     */
    Key?: string;

    /**
     * @type {string}
     * @memberof TagForCreateNetworkInterfaceInput
     */
    Value?: string;
}
