/* tslint:disable */
/* eslint-disable */
/**
 * i18n_openapi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ConvertsubtitleForVideoProjectSerialTaskCreateInput
 */
export interface ConvertsubtitleForVideoProjectSerialTaskCreateInput {

    /**
     * @type {number}
     * @memberof ConvertsubtitleForVideoProjectSerialTaskCreateInput
     */
    arrangement?: number;

    /**
     * @type {number}
     * @memberof ConvertsubtitleForVideoProjectSerialTaskCreateInput
     */
    fileType?: number;

    /**
     * @type {string}
     * @memberof ConvertsubtitleForVideoProjectSerialTaskCreateInput
     */
    name?: string;

    /**
     * @type {number}
     * @memberof ConvertsubtitleForVideoProjectSerialTaskCreateInput
     */
    subtitleLang?: number;

    /**
     * @type {string}
     * @memberof ConvertsubtitleForVideoProjectSerialTaskCreateInput
     */
    targetLang?: string;

    /**
     * @type {string}
     * @memberof ConvertsubtitleForVideoProjectSerialTaskCreateInput
     */
    uri?: string;
}
