/* tslint:disable */
/* eslint-disable */
/**
 * rds_postgresql
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface DescribePlannedEventsRequest
 */
export interface DescribePlannedEventsRequest {

    /**
     * @type {string}
     * @memberof DescribePlannedEventsRequest
     */
    EventId?: string;

    /**
     * @type {Array<string>}
     * @memberof DescribePlannedEventsRequest
     */
    EventType?: Array<string>;

    /**
     * @type {string}
     * @memberof DescribePlannedEventsRequest
     */
    InstanceId?: string;

    /**
     * @type {string}
     * @memberof DescribePlannedEventsRequest
     */
    InstanceName?: string;

    /**
     * @type {number}
     * @memberof DescribePlannedEventsRequest
     */
    PageNumber?: number;

    /**
     * @type {number}
     * @memberof DescribePlannedEventsRequest
     */
    PageSize?: number;

    /**
     * @type {string}
     * @memberof DescribePlannedEventsRequest
     */
    PlannedBeginTimeSearchRangeEnd?: string;

    /**
     * @type {string}
     * @memberof DescribePlannedEventsRequest
     */
    PlannedBeginTimeSearchRangeStart?: string;

    /**
     * @type {string}
     * @memberof DescribePlannedEventsRequest
     */
    PlannedSwitchTimeSearchRangeEnd?: string;

    /**
     * @type {string}
     * @memberof DescribePlannedEventsRequest
     */
    PlannedSwitchTimeSearchRangeStart?: string;

    /**
     * @type {Array<string>}
     * @memberof DescribePlannedEventsRequest
     */
    Status?: Array<string>;
}
