/* tslint:disable */
/* eslint-disable */
/**
 * rds_postgresql
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { BasicInfoForDescribeDBInstanceDetailOutput } from './basic-info-for-describe-dbinstance-detail-output';
import { ChargeDetailForDescribeDBInstanceDetailOutput } from './charge-detail-for-describe-dbinstance-detail-output';
import { EndpointForDescribeDBInstanceDetailOutput } from './endpoint-for-describe-dbinstance-detail-output';
import { NodeForDescribeDBInstanceDetailOutput } from './node-for-describe-dbinstance-detail-output';
 /**
 * 
 *
 * @export
 * @interface DescribeDBInstanceDetailResponse
 */
export interface DescribeDBInstanceDetailResponse {

    /**
     * @type {BasicInfoForDescribeDBInstanceDetailOutput}
     * @memberof DescribeDBInstanceDetailResponse
     */
    BasicInfo?: BasicInfoForDescribeDBInstanceDetailOutput;

    /**
     * @type {ChargeDetailForDescribeDBInstanceDetailOutput}
     * @memberof DescribeDBInstanceDetailResponse
     */
    ChargeDetail?: ChargeDetailForDescribeDBInstanceDetailOutput;

    /**
     * @type {Array<EndpointForDescribeDBInstanceDetailOutput>}
     * @memberof DescribeDBInstanceDetailResponse
     */
    Endpoints?: Array<EndpointForDescribeDBInstanceDetailOutput>;

    /**
     * @type {Array<NodeForDescribeDBInstanceDetailOutput>}
     * @memberof DescribeDBInstanceDetailResponse
     */
    Nodes?: Array<NodeForDescribeDBInstanceDetailOutput>;
}
