/* tslint:disable */
/* eslint-disable */
/**
 * rds_postgresql
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface DisassociateAllowListRequest
 */
export interface DisassociateAllowListRequest {

    /**
     * @type {Array<string>}
     * @memberof DisassociateAllowListRequest
     */
    AllowListIds?: Array<string>;

    /**
     * @type {Array<string>}
     * @memberof DisassociateAllowListRequest
     */
    InstanceIds?: Array<string>;
}
