/* tslint:disable */
/* eslint-disable */
/**
 * rds_postgresql
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ModifyDBEndpointNameRequest
 */
export interface ModifyDBEndpointNameRequest {

    /**
     * @type {string}
     * @memberof ModifyDBEndpointNameRequest
     */
    EndpointId: string;

    /**
     * @type {string}
     * @memberof ModifyDBEndpointNameRequest
     */
    EndpointName: string;

    /**
     * @type {string}
     * @memberof ModifyDBEndpointNameRequest
     */
    InstanceId: string;
}
