/* tslint:disable */
/* eslint-disable */
/**
 * rds_postgresql
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ChargeInfoForRestoreToNewInstanceInput } from './charge-info-for-restore-to-new-instance-input';
import { MaintenanceWindowForRestoreToNewInstanceInput } from './maintenance-window-for-restore-to-new-instance-input';
import { NodeInfoForRestoreToNewInstanceInput } from './node-info-for-restore-to-new-instance-input';
import { TagForRestoreToNewInstanceInput } from './tag-for-restore-to-new-instance-input';
 /**
 * 
 *
 * @export
 * @interface RestoreToNewInstanceRequest
 */
export interface RestoreToNewInstanceRequest {

    /**
     * @type {Array<string>}
     * @memberof RestoreToNewInstanceRequest
     */
    AllowListIds?: Array<string>;

    /**
     * @type {string}
     * @memberof RestoreToNewInstanceRequest
     */
    BackupId?: string;

    /**
     * @type {ChargeInfoForRestoreToNewInstanceInput}
     * @memberof RestoreToNewInstanceRequest
     */
    ChargeInfo?: ChargeInfoForRestoreToNewInstanceInput;

    /**
     * @type {string}
     * @memberof RestoreToNewInstanceRequest
     */
    InstanceName?: string;

    /**
     * @type {MaintenanceWindowForRestoreToNewInstanceInput}
     * @memberof RestoreToNewInstanceRequest
     */
    MaintenanceWindow?: MaintenanceWindowForRestoreToNewInstanceInput;

    /**
     * @type {Array<NodeInfoForRestoreToNewInstanceInput>}
     * @memberof RestoreToNewInstanceRequest
     */
    NodeInfo?: Array<NodeInfoForRestoreToNewInstanceInput>;

    /**
     * @type {string}
     * @memberof RestoreToNewInstanceRequest
     */
    ProjectName?: string;

    /**
     * @type {string}
     * @memberof RestoreToNewInstanceRequest
     */
    RestoreTime?: string;

    /**
     * @type {string}
     * @memberof RestoreToNewInstanceRequest
     */
    SrcInstanceId: string;

    /**
     * @type {number}
     * @memberof RestoreToNewInstanceRequest
     */
    StorageSpace?: number;

    /**
     * @type {string}
     * @memberof RestoreToNewInstanceRequest
     */
    StorageType: string;

    /**
     * @type {string}
     * @memberof RestoreToNewInstanceRequest
     */
    SubnetId: string;

    /**
     * @type {Array<TagForRestoreToNewInstanceInput>}
     * @memberof RestoreToNewInstanceRequest
     */
    Tags?: Array<TagForRestoreToNewInstanceInput>;

    /**
     * @type {string}
     * @memberof RestoreToNewInstanceRequest
     */
    VpcId: string;
}
