/* tslint:disable */
/* eslint-disable */
/**
 * sqs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface MessageForReceiveMessageOutput
 */
export interface MessageForReceiveMessageOutput {

    /**
     * @type {string}
     * @memberof MessageForReceiveMessageOutput
     */
    MessageBody?: string;

    /**
     * @type {string}
     * @memberof MessageForReceiveMessageOutput
     */
    MessageId?: string;

    /**
     * @type {string}
     * @memberof MessageForReceiveMessageOutput
     */
    ReceiptHandle?: string;
}
