/* tslint:disable */
/* eslint-disable */
/**
 * sec_agent
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ListToolProductRequest
 */
export interface ListToolProductRequest {

    /**
     * @type {number}
     * @memberof ListToolProductRequest
     */
    CurrentPage: number;

    /**
     * @type {string}
     * @memberof ListToolProductRequest
     */
    LikeProductName: string;

    /**
     * @type {number}
     * @memberof ListToolProductRequest
     */
    PageSize: number;
}
