/* tslint:disable */
/* eslint-disable */
/**
 * ecs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { OperationDetailForAttachKeyPairOutput } from './operation-detail-for-attach-key-pair-output';
 /**
 * 
 *
 * @export
 * @interface AttachKeyPairResponse
 */
export interface AttachKeyPairResponse {

    /**
     * @type {Array<OperationDetailForAttachKeyPairOutput>}
     * @memberof AttachKeyPairResponse
     */
    OperationDetails?: Array<OperationDetailForAttachKeyPairOutput>;
}
