/* tslint:disable */
/* eslint-disable */
/**
 * ecs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface DeleteKeyPairsRequest
 */
export interface DeleteKeyPairsRequest {

    /**
     * @type {string}
     * @memberof DeleteKeyPairsRequest
     */
    ClientToken?: string;

    /**
     * @type {Array<string>}
     * @memberof DeleteKeyPairsRequest
     */
    KeyPairNames?: Array<string>;
}
