/* tslint:disable */
/* eslint-disable */
/**
 * ecs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { OperationDetailForDeleteInstancesOutput } from './operation-detail-for-delete-instances-output';
 /**
 * 
 *
 * @export
 * @interface DeleteInstancesResponse
 */
export interface DeleteInstancesResponse {

    /**
     * @type {Array<OperationDetailForDeleteInstancesOutput>}
     * @memberof DeleteInstancesResponse
     */
    OperationDetails?: Array<OperationDetailForDeleteInstancesOutput>;
}
