/* tslint:disable */
/* eslint-disable */
/**
 * ecs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { TagFilterForDescribeInstancesInput } from './tag-filter-for-describe-instances-input';
 /**
 * 
 *
 * @export
 * @interface DescribeInstancesRequest
 */
export interface DescribeInstancesRequest {

    /**
     * @type {Array<string>}
     * @memberof DescribeInstancesRequest
     */
    AffinityGroupIds?: Array<string>;

    /**
     * @type {string}
     * @memberof DescribeInstancesRequest
     */
    DedicatedHostClusterId?: string;

    /**
     * @type {string}
     * @memberof DescribeInstancesRequest
     */
    DedicatedHostId?: string;

    /**
     * @type {Array<number>}
     * @memberof DescribeInstancesRequest
     */
    DeploymentSetGroupNumbers?: Array<number>;

    /**
     * @type {Array<string>}
     * @memberof DescribeInstancesRequest
     */
    DeploymentSetIds?: Array<string>;

    /**
     * @type {Array<string>}
     * @memberof DescribeInstancesRequest
     */
    EipAddresses?: Array<string>;

    /**
     * @type {string}
     * @memberof DescribeInstancesRequest
     */
    HpcClusterId?: string;

    /**
     * @type {string}
     * @memberof DescribeInstancesRequest
     */
    InstanceChargeType?: string;

    /**
     * @type {Array<string>}
     * @memberof DescribeInstancesRequest
     */
    InstanceIds?: Array<string>;

    /**
     * @type {string}
     * @memberof DescribeInstancesRequest
     */
    InstanceName?: string;

    /**
     * @type {Array<string>}
     * @memberof DescribeInstancesRequest
     */
    InstanceTypeFamilies?: Array<string>;

    /**
     * @type {Array<string>}
     * @memberof DescribeInstancesRequest
     */
    InstanceTypeIds?: Array<string>;

    /**
     * @type {Array<string>}
     * @memberof DescribeInstancesRequest
     */
    InstanceTypes?: Array<string>;

    /**
     * @type {Array<string>}
     * @memberof DescribeInstancesRequest
     */
    Ipv6Addresses?: Array<string>;

    /**
     * @type {string}
     * @memberof DescribeInstancesRequest
     */
    KeyPairName?: string;

    /**
     * @type {number}
     * @memberof DescribeInstancesRequest
     */
    MaxResults?: number;

    /**
     * @type {string}
     * @memberof DescribeInstancesRequest
     */
    NextToken?: string;

    /**
     * @type {string}
     * @memberof DescribeInstancesRequest
     */
    PrimaryIpAddress?: string;

    /**
     * @type {string}
     * @memberof DescribeInstancesRequest
     */
    ProjectName?: string;

    /**
     * @type {string}
     * @memberof DescribeInstancesRequest
     */
    ScheduledInstanceId?: string;

    /**
     * @type {string}
     * @memberof DescribeInstancesRequest
     */
    Status?: string;

    /**
     * @type {Array<TagFilterForDescribeInstancesInput>}
     * @memberof DescribeInstancesRequest
     */
    TagFilters?: Array<TagFilterForDescribeInstancesInput>;

    /**
     * @type {string}
     * @memberof DescribeInstancesRequest
     */
    VpcId?: string;

    /**
     * @type {string}
     * @memberof DescribeInstancesRequest
     */
    ZoneId?: string;
}
