/* tslint:disable */
/* eslint-disable */
/**
 * ecs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface LocalVolumeForDescribeInstancesOutput
 */
export interface LocalVolumeForDescribeInstancesOutput {

    /**
     * @type {number}
     * @memberof LocalVolumeForDescribeInstancesOutput
     */
    Count?: number;

    /**
     * @type {number}
     * @memberof LocalVolumeForDescribeInstancesOutput
     */
    Size?: number;

    /**
     * @type {string}
     * @memberof LocalVolumeForDescribeInstancesOutput
     */
    VolumeType?: string;
}
