/* tslint:disable */
/* eslint-disable */
/**
 * ecs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface PlacementForAllocateInstancesInput
 */
export interface PlacementForAllocateInstancesInput {

    /**
     * @type {string}
     * @memberof PlacementForAllocateInstancesInput
     */
    Affinity?: string;

    /**
     * @type {string}
     * @memberof PlacementForAllocateInstancesInput
     */
    DedicatedHostClusterId?: string;

    /**
     * @type {string}
     * @memberof PlacementForAllocateInstancesInput
     */
    DedicatedHostId?: string;

    /**
     * @type {string}
     * @memberof PlacementForAllocateInstancesInput
     */
    Tenancy?: string;
}
