/* tslint:disable */
/* eslint-disable */
/**
 * rds_mssql
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { BackupsInfoForDescribeBackupDetailOutput } from './backups-info-for-describe-backup-detail-output';
 /**
 * 
 *
 * @export
 * @interface DescribeBackupDetailResponse
 */
export interface DescribeBackupDetailResponse {

    /**
     * @type {BackupsInfoForDescribeBackupDetailOutput}
     * @memberof DescribeBackupDetailResponse
     */
    BackupsInfo?: BackupsInfoForDescribeBackupDetailOutput;
}
