/* tslint:disable */
/* eslint-disable */
/**
 * filenas
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { EvictPolicyForDescribeDataFlowTasksOutput } from './evict-policy-for-describe-data-flow-tasks-output';
import { ExportPolicyForDescribeDataFlowTasksOutput } from './export-policy-for-describe-data-flow-tasks-output';
import { ImportPolicyForDescribeDataFlowTasksOutput } from './import-policy-for-describe-data-flow-tasks-output';
 /**
 * 
 *
 * @export
 * @interface DataFlowTaskForDescribeDataFlowTasksOutput
 */
export interface DataFlowTaskForDescribeDataFlowTasksOutput {

    /**
     * @type {string}
     * @memberof DataFlowTaskForDescribeDataFlowTasksOutput
     */
    BucketName?: string;

    /**
     * @type {string}
     * @memberof DataFlowTaskForDescribeDataFlowTasksOutput
     */
    BucketPrefix?: string;

    /**
     * @type {string}
     * @memberof DataFlowTaskForDescribeDataFlowTasksOutput
     */
    CreateTime?: string;

    /**
     * @type {string}
     * @memberof DataFlowTaskForDescribeDataFlowTasksOutput
     */
    DataFlowId?: string;

    /**
     * @type {string}
     * @memberof DataFlowTaskForDescribeDataFlowTasksOutput
     */
    EndTime?: string;

    /**
     * @type {string}
     * @memberof DataFlowTaskForDescribeDataFlowTasksOutput
     */
    EntryListFileBucket?: string;

    /**
     * @type {string}
     * @memberof DataFlowTaskForDescribeDataFlowTasksOutput
     */
    EntryListFileKey?: string;

    /**
     * @type {string}
     * @memberof DataFlowTaskForDescribeDataFlowTasksOutput
     */
    EntryListFileName?: string;

    /**
     * @type {string}
     * @memberof DataFlowTaskForDescribeDataFlowTasksOutput
     */
    EntryListFileUrl?: string;

    /**
     * @type {EvictPolicyForDescribeDataFlowTasksOutput}
     * @memberof DataFlowTaskForDescribeDataFlowTasksOutput
     */
    EvictPolicy?: EvictPolicyForDescribeDataFlowTasksOutput;

    /**
     * @type {ExportPolicyForDescribeDataFlowTasksOutput}
     * @memberof DataFlowTaskForDescribeDataFlowTasksOutput
     */
    ExportPolicy?: ExportPolicyForDescribeDataFlowTasksOutput;

    /**
     * @type {string}
     * @memberof DataFlowTaskForDescribeDataFlowTasksOutput
     */
    FileSystemId?: string;

    /**
     * @type {string}
     * @memberof DataFlowTaskForDescribeDataFlowTasksOutput
     */
    FileSystemPath?: string;

    /**
     * @type {string}
     * @memberof DataFlowTaskForDescribeDataFlowTasksOutput
     */
    Id?: string;

    /**
     * @type {ImportPolicyForDescribeDataFlowTasksOutput}
     * @memberof DataFlowTaskForDescribeDataFlowTasksOutput
     */
    ImportPolicy?: ImportPolicyForDescribeDataFlowTasksOutput;

    /**
     * @type {number}
     * @memberof DataFlowTaskForDescribeDataFlowTasksOutput
     */
    QueueExec?: number;

    /**
     * @type {number}
     * @memberof DataFlowTaskForDescribeDataFlowTasksOutput
     */
    QueueFailed?: number;

    /**
     * @type {number}
     * @memberof DataFlowTaskForDescribeDataFlowTasksOutput
     */
    QueueLen?: number;

    /**
     * @type {string}
     * @memberof DataFlowTaskForDescribeDataFlowTasksOutput
     */
    SameNameFilePolicy?: DataFlowTaskForDescribeDataFlowTasksOutputSameNameFilePolicyEnum;

    /**
     * @type {string}
     * @memberof DataFlowTaskForDescribeDataFlowTasksOutput
     */
    StartTime?: string;

    /**
     * @type {string}
     * @memberof DataFlowTaskForDescribeDataFlowTasksOutput
     */
    Status?: DataFlowTaskForDescribeDataFlowTasksOutputStatusEnum;

    /**
     * @type {string}
     * @memberof DataFlowTaskForDescribeDataFlowTasksOutput
     */
    Type?: DataFlowTaskForDescribeDataFlowTasksOutputTypeEnum;

    /**
     * @type {string}
     * @memberof DataFlowTaskForDescribeDataFlowTasksOutput
     */
    UpdateTime?: string;
}

/**
 * @export
 * @enum {string}
 */
export enum DataFlowTaskForDescribeDataFlowTasksOutputSameNameFilePolicyEnum {
    Skip = 'Skip',
    KeepLatest = 'KeepLatest',
    OverWrite = 'OverWrite'
}
/**
 * @export
 * @enum {string}
 */
export enum DataFlowTaskForDescribeDataFlowTasksOutputStatusEnum {
    Creating = 'Creating',
    Running = 'Running',
    Finished = 'Finished',
    Canceling = 'Canceling',
    Canceled = 'Canceled',
    Deleting = 'Deleting',
    Error = 'Error'
}
/**
 * @export
 * @enum {string}
 */
export enum DataFlowTaskForDescribeDataFlowTasksOutputTypeEnum {
    Import = 'Import',
    Export = 'Export',
    Evict = 'Evict'
}

