/* tslint:disable */
/* eslint-disable */
/**
 * filenas
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { FilterForDescribeFileSystemsInput } from './filter-for-describe-file-systems-input';
import { TagFilterForDescribeFileSystemsInput } from './tag-filter-for-describe-file-systems-input';
 /**
 * 
 *
 * @export
 * @interface DescribeFileSystemsRequest
 */
export interface DescribeFileSystemsRequest {

    /**
     * @type {string}
     * @memberof DescribeFileSystemsRequest
     */
    FileSystemIds?: string;

    /**
     * @type {string}
     * @memberof DescribeFileSystemsRequest
     */
    FileSystemType?: DescribeFileSystemsRequestFileSystemTypeEnum;

    /**
     * @type {Array<FilterForDescribeFileSystemsInput>}
     * @memberof DescribeFileSystemsRequest
     */
    Filters?: Array<FilterForDescribeFileSystemsInput>;

    /**
     * @type {number}
     * @memberof DescribeFileSystemsRequest
     */
    PageNumber?: number;

    /**
     * @type {number}
     * @memberof DescribeFileSystemsRequest
     */
    PageSize?: number;

    /**
     * @type {string}
     * @memberof DescribeFileSystemsRequest
     */
    ProjectName?: string;

    /**
     * @type {Array<TagFilterForDescribeFileSystemsInput>}
     * @memberof DescribeFileSystemsRequest
     */
    TagFilters?: Array<TagFilterForDescribeFileSystemsInput>;
}

/**
 * @export
 * @enum {string}
 */
export enum DescribeFileSystemsRequestFileSystemTypeEnum {
    Extreme = 'Extreme',
    Capacity = 'Capacity',
    Cache = 'Cache'
}

