/* tslint:disable */
/* eslint-disable */
/**
 * filenas
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface OverviewForDescribeFileSystemOverviewOutput
 */
export interface OverviewForDescribeFileSystemOverviewOutput {

    /**
     * @type {number}
     * @memberof OverviewForDescribeFileSystemOverviewOutput
     */
    ErrorCount?: number;

    /**
     * @type {number}
     * @memberof OverviewForDescribeFileSystemOverviewOutput
     */
    OtherCount?: number;

    /**
     * @type {string}
     * @memberof OverviewForDescribeFileSystemOverviewOutput
     */
    RegionId?: string;

    /**
     * @type {number}
     * @memberof OverviewForDescribeFileSystemOverviewOutput
     */
    RunningCount?: number;

    /**
     * @type {number}
     * @memberof OverviewForDescribeFileSystemOverviewOutput
     */
    TotalCount?: number;
}
