/* tslint:disable */
/* eslint-disable */
/**
 * filenas
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface PermissionRuleForUpdatePermissionRuleInput
 */
export interface PermissionRuleForUpdatePermissionRuleInput {

    /**
     * @type {string}
     * @memberof PermissionRuleForUpdatePermissionRuleInput
     */
    CidrIp?: string;

    /**
     * @type {string}
     * @memberof PermissionRuleForUpdatePermissionRuleInput
     */
    PermissionRuleId?: string;

    /**
     * @type {string}
     * @memberof PermissionRuleForUpdatePermissionRuleInput
     */
    RwMode?: PermissionRuleForUpdatePermissionRuleInputRwModeEnum;

    /**
     * @type {string}
     * @memberof PermissionRuleForUpdatePermissionRuleInput
     */
    UserMode?: PermissionRuleForUpdatePermissionRuleInputUserModeEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum PermissionRuleForUpdatePermissionRuleInputRwModeEnum {
    RW = 'RW',
    RO = 'RO'
}
/**
 * @export
 * @enum {string}
 */
export enum PermissionRuleForUpdatePermissionRuleInputUserModeEnum {
    AllSquash = 'All_squash',
    NoAllSquash = 'No_all_squash',
    RootSquash = 'Root_squash',
    NoRootSquash = 'No_root_squash'
}

