/* tslint:disable */
/* eslint-disable */
/**
 * certificate_service
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface IssuerForCertificateGetInstanceOutput
 */
export interface IssuerForCertificateGetInstanceOutput {

    /**
     * @type {string}
     * @memberof IssuerForCertificateGetInstanceOutput
     */
    Address?: string;

    /**
     * @type {string}
     * @memberof IssuerForCertificateGetInstanceOutput
     */
    CommonName?: string;

    /**
     * @type {string}
     * @memberof IssuerForCertificateGetInstanceOutput
     */
    Country?: string;

    /**
     * @type {string}
     * @memberof IssuerForCertificateGetInstanceOutput
     */
    Locality?: string;

    /**
     * @type {string}
     * @memberof IssuerForCertificateGetInstanceOutput
     */
    Organization?: string;

    /**
     * @type {string}
     * @memberof IssuerForCertificateGetInstanceOutput
     */
    OrganizationUnit?: string;

    /**
     * @type {string}
     * @memberof IssuerForCertificateGetInstanceOutput
     */
    PostalCode?: string;

    /**
     * @type {string}
     * @memberof IssuerForCertificateGetInstanceOutput
     */
    Province?: string;
}
