/* tslint:disable */
/* eslint-disable */
/**
 * cloud_detect20251031
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface TcpConfigForCreateTaskInput
 */
export interface TcpConfigForCreateTaskInput {

    /**
     * @type {string}
     * @memberof TcpConfigForCreateTaskInput
     */
    Payload?: string;

    /**
     * @type {number}
     * @memberof TcpConfigForCreateTaskInput
     */
    PayloadType?: number;

    /**
     * @type {number}
     * @memberof TcpConfigForCreateTaskInput
     */
    Timeout?: number;
}
