/* tslint:disable */
/* eslint-disable */
/**
 * acep
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface CreateDisplayLayoutMiniResponse
 */
export interface CreateDisplayLayoutMiniResponse {

    /**
     * @type {number}
     * @memberof CreateDisplayLayoutMiniResponse
     */
    CreateAt?: number;

    /**
     * @type {number}
     * @memberof CreateDisplayLayoutMiniResponse
     */
    Density?: number;

    /**
     * @type {string}
     * @memberof CreateDisplayLayoutMiniResponse
     */
    DisplayLayoutId?: string;

    /**
     * @type {string}
     * @memberof CreateDisplayLayoutMiniResponse
     */
    Extra?: string;

    /**
     * @type {number}
     * @memberof CreateDisplayLayoutMiniResponse
     */
    Fps?: number;

    /**
     * @type {number}
     * @memberof CreateDisplayLayoutMiniResponse
     */
    Height?: number;

    /**
     * @type {boolean}
     * @memberof CreateDisplayLayoutMiniResponse
     */
    IsSystemConfig?: boolean;

    /**
     * @type {number}
     * @memberof CreateDisplayLayoutMiniResponse
     */
    Width?: number;
}
