/* tslint:disable */
/* eslint-disable */
/**
 * acep
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface DeleteBackupDataRequest
 */
export interface DeleteBackupDataRequest {

    /**
     * @type {Array<string>}
     * @memberof DeleteBackupDataRequest
     */
    BackupDataIdList?: Array<string>;

    /**
     * @type {string}
     * @memberof DeleteBackupDataRequest
     */
    ProductId: string;
}
