/* tslint:disable */
/* eslint-disable */
/**
 * acep
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { PhoneTemplateForGetPhoneTemplateOutput } from './phone-template-for-get-phone-template-output';
import { TagForGetPhoneTemplateOutput } from './tag-for-get-phone-template-output';
 /**
 * 
 *
 * @export
 * @interface GetPhoneTemplateResponse
 */
export interface GetPhoneTemplateResponse {

    /**
     * @type {PhoneTemplateForGetPhoneTemplateOutput}
     * @memberof GetPhoneTemplateResponse
     */
    PhoneTemplate?: PhoneTemplateForGetPhoneTemplateOutput;

    /**
     * @type {Array<TagForGetPhoneTemplateOutput>}
     * @memberof GetPhoneTemplateResponse
     */
    Tags?: Array<TagForGetPhoneTemplateOutput>;
}
