/* tslint:disable */
/* eslint-disable */
/**
 * acep
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { RowForListAOSPImageOutput } from './row-for-list-aospimage-output';
 /**
 * 
 *
 * @export
 * @interface ListAOSPImageResponse
 */
export interface ListAOSPImageResponse {

    /**
     * @type {string}
     * @memberof ListAOSPImageResponse
     */
    NextToken?: string;

    /**
     * @type {Array<RowForListAOSPImageOutput>}
     * @memberof ListAOSPImageResponse
     */
    Row?: Array<RowForListAOSPImageOutput>;
}
