/* tslint:disable */
/* eslint-disable */
/**
 * acep
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ProxyConfigForSetProxyInput } from './proxy-config-for-set-proxy-input';
 /**
 * 
 *
 * @export
 * @interface SetProxyRequest
 */
export interface SetProxyRequest {

    /**
     * @type {Array<string>}
     * @memberof SetProxyRequest
     */
    PodIdList?: Array<string>;

    /**
     * @type {string}
     * @memberof SetProxyRequest
     */
    ProductId: string;

    /**
     * @type {ProxyConfigForSetProxyInput}
     * @memberof SetProxyRequest
     */
    ProxyConfig?: ProxyConfigForSetProxyInput;

    /**
     * @type {number}
     * @memberof SetProxyRequest
     */
    ProxyStatus: number;
}
