/* tslint:disable */
/* eslint-disable */
/**
 * natgateway
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface SnatEntryForDescribeSnatEntriesOutput
 */
export interface SnatEntryForDescribeSnatEntriesOutput {

    /**
     * @type {string}
     * @memberof SnatEntryForDescribeSnatEntriesOutput
     */
    EipAddress?: string;

    /**
     * @type {string}
     * @memberof SnatEntryForDescribeSnatEntriesOutput
     */
    EipId?: string;

    /**
     * @type {string}
     * @memberof SnatEntryForDescribeSnatEntriesOutput
     */
    NatGatewayId?: string;

    /**
     * @type {string}
     * @memberof SnatEntryForDescribeSnatEntriesOutput
     */
    NatIpId?: string;

    /**
     * @type {string}
     * @memberof SnatEntryForDescribeSnatEntriesOutput
     */
    SnatEntryId?: string;

    /**
     * @type {string}
     * @memberof SnatEntryForDescribeSnatEntriesOutput
     */
    SnatEntryName?: string;

    /**
     * @type {string}
     * @memberof SnatEntryForDescribeSnatEntriesOutput
     */
    SourceCidr?: string;

    /**
     * @type {string}
     * @memberof SnatEntryForDescribeSnatEntriesOutput
     */
    Status?: string;

    /**
     * @type {string}
     * @memberof SnatEntryForDescribeSnatEntriesOutput
     */
    SubnetId?: string;
}
