/* tslint:disable */
/* eslint-disable */
/**
 * iam
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { UserForListUsersForGroupOutput } from './user-for-list-users-for-group-output';
 /**
 * 
 *
 * @export
 * @interface ListUsersForGroupResponse
 */
export interface ListUsersForGroupResponse {

    /**
     * @type {number}
     * @memberof ListUsersForGroupResponse
     */
    Limit?: number;

    /**
     * @type {number}
     * @memberof ListUsersForGroupResponse
     */
    Offset?: number;

    /**
     * @type {number}
     * @memberof ListUsersForGroupResponse
     */
    Total?: number;

    /**
     * @type {Array<UserForListUsersForGroupOutput>}
     * @memberof ListUsersForGroupResponse
     */
    Users?: Array<UserForListUsersForGroupOutput>;
}
