/* tslint:disable */
/* eslint-disable */
/**
 * iam
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface UpdateOAuthProviderRequest
 */
export interface UpdateOAuthProviderRequest {

    /**
     * @type {string}
     * @memberof UpdateOAuthProviderRequest
     */
    AuthorizeTemplate?: string;

    /**
     * @type {string}
     * @memberof UpdateOAuthProviderRequest
     */
    AuthorizeURL?: string;

    /**
     * @type {string}
     * @memberof UpdateOAuthProviderRequest
     */
    ClientId?: string;

    /**
     * @type {string}
     * @memberof UpdateOAuthProviderRequest
     */
    ClientSecret?: string;

    /**
     * @type {string}
     * @memberof UpdateOAuthProviderRequest
     */
    Description?: string;

    /**
     * @type {number}
     * @memberof UpdateOAuthProviderRequest
     */
    IdentityMapType?: number;

    /**
     * @type {string}
     * @memberof UpdateOAuthProviderRequest
     */
    IdpIdentityKey?: string;

    /**
     * @type {string}
     * @memberof UpdateOAuthProviderRequest
     */
    OAuthProviderName: string;

    /**
     * @type {string}
     * @memberof UpdateOAuthProviderRequest
     */
    Scope?: string;

    /**
     * @type {number}
     * @memberof UpdateOAuthProviderRequest
     */
    Status?: number;

    /**
     * @type {string}
     * @memberof UpdateOAuthProviderRequest
     */
    TokenURL?: string;

    /**
     * @type {string}
     * @memberof UpdateOAuthProviderRequest
     */
    UserInfoURL?: string;
}
