/* tslint:disable */
/* eslint-disable */
/**
 * iam
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface UpdateRoleRequest
 */
export interface UpdateRoleRequest {

    /**
     * @type {string}
     * @memberof UpdateRoleRequest
     */
    Description?: string;

    /**
     * @type {string}
     * @memberof UpdateRoleRequest
     */
    DisplayName?: string;

    /**
     * @type {number}
     * @memberof UpdateRoleRequest
     */
    MaxSessionDuration?: number;

    /**
     * @type {string}
     * @memberof UpdateRoleRequest
     */
    NewRoleName?: string;

    /**
     * @type {string}
     * @memberof UpdateRoleRequest
     */
    RoleName: string;

    /**
     * @type {string}
     * @memberof UpdateRoleRequest
     */
    TrustPolicyDocument?: string;
}
