/* tslint:disable */
/* eslint-disable */
/**
 * iam
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface UpdateUserRequest
 */
export interface UpdateUserRequest {

    /**
     * @type {string}
     * @memberof UpdateUserRequest
     */
    NewDescription?: string;

    /**
     * @type {string}
     * @memberof UpdateUserRequest
     */
    NewDisplayName?: string;

    /**
     * @type {string}
     * @memberof UpdateUserRequest
     */
    NewEmail?: string;

    /**
     * @type {string}
     * @memberof UpdateUserRequest
     */
    NewMobilePhone?: string;

    /**
     * @type {string}
     * @memberof UpdateUserRequest
     */
    NewUserName?: string;

    /**
     * @type {string}
     * @memberof UpdateUserRequest
     */
    UserName: string;
}
