/* tslint:disable */
/* eslint-disable */
/**
 * vod20250101
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { CanvasForStartExecutionInput } from './canvas-for-start-execution-input';
import { OutputForStartExecutionInput } from './output-for-start-execution-input';
 /**
 * 
 *
 * @export
 * @interface CustomEditForStartExecutionInput
 */
export interface CustomEditForStartExecutionInput {

    /**
     * @type {CanvasForStartExecutionInput}
     * @memberof CustomEditForStartExecutionInput
     */
    Canvas?: CanvasForStartExecutionInput;

    /**
     * @type {OutputForStartExecutionInput}
     * @memberof CustomEditForStartExecutionInput
     */
    Output?: OutputForStartExecutionInput;
}
