/* tslint:disable */
/* eslint-disable */
/**
 * vod20250101
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ListAITranslationProjectRequest
 */
export interface ListAITranslationProjectRequest {

    /**
     * @type {number}
     * @memberof ListAITranslationProjectRequest
     */
    PageNumber?: number;

    /**
     * @type {string}
     * @memberof ListAITranslationProjectRequest
     */
    PageSize?: string;

    /**
     * @type {string}
     * @memberof ListAITranslationProjectRequest
     */
    ProjectIdOrTitleFilter?: string;

    /**
     * @type {string}
     * @memberof ListAITranslationProjectRequest
     */
    SpaceName: string;

    /**
     * @type {string}
     * @memberof ListAITranslationProjectRequest
     */
    StatusFilter?: string;
}
