/* tslint:disable */
/* eslint-disable */
/**
 * vod20250101
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ListAITranslationSpeechRequest
 */
export interface ListAITranslationSpeechRequest {

    /**
     * @type {string}
     * @memberof ListAITranslationSpeechRequest
     */
    Language: string;

    /**
     * @type {string}
     * @memberof ListAITranslationSpeechRequest
     */
    SpaceName: string;

    /**
     * @type {string}
     * @memberof ListAITranslationSpeechRequest
     */
    SpeechTypeFilter: string;
}
