/* tslint:disable */
/* eslint-disable */
/**
 * vod20250101
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { DirectUrlForGetExecutionOutput } from './direct-url-for-get-execution-output';
import { FileIdForGetExecutionOutput } from './file-id-for-get-execution-output';
 /**
 * 
 *
 * @export
 * @interface MultiInputForGetExecutionOutput
 */
export interface MultiInputForGetExecutionOutput {

    /**
     * @type {DirectUrlForGetExecutionOutput}
     * @memberof MultiInputForGetExecutionOutput
     */
    DirectUrl?: DirectUrlForGetExecutionOutput;

    /**
     * @type {FileIdForGetExecutionOutput}
     * @memberof MultiInputForGetExecutionOutput
     */
    FileId?: FileIdForGetExecutionOutput;

    /**
     * @type {string}
     * @memberof MultiInputForGetExecutionOutput
     */
    Schema?: string;

    /**
     * @type {string}
     * @memberof MultiInputForGetExecutionOutput
     */
    Tag?: string;

    /**
     * @type {string}
     * @memberof MultiInputForGetExecutionOutput
     */
    Type?: string;

    /**
     * @type {string}
     * @memberof MultiInputForGetExecutionOutput
     */
    Vid?: string;
}
