/* tslint:disable */
/* eslint-disable */
/**
 * vod20250101
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AreaForStartExecutionInput } from './area-for-start-execution-input';
 /**
 * 
 *
 * @export
 * @interface SnapshotParamForStartExecutionInput
 */
export interface SnapshotParamForStartExecutionInput {

    /**
     * @type {AreaForStartExecutionInput}
     * @memberof SnapshotParamForStartExecutionInput
     */
    Area?: AreaForStartExecutionInput;

    /**
     * @type {number}
     * @memberof SnapshotParamForStartExecutionInput
     */
    Fps?: number;

    /**
     * @type {string}
     * @memberof SnapshotParamForStartExecutionInput
     */
    Resolution?: string;
}
