/* tslint:disable */
/* eslint-disable */
/**
 * vod20250101
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface SpeechForUpdateAITranslationSpeechesInput
 */
export interface SpeechForUpdateAITranslationSpeechesInput {

    /**
     * @type {string}
     * @memberof SpeechForUpdateAITranslationSpeechesInput
     */
    Id?: string;

    /**
     * @type {string}
     * @memberof SpeechForUpdateAITranslationSpeechesInput
     */
    SpeechName?: string;
}
