/* tslint:disable */
/* eslint-disable */
/**
 * ga
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface AcceleratorReplacePublicBandwidthPackageRequest
 */
export interface AcceleratorReplacePublicBandwidthPackageRequest {

    /**
     * @type {string}
     * @memberof AcceleratorReplacePublicBandwidthPackageRequest
     */
    AcceleratorId: string;

    /**
     * @type {string}
     * @memberof AcceleratorReplacePublicBandwidthPackageRequest
     */
    BandwidthPackageId: string;
}
