/* tslint:disable */
/* eslint-disable */
/**
 * ga
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ResourceTagForListAcceleratorsOutput } from './resource-tag-for-list-accelerators-output';
 /**
 * 
 *
 * @export
 * @interface AcceleratorForListAcceleratorsOutput
 */
export interface AcceleratorForListAcceleratorsOutput {

    /**
     * @type {string}
     * @memberof AcceleratorForListAcceleratorsOutput
     */
    AcceleratorId?: string;

    /**
     * @type {string}
     * @memberof AcceleratorForListAcceleratorsOutput
     */
    AccountID?: string;

    /**
     * @type {Array<string>}
     * @memberof AcceleratorForListAcceleratorsOutput
     */
    BandwidthPackageIds?: Array<string>;

    /**
     * @type {string}
     * @memberof AcceleratorForListAcceleratorsOutput
     */
    BillingSpec?: string;

    /**
     * @type {number}
     * @memberof AcceleratorForListAcceleratorsOutput
     */
    BillingSpecEffectiveTime?: number;

    /**
     * @type {string}
     * @memberof AcceleratorForListAcceleratorsOutput
     */
    BillingType?: string;

    /**
     * @type {string}
     * @memberof AcceleratorForListAcceleratorsOutput
     */
    CNAME?: string;

    /**
     * @type {string}
     * @memberof AcceleratorForListAcceleratorsOutput
     */
    ChargeType?: string;

    /**
     * @type {number}
     * @memberof AcceleratorForListAcceleratorsOutput
     */
    CreateTime?: number;

    /**
     * @type {string}
     * @memberof AcceleratorForListAcceleratorsOutput
     */
    CreateTimeStr?: string;

    /**
     * @type {Array<string>}
     * @memberof AcceleratorForListAcceleratorsOutput
     */
    CrossDomainBandwidthIds?: Array<string>;

    /**
     * @type {number}
     * @memberof AcceleratorForListAcceleratorsOutput
     */
    ExpiredTime?: number;

    /**
     * @type {boolean}
     * @memberof AcceleratorForListAcceleratorsOutput
     */
    FullPortSwitch?: boolean;

    /**
     * @type {number}
     * @memberof AcceleratorForListAcceleratorsOutput
     */
    ListenerCount?: number;

    /**
     * @type {string}
     * @memberof AcceleratorForListAcceleratorsOutput
     */
    Name?: string;

    /**
     * @type {string}
     * @memberof AcceleratorForListAcceleratorsOutput
     */
    ProjectName?: string;

    /**
     * @type {number}
     * @memberof AcceleratorForListAcceleratorsOutput
     */
    RegionCount?: number;

    /**
     * @type {number}
     * @memberof AcceleratorForListAcceleratorsOutput
     */
    RenewType?: number;

    /**
     * @type {Array<ResourceTagForListAcceleratorsOutput>}
     * @memberof AcceleratorForListAcceleratorsOutput
     */
    ResourceTags?: Array<ResourceTagForListAcceleratorsOutput>;

    /**
     * @type {string}
     * @memberof AcceleratorForListAcceleratorsOutput
     */
    State?: string;
}
