/* tslint:disable */
/* eslint-disable */
/**
 * ga
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { BackupEndpointGroupForCreateListenerInOneStepInput } from './backup-endpoint-group-for-create-listener-in-one-step-input';
import { EndpointGroupForCreateListenerInOneStepInput } from './endpoint-group-for-create-listener-in-one-step-input';
import { FixedSourceReturnForCreateListenerInOneStepInput } from './fixed-source-return-for-create-listener-in-one-step-input';
import { IPAccessForCreateListenerInOneStepInput } from './ipaccess-for-create-listener-in-one-step-input';
import { PortRangeForCreateListenerInOneStepInput } from './port-range-for-create-listener-in-one-step-input';
 /**
 * 
 *
 * @export
 * @interface CreateListenerInOneStepRequest
 */
export interface CreateListenerInOneStepRequest {

    /**
     * @type {string}
     * @memberof CreateListenerInOneStepRequest
     */
    AcceleratorId: string;

    /**
     * @type {Array<BackupEndpointGroupForCreateListenerInOneStepInput>}
     * @memberof CreateListenerInOneStepRequest
     */
    BackupEndpointGroups?: Array<BackupEndpointGroupForCreateListenerInOneStepInput>;

    /**
     * @type {boolean}
     * @memberof CreateListenerInOneStepRequest
     */
    DisableIsolateTCPNullConn?: boolean;

    /**
     * @type {boolean}
     * @memberof CreateListenerInOneStepRequest
     */
    DisablePreConnect?: boolean;

    /**
     * @type {boolean}
     * @memberof CreateListenerInOneStepRequest
     */
    EnableAffinity: boolean;

    /**
     * @type {Array<EndpointGroupForCreateListenerInOneStepInput>}
     * @memberof CreateListenerInOneStepRequest
     */
    EndpointGroups?: Array<EndpointGroupForCreateListenerInOneStepInput>;

    /**
     * @type {FixedSourceReturnForCreateListenerInOneStepInput}
     * @memberof CreateListenerInOneStepRequest
     */
    FixedSourceReturn?: FixedSourceReturnForCreateListenerInOneStepInput;

    /**
     * @type {IPAccessForCreateListenerInOneStepInput}
     * @memberof CreateListenerInOneStepRequest
     */
    IPAccess?: IPAccessForCreateListenerInOneStepInput;

    /**
     * @type {string}
     * @memberof CreateListenerInOneStepRequest
     */
    Name?: string;

    /**
     * @type {Array<PortRangeForCreateListenerInOneStepInput>}
     * @memberof CreateListenerInOneStepRequest
     */
    PortRanges?: Array<PortRangeForCreateListenerInOneStepInput>;

    /**
     * @type {string}
     * @memberof CreateListenerInOneStepRequest
     */
    Protocol: string;
}
