/* tslint:disable */
/* eslint-disable */
/**
 * ga
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { PublicBandwidthPackageForDescribePublicBandwidthPackageOutput } from './public-bandwidth-package-for-describe-public-bandwidth-package-output';
 /**
 * 
 *
 * @export
 * @interface DescribePublicBandwidthPackageResponse
 */
export interface DescribePublicBandwidthPackageResponse {

    /**
     * @type {PublicBandwidthPackageForDescribePublicBandwidthPackageOutput}
     * @memberof DescribePublicBandwidthPackageResponse
     */
    PublicBandwidthPackage?: PublicBandwidthPackageForDescribePublicBandwidthPackageOutput;
}
