/* tslint:disable */
/* eslint-disable */
/**
 * ga
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface RenewAcceleratorRequest
 */
export interface RenewAcceleratorRequest {

    /**
     * @type {string}
     * @memberof RenewAcceleratorRequest
     */
    AcceleratorId: string;

    /**
     * @type {number}
     * @memberof RenewAcceleratorRequest
     */
    Duration: number;

    /**
     * @type {number}
     * @memberof RenewAcceleratorRequest
     */
    RenewType?: number;
}
