/* tslint:disable */
/* eslint-disable */
/**
 * mongodb
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AccountForDescribeDBAccountsOutput } from './account-for-describe-dbaccounts-output';
 /**
 * 
 *
 * @export
 * @interface DescribeDBAccountsResponse
 */
export interface DescribeDBAccountsResponse {

    /**
     * @type {Array<AccountForDescribeDBAccountsOutput>}
     * @memberof DescribeDBAccountsResponse
     */
    Accounts?: Array<AccountForDescribeDBAccountsOutput>;

    /**
     * @type {number}
     * @memberof DescribeDBAccountsResponse
     */
    Total?: number;
}
