/* tslint:disable */
/* eslint-disable */
/**
 * mongodb
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ModifyDBInstanceChargeTypeRequest
 */
export interface ModifyDBInstanceChargeTypeRequest {

    /**
     * @type {boolean}
     * @memberof ModifyDBInstanceChargeTypeRequest
     */
    AutoRenew?: boolean;

    /**
     * @type {string}
     * @memberof ModifyDBInstanceChargeTypeRequest
     */
    ChargeType: ModifyDBInstanceChargeTypeRequestChargeTypeEnum;

    /**
     * @type {Array<string>}
     * @memberof ModifyDBInstanceChargeTypeRequest
     */
    InstanceIds?: Array<string>;

    /**
     * @type {number}
     * @memberof ModifyDBInstanceChargeTypeRequest
     */
    Period?: number;

    /**
     * @type {string}
     * @memberof ModifyDBInstanceChargeTypeRequest
     */
    PeriodUnit?: ModifyDBInstanceChargeTypeRequestPeriodUnitEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum ModifyDBInstanceChargeTypeRequestChargeTypeEnum {
    NotEnabled = 'NotEnabled',
    PostPaid = 'PostPaid',
    Prepaid = 'Prepaid'
}
/**
 * @export
 * @enum {string}
 */
export enum ModifyDBInstanceChargeTypeRequestPeriodUnitEnum {
    Year = 'Year',
    Month = 'Month'
}

