/* tslint:disable */
/* eslint-disable */
/**
 * private_zone
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface IpConfigForCreateResolverEndpointInput
 */
export interface IpConfigForCreateResolverEndpointInput {

    /**
     * @type {string}
     * @memberof IpConfigForCreateResolverEndpointInput
     */
    AzID?: string;

    /**
     * @type {string}
     * @memberof IpConfigForCreateResolverEndpointInput
     */
    IP?: string;

    /**
     * @type {string}
     * @memberof IpConfigForCreateResolverEndpointInput
     */
    IPv6?: string;

    /**
     * @type {string}
     * @memberof IpConfigForCreateResolverEndpointInput
     */
    SubnetID?: string;
}
