/* tslint:disable */
/* eslint-disable */
/**
 * vke
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { RegistryProxyConfigForCreateNodePoolInput } from './registry-proxy-config-for-create-node-pool-input';
 /**
 * 
 *
 * @export
 * @interface ContainerdConfigForCreateNodePoolInput
 */
export interface ContainerdConfigForCreateNodePoolInput {

    /**
     * @type {Array<string>}
     * @memberof ContainerdConfigForCreateNodePoolInput
     */
    InsecureRegistries?: Array<string>;

    /**
     * @type {Array<RegistryProxyConfigForCreateNodePoolInput>}
     * @memberof ContainerdConfigForCreateNodePoolInput
     */
    RegistryProxyConfigs?: Array<RegistryProxyConfigForCreateNodePoolInput>;
}
