/* tslint:disable */
/* eslint-disable */
/**
 * vke
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface CreateAddonRequest
 */
export interface CreateAddonRequest {

    /**
     * @type {string}
     * @memberof CreateAddonRequest
     */
    ClientToken?: string;

    /**
     * @type {string}
     * @memberof CreateAddonRequest
     */
    ClusterId: string;

    /**
     * @type {string}
     * @memberof CreateAddonRequest
     */
    Config?: string;

    /**
     * @type {string}
     * @memberof CreateAddonRequest
     */
    DeployMode?: CreateAddonRequestDeployModeEnum;

    /**
     * @type {string}
     * @memberof CreateAddonRequest
     */
    DeployNodeType?: CreateAddonRequestDeployNodeTypeEnum;

    /**
     * @type {string}
     * @memberof CreateAddonRequest
     */
    Name: string;

    /**
     * @type {string}
     * @memberof CreateAddonRequest
     */
    Version?: string;
}

/**
 * @export
 * @enum {string}
 */
export enum CreateAddonRequestDeployModeEnum {
    Managed = 'Managed',
    Unmanaged = 'Unmanaged'
}
/**
 * @export
 * @enum {string}
 */
export enum CreateAddonRequestDeployNodeTypeEnum {
    Node = 'Node',
    VirtualNode = 'VirtualNode',
    EdgeNode = 'EdgeNode'
}

