/* tslint:disable */
/* eslint-disable */
/**
 * vke
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { LabelForCreateNodesInput } from './label-for-create-nodes-input';
import { TaintForCreateNodesInput } from './taint-for-create-nodes-input';
 /**
 * 
 *
 * @export
 * @interface KubernetesConfigForCreateNodesInput
 */
export interface KubernetesConfigForCreateNodesInput {

    /**
     * @type {boolean}
     * @memberof KubernetesConfigForCreateNodesInput
     */
    Cordon?: boolean;

    /**
     * @type {Array<LabelForCreateNodesInput>}
     * @memberof KubernetesConfigForCreateNodesInput
     */
    Labels?: Array<LabelForCreateNodesInput>;

    /**
     * @type {Array<TaintForCreateNodesInput>}
     * @memberof KubernetesConfigForCreateNodesInput
     */
    Taints?: Array<TaintForCreateNodesInput>;
}
