/* tslint:disable */
/* eslint-disable */
/**
 * vke
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { EvictionHardForListNodePoolsOutput } from './eviction-hard-for-list-node-pools-output';
import { FeatureGatesForListNodePoolsOutput } from './feature-gates-for-list-node-pools-output';
import { KubeReservedForListNodePoolsOutput } from './kube-reserved-for-list-node-pools-output';
import { SystemReservedForListNodePoolsOutput } from './system-reserved-for-list-node-pools-output';
 /**
 * 
 *
 * @export
 * @interface KubeletConfigForListNodePoolsOutput
 */
export interface KubeletConfigForListNodePoolsOutput {

    /**
     * @type {string}
     * @memberof KubeletConfigForListNodePoolsOutput
     */
    CpuManagerPolicy?: KubeletConfigForListNodePoolsOutputCpuManagerPolicyEnum;

    /**
     * @type {Array<EvictionHardForListNodePoolsOutput>}
     * @memberof KubeletConfigForListNodePoolsOutput
     */
    EvictionHard?: Array<EvictionHardForListNodePoolsOutput>;

    /**
     * @type {FeatureGatesForListNodePoolsOutput}
     * @memberof KubeletConfigForListNodePoolsOutput
     */
    FeatureGates?: FeatureGatesForListNodePoolsOutput;

    /**
     * @type {number}
     * @memberof KubeletConfigForListNodePoolsOutput
     */
    KubeApiBurst?: number;

    /**
     * @type {number}
     * @memberof KubeletConfigForListNodePoolsOutput
     */
    KubeApiQps?: number;

    /**
     * @type {Array<KubeReservedForListNodePoolsOutput>}
     * @memberof KubeletConfigForListNodePoolsOutput
     */
    KubeReserved?: Array<KubeReservedForListNodePoolsOutput>;

    /**
     * @type {number}
     * @memberof KubeletConfigForListNodePoolsOutput
     */
    MaxPods?: number;

    /**
     * @type {number}
     * @memberof KubeletConfigForListNodePoolsOutput
     */
    RegistryBurst?: number;

    /**
     * @type {number}
     * @memberof KubeletConfigForListNodePoolsOutput
     */
    RegistryPullQps?: number;

    /**
     * @type {boolean}
     * @memberof KubeletConfigForListNodePoolsOutput
     */
    SerializeImagePulls?: boolean;

    /**
     * @type {Array<SystemReservedForListNodePoolsOutput>}
     * @memberof KubeletConfigForListNodePoolsOutput
     */
    SystemReserved?: Array<SystemReservedForListNodePoolsOutput>;

    /**
     * @type {string}
     * @memberof KubeletConfigForListNodePoolsOutput
     */
    TopologyManagerPolicy?: KubeletConfigForListNodePoolsOutputTopologyManagerPolicyEnum;

    /**
     * @type {string}
     * @memberof KubeletConfigForListNodePoolsOutput
     */
    TopologyManagerScope?: KubeletConfigForListNodePoolsOutputTopologyManagerScopeEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum KubeletConfigForListNodePoolsOutputCpuManagerPolicyEnum {
    None = 'none',
    Static = 'static'
}
/**
 * @export
 * @enum {string}
 */
export enum KubeletConfigForListNodePoolsOutputTopologyManagerPolicyEnum {
    Restricted = 'restricted',
    BestEffort = 'best-effort',
    None = 'none',
    SingleNumaNode = 'single-numa-node'
}
/**
 * @export
 * @enum {string}
 */
export enum KubeletConfigForListNodePoolsOutputTopologyManagerScopeEnum {
    Pod = 'pod',
    Container = 'container'
}

