/* tslint:disable */
/* eslint-disable */
/**
 * vke
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ItemForListClustersOutput } from './item-for-list-clusters-output';
 /**
 * 
 *
 * @export
 * @interface ListClustersResponse
 */
export interface ListClustersResponse {

    /**
     * @type {Array<ItemForListClustersOutput>}
     * @memberof ListClustersResponse
     */
    Items?: Array<ItemForListClustersOutput>;

    /**
     * @type {number}
     * @memberof ListClustersResponse
     */
    PageNumber?: number;

    /**
     * @type {number}
     * @memberof ListClustersResponse
     */
    PageSize?: number;

    /**
     * @type {number}
     * @memberof ListClustersResponse
     */
    TotalCount?: number;
}
