/* tslint:disable */
/* eslint-disable */
/**
 * vke
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ConditionForListClustersOutput } from './condition-for-list-clusters-output';
 /**
 * 
 *
 * @export
 * @interface StatusForListClustersOutput
 */
export interface StatusForListClustersOutput {

    /**
     * @type {Array<ConditionForListClustersOutput>}
     * @memberof StatusForListClustersOutput
     */
    Conditions?: Array<ConditionForListClustersOutput>;

    /**
     * @type {string}
     * @memberof StatusForListClustersOutput
     */
    Phase?: StatusForListClustersOutputPhaseEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum StatusForListClustersOutputPhaseEnum {
    Running = 'Running',
    Starting = 'Starting',
    Stopped = 'Stopped',
    Failed = 'Failed',
    Updating = 'Updating',
    Creating = 'Creating',
    Deleting = 'Deleting'
}

