/* tslint:disable */
/* eslint-disable */
/**
 * vke
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface TaintForCreateNodePoolInput
 */
export interface TaintForCreateNodePoolInput {

    /**
     * @type {string}
     * @memberof TaintForCreateNodePoolInput
     */
    Effect?: TaintForCreateNodePoolInputEffectEnum;

    /**
     * @type {string}
     * @memberof TaintForCreateNodePoolInput
     */
    Key?: string;

    /**
     * @type {string}
     * @memberof TaintForCreateNodePoolInput
     */
    Value?: string;
}

/**
 * @export
 * @enum {string}
 */
export enum TaintForCreateNodePoolInputEffectEnum {
    NoSchedule = 'NoSchedule',
    PreferNoSchedule = 'PreferNoSchedule',
    NoExecute = 'NoExecute'
}

