/* tslint:disable */
/* eslint-disable */
/**
 * vke
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { CompatibilityForListSupportedAddonsOutput } from './compatibility-for-list-supported-addons-output';
 /**
 * 
 *
 * @export
 * @interface VersionForListSupportedAddonsOutput
 */
export interface VersionForListSupportedAddonsOutput {

    /**
     * @type {Array<CompatibilityForListSupportedAddonsOutput>}
     * @memberof VersionForListSupportedAddonsOutput
     */
    Compatibilities?: Array<CompatibilityForListSupportedAddonsOutput>;

    /**
     * @type {Array<string>}
     * @memberof VersionForListSupportedAddonsOutput
     */
    CompatibleVersions?: Array<string>;

    /**
     * @type {string}
     * @memberof VersionForListSupportedAddonsOutput
     */
    Version?: string;
}
