/* tslint:disable */
/* eslint-disable */
/**
 * vefaas_dev
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ErrorForWriteFilesOutput
 */
export interface ErrorForWriteFilesOutput {

    /**
     * @type {string}
     * @memberof ErrorForWriteFilesOutput
     */
    Error?: string;

    /**
     * @type {string}
     * @memberof ErrorForWriteFilesOutput
     */
    Path?: string;
}
