/* tslint:disable */
/* eslint-disable */
/**
 * vefaas_dev
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ItemForListFunctionsOutput } from './item-for-list-functions-output';
 /**
 * 
 *
 * @export
 * @interface ListFunctionsResponse
 */
export interface ListFunctionsResponse {

    /**
     * @type {Array<ItemForListFunctionsOutput>}
     * @memberof ListFunctionsResponse
     */
    Items?: Array<ItemForListFunctionsOutput>;

    /**
     * @type {number}
     * @memberof ListFunctionsResponse
     */
    Total?: number;
}
