/* tslint:disable */
/* eslint-disable */
/**
 * vefaas_dev
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { FilterForListRevisionsInput } from './filter-for-list-revisions-input';
 /**
 * 
 *
 * @export
 * @interface ListRevisionsRequest
 */
export interface ListRevisionsRequest {

    /**
     * @type {Array<FilterForListRevisionsInput>}
     * @memberof ListRevisionsRequest
     */
    Filters?: Array<FilterForListRevisionsInput>;

    /**
     * @type {string}
     * @memberof ListRevisionsRequest
     */
    FunctionId: string;

    /**
     * @type {number}
     * @memberof ListRevisionsRequest
     */
    PageNumber?: number;

    /**
     * @type {number}
     * @memberof ListRevisionsRequest
     */
    PageSize?: number;
}
