/* tslint:disable */
/* eslint-disable */
/**
 * vefaas_dev
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface NasConfigForListRevisionsOutput
 */
export interface NasConfigForListRevisionsOutput {

    /**
     * @type {string}
     * @memberof NasConfigForListRevisionsOutput
     */
    FileSystemId?: string;

    /**
     * @type {number}
     * @memberof NasConfigForListRevisionsOutput
     */
    Gid?: number;

    /**
     * @type {string}
     * @memberof NasConfigForListRevisionsOutput
     */
    LocalMountPath?: string;

    /**
     * @type {string}
     * @memberof NasConfigForListRevisionsOutput
     */
    MountPointId?: string;

    /**
     * @type {string}
     * @memberof NasConfigForListRevisionsOutput
     */
    RemotePath?: string;

    /**
     * @type {number}
     * @memberof NasConfigForListRevisionsOutput
     */
    Uid?: number;
}
