/* tslint:disable */
/* eslint-disable */
/**
 * vefaas
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { KafkaCredentialsForCreateKafkaTriggerInput } from './kafka-credentials-for-create-kafka-trigger-input';
 /**
 * 
 *
 * @export
 * @interface CreateKafkaTriggerRequest
 */
export interface CreateKafkaTriggerRequest {

    /**
     * @type {number}
     * @memberof CreateKafkaTriggerRequest
     */
    BatchFlushDurationMilliseconds?: number;

    /**
     * @type {number}
     * @memberof CreateKafkaTriggerRequest
     */
    BatchSize?: number;

    /**
     * @type {string}
     * @memberof CreateKafkaTriggerRequest
     */
    Description?: string;

    /**
     * @type {boolean}
     * @memberof CreateKafkaTriggerRequest
     */
    Enabled?: boolean;

    /**
     * @type {string}
     * @memberof CreateKafkaTriggerRequest
     */
    FunctionId: string;

    /**
     * @type {KafkaCredentialsForCreateKafkaTriggerInput}
     * @memberof CreateKafkaTriggerRequest
     */
    KafkaCredentials?: KafkaCredentialsForCreateKafkaTriggerInput;

    /**
     * @type {number}
     * @memberof CreateKafkaTriggerRequest
     */
    MaximumRetryAttempts?: number;

    /**
     * @type {string}
     * @memberof CreateKafkaTriggerRequest
     */
    MqInstanceId: string;

    /**
     * @type {string}
     * @memberof CreateKafkaTriggerRequest
     */
    Name: string;

    /**
     * @type {string}
     * @memberof CreateKafkaTriggerRequest
     */
    StartingPosition?: string;

    /**
     * @type {string}
     * @memberof CreateKafkaTriggerRequest
     */
    TopicName: string;
}
