/* tslint:disable */
/* eslint-disable */
/**
 * vefaas
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AsyncTaskConfigForUpdateFunctionInput } from './async-task-config-for-update-function-input';
import { EnvForUpdateFunctionInput } from './env-for-update-function-input';
import { NasStorageForUpdateFunctionInput } from './nas-storage-for-update-function-input';
import { SourceAccessConfigForUpdateFunctionInput } from './source-access-config-for-update-function-input';
import { TagForUpdateFunctionInput } from './tag-for-update-function-input';
import { TlsConfigForUpdateFunctionInput } from './tls-config-for-update-function-input';
import { TosMountConfigForUpdateFunctionInput } from './tos-mount-config-for-update-function-input';
import { VpcConfigForUpdateFunctionInput } from './vpc-config-for-update-function-input';
 /**
 * 
 *
 * @export
 * @interface UpdateFunctionRequest
 */
export interface UpdateFunctionRequest {

    /**
     * @type {AsyncTaskConfigForUpdateFunctionInput}
     * @memberof UpdateFunctionRequest
     */
    AsyncTaskConfig?: AsyncTaskConfigForUpdateFunctionInput;

    /**
     * @type {string}
     * @memberof UpdateFunctionRequest
     */
    Command?: string;

    /**
     * @type {number}
     * @memberof UpdateFunctionRequest
     */
    CpuMilli?: number;

    /**
     * @type {string}
     * @memberof UpdateFunctionRequest
     */
    Description?: string;

    /**
     * @type {boolean}
     * @memberof UpdateFunctionRequest
     */
    EnableApmplus?: boolean;

    /**
     * @type {Array<EnvForUpdateFunctionInput>}
     * @memberof UpdateFunctionRequest
     */
    Envs?: Array<EnvForUpdateFunctionInput>;

    /**
     * @type {boolean}
     * @memberof UpdateFunctionRequest
     */
    ExclusiveMode?: boolean;

    /**
     * @type {string}
     * @memberof UpdateFunctionRequest
     */
    Id: string;

    /**
     * @type {number}
     * @memberof UpdateFunctionRequest
     */
    InitializerSec?: number;

    /**
     * @type {number}
     * @memberof UpdateFunctionRequest
     */
    MaxConcurrency?: number;

    /**
     * @type {number}
     * @memberof UpdateFunctionRequest
     */
    MemoryMB?: number;

    /**
     * @type {NasStorageForUpdateFunctionInput}
     * @memberof UpdateFunctionRequest
     */
    NasStorage?: NasStorageForUpdateFunctionInput;

    /**
     * @type {number}
     * @memberof UpdateFunctionRequest
     */
    Port?: number;

    /**
     * @type {string}
     * @memberof UpdateFunctionRequest
     */
    ProjectName?: string;

    /**
     * @type {number}
     * @memberof UpdateFunctionRequest
     */
    RequestTimeout?: number;

    /**
     * @type {string}
     * @memberof UpdateFunctionRequest
     */
    Role?: string;

    /**
     * @type {string}
     * @memberof UpdateFunctionRequest
     */
    Source?: string;

    /**
     * @type {SourceAccessConfigForUpdateFunctionInput}
     * @memberof UpdateFunctionRequest
     */
    SourceAccessConfig?: SourceAccessConfigForUpdateFunctionInput;

    /**
     * @type {string}
     * @memberof UpdateFunctionRequest
     */
    SourceType?: string;

    /**
     * @type {Array<TagForUpdateFunctionInput>}
     * @memberof UpdateFunctionRequest
     */
    Tags?: Array<TagForUpdateFunctionInput>;

    /**
     * @type {TlsConfigForUpdateFunctionInput}
     * @memberof UpdateFunctionRequest
     */
    TlsConfig?: TlsConfigForUpdateFunctionInput;

    /**
     * @type {TosMountConfigForUpdateFunctionInput}
     * @memberof UpdateFunctionRequest
     */
    TosMountConfig?: TosMountConfigForUpdateFunctionInput;

    /**
     * @type {VpcConfigForUpdateFunctionInput}
     * @memberof UpdateFunctionRequest
     */
    VpcConfig?: VpcConfigForUpdateFunctionInput;
}
