/* tslint:disable */
/* eslint-disable */
/**
 * cv20240606
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface AlgorithmBaseRespForRealmanAvatarPictureSubmitTaskOutput
 */
export interface AlgorithmBaseRespForRealmanAvatarPictureSubmitTaskOutput {

    /**
     * @type {number}
     * @memberof AlgorithmBaseRespForRealmanAvatarPictureSubmitTaskOutput
     */
    status_code?: number;

    /**
     * @type {string}
     * @memberof AlgorithmBaseRespForRealmanAvatarPictureSubmitTaskOutput
     */
    status_message?: string;
}
