/* tslint:disable */
/* eslint-disable */
/**
 * cv20240606
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AlgorithmBaseRespForJimengT2IV30SubmitTaskOutput } from './algorithm-base-resp-for-jimeng-t2-iv30-submit-task-output';
 /**
 * 
 *
 * @export
 * @interface DataForJimengT2IV30SubmitTaskOutput
 */
export interface DataForJimengT2IV30SubmitTaskOutput {

    /**
     * @type {AlgorithmBaseRespForJimengT2IV30SubmitTaskOutput}
     * @memberof DataForJimengT2IV30SubmitTaskOutput
     */
    algorithm_base_resp?: AlgorithmBaseRespForJimengT2IV30SubmitTaskOutput;

    /**
     * @type {Array<string>}
     * @memberof DataForJimengT2IV30SubmitTaskOutput
     */
    binary_data_base64?: Array<string>;

    /**
     * @type {Array<string>}
     * @memberof DataForJimengT2IV30SubmitTaskOutput
     */
    image_urls?: Array<string>;

    /**
     * @type {string}
     * @memberof DataForJimengT2IV30SubmitTaskOutput
     */
    resp_data?: string;

    /**
     * @type {string}
     * @memberof DataForJimengT2IV30SubmitTaskOutput
     */
    response_data?: string;

    /**
     * @type {string}
     * @memberof DataForJimengT2IV30SubmitTaskOutput
     */
    status?: string;

    /**
     * @type {string}
     * @memberof DataForJimengT2IV30SubmitTaskOutput
     */
    task_id?: string;
}
