/* tslint:disable */
/* eslint-disable */
/**
 * cv20240606
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { DataForDressingDiffusionInput } from './data-for-dressing-diffusion-input';
 /**
 * 
 *
 * @export
 * @interface GarmentForDressingDiffusionInput
 */
export interface GarmentForDressingDiffusionInput {

    /**
     * @type {Array<DataForDressingDiffusionInput>}
     * @memberof GarmentForDressingDiffusionInput
     */
    data?: Array<DataForDressingDiffusionInput>;

    /**
     * @type {string}
     * @memberof GarmentForDressingDiffusionInput
     */
    id?: string;
}
