/* tslint:disable */
/* eslint-disable */
/**
 * cv20240606
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { LogoInfoForHighAesGeneralV14IPKeepInput } from './logo-info-for-high-aes-general-v14-ipkeep-input';
 /**
 * 
 *
 * @export
 * @interface HighAesGeneralV14IPKeepRequest
 */
export interface HighAesGeneralV14IPKeepRequest {

    /**
     * @type {Array<string>}
     * @memberof HighAesGeneralV14IPKeepRequest
     */
    binary_data_base64?: Array<string>;

    /**
     * @type {number}
     * @memberof HighAesGeneralV14IPKeepRequest
     */
    ddim_steps?: number;

    /**
     * @type {number}
     * @memberof HighAesGeneralV14IPKeepRequest
     */
    height?: number;

    /**
     * @type {Array<string>}
     * @memberof HighAesGeneralV14IPKeepRequest
     */
    image_urls?: Array<string>;

    /**
     * @type {LogoInfoForHighAesGeneralV14IPKeepInput}
     * @memberof HighAesGeneralV14IPKeepRequest
     */
    logo_info?: LogoInfoForHighAesGeneralV14IPKeepInput;

    /**
     * @type {string}
     * @memberof HighAesGeneralV14IPKeepRequest
     */
    model_version: string;

    /**
     * @type {string}
     * @memberof HighAesGeneralV14IPKeepRequest
     */
    prompt: string;

    /**
     * @type {number}
     * @memberof HighAesGeneralV14IPKeepRequest
     */
    ref_id_weight?: number;

    /**
     * @type {number}
     * @memberof HighAesGeneralV14IPKeepRequest
     */
    ref_ip_weight?: number;

    /**
     * @type {string}
     * @memberof HighAesGeneralV14IPKeepRequest
     */
    req_key: string;

    /**
     * @type {boolean}
     * @memberof HighAesGeneralV14IPKeepRequest
     */
    return_url?: boolean;

    /**
     * @type {number}
     * @memberof HighAesGeneralV14IPKeepRequest
     */
    scale?: number;

    /**
     * @type {number}
     * @memberof HighAesGeneralV14IPKeepRequest
     */
    seed?: number;

    /**
     * @type {boolean}
     * @memberof HighAesGeneralV14IPKeepRequest
     */
    use_predict_tags?: boolean;

    /**
     * @type {boolean}
     * @memberof HighAesGeneralV14IPKeepRequest
     */
    use_rephraser?: boolean;

    /**
     * @type {boolean}
     * @memberof HighAesGeneralV14IPKeepRequest
     */
    use_sr?: boolean;

    /**
     * @type {number}
     * @memberof HighAesGeneralV14IPKeepRequest
     */
    width?: number;
}
