/* tslint:disable */
/* eslint-disable */
/**
 * cv20240606
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { DataForImg2imgBgpaintLightOutput } from './data-for-img2img-bgpaint-light-output';
 /**
 * 
 *
 * @export
 * @interface Img2imgBgpaintLightResponse
 */
export interface Img2imgBgpaintLightResponse {

    /**
     * @type {number}
     * @memberof Img2imgBgpaintLightResponse
     */
    code?: number;

    /**
     * @type {DataForImg2imgBgpaintLightOutput}
     * @memberof Img2imgBgpaintLightResponse
     */
    data?: DataForImg2imgBgpaintLightOutput;

    /**
     * @type {string}
     * @memberof Img2imgBgpaintLightResponse
     */
    message?: string;

    /**
     * @type {string}
     * @memberof Img2imgBgpaintLightResponse
     */
    request_id?: string;

    /**
     * @type {number}
     * @memberof Img2imgBgpaintLightResponse
     */
    status?: number;

    /**
     * @type {string}
     * @memberof Img2imgBgpaintLightResponse
     */
    time_elapsed?: string;
}
