/* tslint:disable */
/* eslint-disable */
/**
 * cv20240606
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface JimengT2IV30SubmitTaskRequest
 */
export interface JimengT2IV30SubmitTaskRequest {

    /**
     * @type {number}
     * @memberof JimengT2IV30SubmitTaskRequest
     */
    height?: number;

    /**
     * @type {string}
     * @memberof JimengT2IV30SubmitTaskRequest
     */
    prompt: string;

    /**
     * @type {string}
     * @memberof JimengT2IV30SubmitTaskRequest
     */
    req_key: string;

    /**
     * @type {number}
     * @memberof JimengT2IV30SubmitTaskRequest
     */
    seed?: number;

    /**
     * @type {boolean}
     * @memberof JimengT2IV30SubmitTaskRequest
     */
    use_pre_llm?: boolean;

    /**
     * @type {number}
     * @memberof JimengT2IV30SubmitTaskRequest
     */
    width?: number;
}
