/* tslint:disable */
/* eslint-disable */
/**
 * cv20240606
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { DataForJimengHighAESGeneralV21LOutput } from './data-for-jimeng-high-aesgeneral-v21-loutput';
 /**
 * 
 *
 * @export
 * @interface JimengHighAESGeneralV21LResponse
 */
export interface JimengHighAESGeneralV21LResponse {

    /**
     * @type {number}
     * @memberof JimengHighAESGeneralV21LResponse
     */
    code?: number;

    /**
     * @type {DataForJimengHighAESGeneralV21LOutput}
     * @memberof JimengHighAESGeneralV21LResponse
     */
    data?: DataForJimengHighAESGeneralV21LOutput;

    /**
     * @type {string}
     * @memberof JimengHighAESGeneralV21LResponse
     */
    message?: string;

    /**
     * @type {string}
     * @memberof JimengHighAESGeneralV21LResponse
     */
    request_id?: string;

    /**
     * @type {number}
     * @memberof JimengHighAESGeneralV21LResponse
     */
    status?: number;

    /**
     * @type {string}
     * @memberof JimengHighAESGeneralV21LResponse
     */
    time_elapsed?: string;
}
