/* tslint:disable */
/* eslint-disable */
/**
 * cv20240606
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { DataForJimengI2VFirstV301080SubmitTaskOutput } from './data-for-jimeng-i2-vfirst-v301080-submit-task-output';
 /**
 * 
 *
 * @export
 * @interface JimengI2VFirstV301080SubmitTaskResponse
 */
export interface JimengI2VFirstV301080SubmitTaskResponse {

    /**
     * @type {number}
     * @memberof JimengI2VFirstV301080SubmitTaskResponse
     */
    code?: number;

    /**
     * @type {DataForJimengI2VFirstV301080SubmitTaskOutput}
     * @memberof JimengI2VFirstV301080SubmitTaskResponse
     */
    data?: DataForJimengI2VFirstV301080SubmitTaskOutput;

    /**
     * @type {string}
     * @memberof JimengI2VFirstV301080SubmitTaskResponse
     */
    message?: string;

    /**
     * @type {string}
     * @memberof JimengI2VFirstV301080SubmitTaskResponse
     */
    request_id?: string;

    /**
     * @type {number}
     * @memberof JimengI2VFirstV301080SubmitTaskResponse
     */
    status?: number;

    /**
     * @type {string}
     * @memberof JimengI2VFirstV301080SubmitTaskResponse
     */
    time_elapsed?: string;
}
