/* tslint:disable */
/* eslint-disable */
/**
 * cv20240606
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface LogoInfoForJimengHighAESGeneralV21LInput
 */
export interface LogoInfoForJimengHighAESGeneralV21LInput {

    /**
     * @type {boolean}
     * @memberof LogoInfoForJimengHighAESGeneralV21LInput
     */
    add_logo?: boolean;

    /**
     * @type {number}
     * @memberof LogoInfoForJimengHighAESGeneralV21LInput
     */
    language?: number;

    /**
     * @type {string}
     * @memberof LogoInfoForJimengHighAESGeneralV21LInput
     */
    logo_text_content?: string;

    /**
     * @type {number}
     * @memberof LogoInfoForJimengHighAESGeneralV21LInput
     */
    position?: number;
}
