/* tslint:disable */
/* eslint-disable */
/**
 * cv20240606
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ProductInteractionSubmitTaskRequest
 */
export interface ProductInteractionSubmitTaskRequest {

    /**
     * @type {string}
     * @memberof ProductInteractionSubmitTaskRequest
     */
    human_pic_url: string;

    /**
     * @type {string}
     * @memberof ProductInteractionSubmitTaskRequest
     */
    object_pic_url: string;

    /**
     * @type {string}
     * @memberof ProductInteractionSubmitTaskRequest
     */
    req_key: string;

    /**
     * @type {string}
     * @memberof ProductInteractionSubmitTaskRequest
     */
    resolution?: string;

    /**
     * @type {number}
     * @memberof ProductInteractionSubmitTaskRequest
     */
    video_duration?: number;
}
