/* tslint:disable */
/* eslint-disable */
/**
 * privatelink
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface DescribeVpcEndpointServicePermissionsRequest
 */
export interface DescribeVpcEndpointServicePermissionsRequest {

    /**
     * @type {number}
     * @memberof DescribeVpcEndpointServicePermissionsRequest
     */
    PageNumber?: number;

    /**
     * @type {number}
     * @memberof DescribeVpcEndpointServicePermissionsRequest
     */
    PageSize?: number;

    /**
     * @type {string}
     * @memberof DescribeVpcEndpointServicePermissionsRequest
     */
    PermitAccountId?: string;

    /**
     * @type {string}
     * @memberof DescribeVpcEndpointServicePermissionsRequest
     */
    ServiceId: string;
}
