/* tslint:disable */
/* eslint-disable */
/**
 * privatelink
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface EndpointZoneForDescribeVpcEndpointZonesOutput
 */
export interface EndpointZoneForDescribeVpcEndpointZonesOutput {

    /**
     * @type {string}
     * @memberof EndpointZoneForDescribeVpcEndpointZonesOutput
     */
    Ipv6ServiceStatus?: string;

    /**
     * @type {string}
     * @memberof EndpointZoneForDescribeVpcEndpointZonesOutput
     */
    NetworkInterfaceIP?: string;

    /**
     * @type {string}
     * @memberof EndpointZoneForDescribeVpcEndpointZonesOutput
     */
    NetworkInterfaceId?: string;

    /**
     * @type {string}
     * @memberof EndpointZoneForDescribeVpcEndpointZonesOutput
     */
    NetworkInterfaceIpv6?: string;

    /**
     * @type {string}
     * @memberof EndpointZoneForDescribeVpcEndpointZonesOutput
     */
    ReplacedNetworkInterfaceId?: string;

    /**
     * @type {string}
     * @memberof EndpointZoneForDescribeVpcEndpointZonesOutput
     */
    ReplacedNetworkInterfaceIp?: string;

    /**
     * @type {string}
     * @memberof EndpointZoneForDescribeVpcEndpointZonesOutput
     */
    ReplacedNetworkInterfaceIpv6?: string;

    /**
     * @type {string}
     * @memberof EndpointZoneForDescribeVpcEndpointZonesOutput
     */
    ServiceStatus?: string;

    /**
     * @type {string}
     * @memberof EndpointZoneForDescribeVpcEndpointZonesOutput
     */
    SubnetId?: string;

    /**
     * @type {string}
     * @memberof EndpointZoneForDescribeVpcEndpointZonesOutput
     */
    ZoneDomain?: string;

    /**
     * @type {string}
     * @memberof EndpointZoneForDescribeVpcEndpointZonesOutput
     */
    ZoneId?: string;

    /**
     * @type {string}
     * @memberof EndpointZoneForDescribeVpcEndpointZonesOutput
     */
    ZoneStatus?: string;
}
