/* tslint:disable */
/* eslint-disable */
/**
 * privatelink
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ResourceForCreateUniqueResourceTypeVpcEndpointServiceInput
 */
export interface ResourceForCreateUniqueResourceTypeVpcEndpointServiceInput {

    /**
     * @type {string}
     * @memberof ResourceForCreateUniqueResourceTypeVpcEndpointServiceInput
     */
    InstanceId?: string;

    /**
     * @type {string}
     * @memberof ResourceForCreateUniqueResourceTypeVpcEndpointServiceInput
     */
    ResourceId: string;

    /**
     * @type {Array<string>}
     * @memberof ResourceForCreateUniqueResourceTypeVpcEndpointServiceInput
     */
    ZoneIds?: Array<string>;
}
