/* tslint:disable */
/* eslint-disable */
/**
 * flink20250101
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface StartApplicationInstanceResponse
 */
export interface StartApplicationInstanceResponse {

    /**
     * @type {string}
     * @memberof StartApplicationInstanceResponse
     */
    Id?: string;

    /**
     * @type {string}
     * @memberof StartApplicationInstanceResponse
     */
    InstanceId?: string;

    /**
     * @type {boolean}
     * @memberof StartApplicationInstanceResponse
     */
    Success?: boolean;
}
