/* tslint:disable */
/* eslint-disable */
/**
 * vedbm
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { TemplateParameterForDescribeParameterTemplateDetailOutput } from './template-parameter-for-describe-parameter-template-detail-output';
 /**
 * 
 *
 * @export
 * @interface DescribeParameterTemplateDetailResponse
 */
export interface DescribeParameterTemplateDetailResponse {

    /**
     * @type {string}
     * @memberof DescribeParameterTemplateDetailResponse
     */
    CreateTime?: string;

    /**
     * @type {boolean}
     * @memberof DescribeParameterTemplateDetailResponse
     */
    NeedRestart?: boolean;

    /**
     * @type {number}
     * @memberof DescribeParameterTemplateDetailResponse
     */
    ParameterNumber?: number;

    /**
     * @type {string}
     * @memberof DescribeParameterTemplateDetailResponse
     */
    TemplateCategory?: string;

    /**
     * @type {string}
     * @memberof DescribeParameterTemplateDetailResponse
     */
    TemplateDescription?: string;

    /**
     * @type {string}
     * @memberof DescribeParameterTemplateDetailResponse
     */
    TemplateId?: string;

    /**
     * @type {string}
     * @memberof DescribeParameterTemplateDetailResponse
     */
    TemplateName?: string;

    /**
     * @type {Array<TemplateParameterForDescribeParameterTemplateDetailOutput>}
     * @memberof DescribeParameterTemplateDetailResponse
     */
    TemplateParameters?: Array<TemplateParameterForDescribeParameterTemplateDetailOutput>;

    /**
     * @type {string}
     * @memberof DescribeParameterTemplateDetailResponse
     */
    TemplateSource?: string;

    /**
     * @type {string}
     * @memberof DescribeParameterTemplateDetailResponse
     */
    TemplateType?: string;

    /**
     * @type {string}
     * @memberof DescribeParameterTemplateDetailResponse
     */
    TemplateTypeVersion?: string;

    /**
     * @type {string}
     * @memberof DescribeParameterTemplateDetailResponse
     */
    UpdateTime?: string;
}
