/* tslint:disable */
/* eslint-disable */
/**
 * vedbm
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ModifyDBInstanceDeletionProtectionPolicyRequest
 */
export interface ModifyDBInstanceDeletionProtectionPolicyRequest {

    /**
     * @type {string}
     * @memberof ModifyDBInstanceDeletionProtectionPolicyRequest
     */
    DeletionProtection: ModifyDBInstanceDeletionProtectionPolicyRequestDeletionProtectionEnum;

    /**
     * @type {string}
     * @memberof ModifyDBInstanceDeletionProtectionPolicyRequest
     */
    InstanceId: string;
}

/**
 * @export
 * @enum {string}
 */
export enum ModifyDBInstanceDeletionProtectionPolicyRequestDeletionProtectionEnum {
    Disabled = 'disabled',
    Enabled = 'enabled'
}

