/* tslint:disable */
/* eslint-disable */
/**
 * kms
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface AsymmetricEncryptRequest
 */
export interface AsymmetricEncryptRequest {

    /**
     * @type {string}
     * @memberof AsymmetricEncryptRequest
     */
    Algorithm: string;

    /**
     * @type {string}
     * @memberof AsymmetricEncryptRequest
     */
    KeyID?: string;

    /**
     * @type {string}
     * @memberof AsymmetricEncryptRequest
     */
    KeyName?: string;

    /**
     * @type {string}
     * @memberof AsymmetricEncryptRequest
     */
    KeyringName?: string;

    /**
     * @type {string}
     * @memberof AsymmetricEncryptRequest
     */
    Plaintext: string;
}
