/* tslint:disable */
/* eslint-disable */
/**
 * kms
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { KeyringForDescribeKeyringsOutput } from './keyring-for-describe-keyrings-output';
import { PageInfoForDescribeKeyringsOutput } from './page-info-for-describe-keyrings-output';
 /**
 * 
 *
 * @export
 * @interface DescribeKeyringsResponse
 */
export interface DescribeKeyringsResponse {

    /**
     * @type {Array<KeyringForDescribeKeyringsOutput>}
     * @memberof DescribeKeyringsResponse
     */
    Keyrings?: Array<KeyringForDescribeKeyringsOutput>;

    /**
     * @type {PageInfoForDescribeKeyringsOutput}
     * @memberof DescribeKeyringsResponse
     */
    PageInfo?: PageInfoForDescribeKeyringsOutput;
}
