/* tslint:disable */
/* eslint-disable */
/**
 * rcs_5g
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface SendRcsRequest
 */
export interface SendRcsRequest {

    /**
     * @type {string}
     * @memberof SendRcsRequest
     */
    ChannelType?: SendRcsRequestChannelTypeEnum;

    /**
     * @type {string}
     * @memberof SendRcsRequest
     */
    ChatbotId: string;

    /**
     * @type {boolean}
     * @memberof SendRcsRequest
     */
    FailbackFlag?: boolean;

    /**
     * @type {string}
     * @memberof SendRcsRequest
     */
    MessageType?: SendRcsRequestMessageTypeEnum;

    /**
     * @type {string}
     * @memberof SendRcsRequest
     */
    Params?: string;

    /**
     * @type {string}
     * @memberof SendRcsRequest
     */
    Receiver: string;

    /**
     * @type {string}
     * @memberof SendRcsRequest
     */
    SmsSign?: string;

    /**
     * @type {string}
     * @memberof SendRcsRequest
     */
    SmsSubAccountId?: string;

    /**
     * @type {string}
     * @memberof SendRcsRequest
     */
    SmsTemplateId?: string;

    /**
     * @type {string}
     * @memberof SendRcsRequest
     */
    TemplateCode: string;
}

/**
 * @export
 * @enum {string}
 */
export enum SendRcsRequestChannelTypeEnum {
    RCS = 'RCS'
}
/**
 * @export
 * @enum {string}
 */
export enum SendRcsRequestMessageTypeEnum {
    TEMPLATE = 'TEMPLATE'
}

