/* tslint:disable */
/* eslint-disable */
/**
 * waf
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Client, ClientConfig, Command, buildRequestConfigFromMetaPath, CommandOutput } from '@volcengine/sdk-core';

import { AddHostGroupRequest } from './types/index';
import { AddHostGroupResponse } from './types/index';
import { AddIpGroupRequest } from './types/index';
import { AddIpGroupResponse } from './types/index';
import { AddProhibitionBlackRequest } from './types/index';
import { AddProhibitionBlackResponse } from './types/index';
import { AddProhibitionWhiteRequest } from './types/index';
import { AddProhibitionWhiteResponse } from './types/index';
import { BatchUpdateTLSFieldsConfigRequest } from './types/index';
import { BatchUpdateTLSFieldsConfigResponse } from './types/index';
import { CheckLLMPromptRequest } from './types/index';
import { CheckLLMPromptResponse } from './types/index';
import { CheckLLMResponseStreamRequest } from './types/index';
import { CheckLLMResponseStreamResponse } from './types/index';
import { CreateAclRuleRequest } from './types/index';
import { CreateAclRuleResponse } from './types/index';
import { CreateAllowRuleRequest } from './types/index';
import { CreateAllowRuleResponse } from './types/index';
import { CreateBlockRuleRequest } from './types/index';
import { CreateBlockRuleResponse } from './types/index';
import { CreateBotAnalyseProtectRuleRequest } from './types/index';
import { CreateBotAnalyseProtectRuleResponse } from './types/index';
import { CreateCCRuleRequest } from './types/index';
import { CreateCCRuleResponse } from './types/index';
import { CreateCustomBotConfigRequest } from './types/index';
import { CreateCustomBotConfigResponse } from './types/index';
import { CreateCustomPageRequest } from './types/index';
import { CreateCustomPageResponse } from './types/index';
import { CreateDomainRequest } from './types/index';
import { CreateDomainResponse } from './types/index';
import { CreateTamperProofRequest } from './types/index';
import { CreateTamperProofResponse } from './types/index';
import { CreateVulWhiteFieldRequest } from './types/index';
import { CreateVulWhiteFieldResponse } from './types/index';
import { DeleteAclRuleRequest } from './types/index';
import { DeleteAclRuleResponse } from './types/index';
import { DeleteAllowRuleRequest } from './types/index';
import { DeleteAllowRuleResponse } from './types/index';
import { DeleteBlockRuleRequest } from './types/index';
import { DeleteBlockRuleResponse } from './types/index';
import { DeleteBotAnalyseProtectRuleRequest } from './types/index';
import { DeleteBotAnalyseProtectRuleResponse } from './types/index';
import { DeleteCCRuleRequest } from './types/index';
import { DeleteCCRuleResponse } from './types/index';
import { DeleteCustomBotConfigRequest } from './types/index';
import { DeleteCustomBotConfigResponse } from './types/index';
import { DeleteCustomPageRequest } from './types/index';
import { DeleteCustomPageResponse } from './types/index';
import { DeleteDomainRequest } from './types/index';
import { DeleteDomainResponse } from './types/index';
import { DeleteHostGroupRequest } from './types/index';
import { DeleteHostGroupResponse } from './types/index';
import { DeleteIpGroupRequest } from './types/index';
import { DeleteIpGroupResponse } from './types/index';
import { DeleteProhibitionBlackRequest } from './types/index';
import { DeleteProhibitionBlackResponse } from './types/index';
import { DeleteProhibitionWhiteRequest } from './types/index';
import { DeleteProhibitionWhiteResponse } from './types/index';
import { DeleteTamperProofRequest } from './types/index';
import { DeleteTamperProofResponse } from './types/index';
import { DeleteVulWhiteFieldRequest } from './types/index';
import { DeleteVulWhiteFieldResponse } from './types/index';
import { DeleteWafServiceCertificateRequest } from './types/index';
import { DeleteWafServiceCertificateResponse } from './types/index';
import { GetDomainInfoRequest } from './types/index';
import { GetDomainInfoResponse } from './types/index';
import { GetInstanceCtlRequest } from './types/index';
import { GetInstanceCtlResponse } from './types/index';
import { GetReqQPSAnalysisRequest } from './types/index';
import { GetReqQPSAnalysisResponse } from './types/index';
import { GetTLSConfigRequest } from './types/index';
import { GetTLSConfigResponse } from './types/index';
import { GetVulnerabilityConfigRequest } from './types/index';
import { GetVulnerabilityConfigResponse } from './types/index';
import { ListAclRuleRequest } from './types/index';
import { ListAclRuleResponse } from './types/index';
import { ListAllIpGroupsRequest } from './types/index';
import { ListAllIpGroupsResponse } from './types/index';
import { ListAllowRuleRequest } from './types/index';
import { ListAllowRuleResponse } from './types/index';
import { ListAreaBlockRuleRequest } from './types/index';
import { ListAreaBlockRuleResponse } from './types/index';
import { ListBlockRuleRequest } from './types/index';
import { ListBlockRuleResponse } from './types/index';
import { ListBotAnalyseProtectRulePriorityAvailableRequest } from './types/index';
import { ListBotAnalyseProtectRulePriorityAvailableResponse } from './types/index';
import { ListBotAnalyseProtectRuleRequest } from './types/index';
import { ListBotAnalyseProtectRuleResponse } from './types/index';
import { ListCCRuleRequest } from './types/index';
import { ListCCRuleResponse } from './types/index';
import { ListCertificateServicesRequest } from './types/index';
import { ListCertificateServicesResponse } from './types/index';
import { ListCustomBotConfigRequest } from './types/index';
import { ListCustomBotConfigResponse } from './types/index';
import { ListCustomPageRequest } from './types/index';
import { ListCustomPageResponse } from './types/index';
import { ListDomainRequest } from './types/index';
import { ListDomainResponse } from './types/index';
import { ListHostGroupRequest } from './types/index';
import { ListHostGroupResponse } from './types/index';
import { ListIpGroupRequest } from './types/index';
import { ListIpGroupResponse } from './types/index';
import { ListLoadBalancerRequest } from './types/index';
import { ListLoadBalancerResponse } from './types/index';
import { ListProhibitionRequest } from './types/index';
import { ListProhibitionResponse } from './types/index';
import { ListSystemBotConfigRequest } from './types/index';
import { ListSystemBotConfigResponse } from './types/index';
import { ListTamperProofRequest } from './types/index';
import { ListTamperProofResponse } from './types/index';
import { ListVulWhiteFieldRequest } from './types/index';
import { ListVulWhiteFieldResponse } from './types/index';
import { ListVulnerabilityRuleRequest } from './types/index';
import { ListVulnerabilityRuleResponse } from './types/index';
import { ListWafServiceCertificateRequest } from './types/index';
import { ListWafServiceCertificateResponse } from './types/index';
import { ModifyServiceDefenceModeRequest } from './types/index';
import { ModifyServiceDefenceModeResponse } from './types/index';
import { ModifyTLSConfigRequest } from './types/index';
import { ModifyTLSConfigResponse } from './types/index';
import { QueryAttackAnalysisTermsAggLbRequest } from './types/index';
import { QueryAttackAnalysisTermsAggLbResponse } from './types/index';
import { QueryAttackAnalysisWithRuleAggLbRequest } from './types/index';
import { QueryAttackAnalysisWithRuleAggLbResponse } from './types/index';
import { QueryAttackSecurityEventRequest } from './types/index';
import { QueryAttackSecurityEventResponse } from './types/index';
import { QueryCertificateIfReplaceRequest } from './types/index';
import { QueryCertificateIfReplaceResponse } from './types/index';
import { QueryFlowOverviewLbRequest } from './types/index';
import { QueryFlowOverviewLbResponse } from './types/index';
import { QueryLLMGenerateRequest } from './types/index';
import { QueryLLMGenerateResponse } from './types/index';
import { QueryProtectionOverviewLbRequest } from './types/index';
import { QueryProtectionOverviewLbResponse } from './types/index';
import { UpdateAclRuleRequest } from './types/index';
import { UpdateAclRuleResponse } from './types/index';
import { UpdateAllowRuleRequest } from './types/index';
import { UpdateAllowRuleResponse } from './types/index';
import { UpdateAreaBlockRuleRequest } from './types/index';
import { UpdateAreaBlockRuleResponse } from './types/index';
import { UpdateBlockRuleRequest } from './types/index';
import { UpdateBlockRuleResponse } from './types/index';
import { UpdateBotAnalyseProtectRuleRequest } from './types/index';
import { UpdateBotAnalyseProtectRuleResponse } from './types/index';
import { UpdateCCRuleRequest } from './types/index';
import { UpdateCCRuleResponse } from './types/index';
import { UpdateCustomBotConfigRequest } from './types/index';
import { UpdateCustomBotConfigResponse } from './types/index';
import { UpdateCustomPageRequest } from './types/index';
import { UpdateCustomPageResponse } from './types/index';
import { UpdateCustomSystemVulRuleRequest } from './types/index';
import { UpdateCustomSystemVulRuleResponse } from './types/index';
import { UpdateDomainRequest } from './types/index';
import { UpdateDomainResponse } from './types/index';
import { UpdateHostGroupRequest } from './types/index';
import { UpdateHostGroupResponse } from './types/index';
import { UpdateInstanceCtlRequest } from './types/index';
import { UpdateInstanceCtlResponse } from './types/index';
import { UpdateIpGroupRequest } from './types/index';
import { UpdateIpGroupResponse } from './types/index';
import { UpdateSystemBotConfigRequest } from './types/index';
import { UpdateSystemBotConfigResponse } from './types/index';
import { UpdateTamperProofCacheRequest } from './types/index';
import { UpdateTamperProofCacheResponse } from './types/index';
import { UpdateTamperProofRequest } from './types/index';
import { UpdateTamperProofResponse } from './types/index';
import { UpdateVulWhiteFieldRequest } from './types/index';
import { UpdateVulWhiteFieldResponse } from './types/index';
import { UpdateVulnerabilityConfigRequest } from './types/index';
import { UpdateVulnerabilityConfigResponse } from './types/index';
import { UpdateWafServiceControlRequest } from './types/index';
import { UpdateWafServiceControlResponse } from './types/index';
import { UploadWafServiceCertificateRequest } from './types/index';
import { UploadWafServiceCertificateResponse } from './types/index';

// ============================================================================
// Output Type Definitions
// ============================================================================
export type AddHostGroupCommandOutput = CommandOutput<AddHostGroupResponse>;
export type AddIpGroupCommandOutput = CommandOutput<AddIpGroupResponse>;
export type AddProhibitionBlackCommandOutput = CommandOutput<AddProhibitionBlackResponse>;
export type AddProhibitionWhiteCommandOutput = CommandOutput<AddProhibitionWhiteResponse>;
export type BatchUpdateTLSFieldsConfigCommandOutput = CommandOutput<BatchUpdateTLSFieldsConfigResponse>;
export type CheckLLMPromptCommandOutput = CommandOutput<CheckLLMPromptResponse>;
export type CheckLLMResponseStreamCommandOutput = CommandOutput<CheckLLMResponseStreamResponse>;
export type CreateAclRuleCommandOutput = CommandOutput<CreateAclRuleResponse>;
export type CreateAllowRuleCommandOutput = CommandOutput<CreateAllowRuleResponse>;
export type CreateBlockRuleCommandOutput = CommandOutput<CreateBlockRuleResponse>;
export type CreateBotAnalyseProtectRuleCommandOutput = CommandOutput<CreateBotAnalyseProtectRuleResponse>;
export type CreateCCRuleCommandOutput = CommandOutput<CreateCCRuleResponse>;
export type CreateCustomBotConfigCommandOutput = CommandOutput<CreateCustomBotConfigResponse>;
export type CreateCustomPageCommandOutput = CommandOutput<CreateCustomPageResponse>;
export type CreateDomainCommandOutput = CommandOutput<CreateDomainResponse>;
export type CreateTamperProofCommandOutput = CommandOutput<CreateTamperProofResponse>;
export type CreateVulWhiteFieldCommandOutput = CommandOutput<CreateVulWhiteFieldResponse>;
export type DeleteAclRuleCommandOutput = CommandOutput<DeleteAclRuleResponse>;
export type DeleteAllowRuleCommandOutput = CommandOutput<DeleteAllowRuleResponse>;
export type DeleteBlockRuleCommandOutput = CommandOutput<DeleteBlockRuleResponse>;
export type DeleteBotAnalyseProtectRuleCommandOutput = CommandOutput<DeleteBotAnalyseProtectRuleResponse>;
export type DeleteCCRuleCommandOutput = CommandOutput<DeleteCCRuleResponse>;
export type DeleteCustomBotConfigCommandOutput = CommandOutput<DeleteCustomBotConfigResponse>;
export type DeleteCustomPageCommandOutput = CommandOutput<DeleteCustomPageResponse>;
export type DeleteDomainCommandOutput = CommandOutput<DeleteDomainResponse>;
export type DeleteHostGroupCommandOutput = CommandOutput<DeleteHostGroupResponse>;
export type DeleteIpGroupCommandOutput = CommandOutput<DeleteIpGroupResponse>;
export type DeleteProhibitionBlackCommandOutput = CommandOutput<DeleteProhibitionBlackResponse>;
export type DeleteProhibitionWhiteCommandOutput = CommandOutput<DeleteProhibitionWhiteResponse>;
export type DeleteTamperProofCommandOutput = CommandOutput<DeleteTamperProofResponse>;
export type DeleteVulWhiteFieldCommandOutput = CommandOutput<DeleteVulWhiteFieldResponse>;
export type DeleteWafServiceCertificateCommandOutput = CommandOutput<DeleteWafServiceCertificateResponse>;
export type GetDomainInfoCommandOutput = CommandOutput<GetDomainInfoResponse>;
export type GetInstanceCtlCommandOutput = CommandOutput<GetInstanceCtlResponse>;
export type GetReqQPSAnalysisCommandOutput = CommandOutput<GetReqQPSAnalysisResponse>;
export type GetTLSConfigCommandOutput = CommandOutput<GetTLSConfigResponse>;
export type GetVulnerabilityConfigCommandOutput = CommandOutput<GetVulnerabilityConfigResponse>;
export type ListAclRuleCommandOutput = CommandOutput<ListAclRuleResponse>;
export type ListAllIpGroupsCommandOutput = CommandOutput<ListAllIpGroupsResponse>;
export type ListAllowRuleCommandOutput = CommandOutput<ListAllowRuleResponse>;
export type ListAreaBlockRuleCommandOutput = CommandOutput<ListAreaBlockRuleResponse>;
export type ListBlockRuleCommandOutput = CommandOutput<ListBlockRuleResponse>;
export type ListBotAnalyseProtectRuleCommandOutput = CommandOutput<ListBotAnalyseProtectRuleResponse>;
export type ListBotAnalyseProtectRulePriorityAvailableCommandOutput = CommandOutput<ListBotAnalyseProtectRulePriorityAvailableResponse>;
export type ListCCRuleCommandOutput = CommandOutput<ListCCRuleResponse>;
export type ListCertificateServicesCommandOutput = CommandOutput<ListCertificateServicesResponse>;
export type ListCustomBotConfigCommandOutput = CommandOutput<ListCustomBotConfigResponse>;
export type ListCustomPageCommandOutput = CommandOutput<ListCustomPageResponse>;
export type ListDomainCommandOutput = CommandOutput<ListDomainResponse>;
export type ListHostGroupCommandOutput = CommandOutput<ListHostGroupResponse>;
export type ListIpGroupCommandOutput = CommandOutput<ListIpGroupResponse>;
export type ListLoadBalancerCommandOutput = CommandOutput<ListLoadBalancerResponse>;
export type ListProhibitionCommandOutput = CommandOutput<ListProhibitionResponse>;
export type ListSystemBotConfigCommandOutput = CommandOutput<ListSystemBotConfigResponse>;
export type ListTamperProofCommandOutput = CommandOutput<ListTamperProofResponse>;
export type ListVulWhiteFieldCommandOutput = CommandOutput<ListVulWhiteFieldResponse>;
export type ListVulnerabilityRuleCommandOutput = CommandOutput<ListVulnerabilityRuleResponse>;
export type ListWafServiceCertificateCommandOutput = CommandOutput<ListWafServiceCertificateResponse>;
export type ModifyServiceDefenceModeCommandOutput = CommandOutput<ModifyServiceDefenceModeResponse>;
export type ModifyTLSConfigCommandOutput = CommandOutput<ModifyTLSConfigResponse>;
export type QueryAttackAnalysisTermsAggLbCommandOutput = CommandOutput<QueryAttackAnalysisTermsAggLbResponse>;
export type QueryAttackAnalysisWithRuleAggLbCommandOutput = CommandOutput<QueryAttackAnalysisWithRuleAggLbResponse>;
export type QueryAttackSecurityEventCommandOutput = CommandOutput<QueryAttackSecurityEventResponse>;
export type QueryCertificateIfReplaceCommandOutput = CommandOutput<QueryCertificateIfReplaceResponse>;
export type QueryFlowOverviewLbCommandOutput = CommandOutput<QueryFlowOverviewLbResponse>;
export type QueryLLMGenerateCommandOutput = CommandOutput<QueryLLMGenerateResponse>;
export type QueryProtectionOverviewLbCommandOutput = CommandOutput<QueryProtectionOverviewLbResponse>;
export type UpdateAclRuleCommandOutput = CommandOutput<UpdateAclRuleResponse>;
export type UpdateAllowRuleCommandOutput = CommandOutput<UpdateAllowRuleResponse>;
export type UpdateAreaBlockRuleCommandOutput = CommandOutput<UpdateAreaBlockRuleResponse>;
export type UpdateBlockRuleCommandOutput = CommandOutput<UpdateBlockRuleResponse>;
export type UpdateBotAnalyseProtectRuleCommandOutput = CommandOutput<UpdateBotAnalyseProtectRuleResponse>;
export type UpdateCCRuleCommandOutput = CommandOutput<UpdateCCRuleResponse>;
export type UpdateCustomBotConfigCommandOutput = CommandOutput<UpdateCustomBotConfigResponse>;
export type UpdateCustomPageCommandOutput = CommandOutput<UpdateCustomPageResponse>;
export type UpdateCustomSystemVulRuleCommandOutput = CommandOutput<UpdateCustomSystemVulRuleResponse>;
export type UpdateDomainCommandOutput = CommandOutput<UpdateDomainResponse>;
export type UpdateHostGroupCommandOutput = CommandOutput<UpdateHostGroupResponse>;
export type UpdateInstanceCtlCommandOutput = CommandOutput<UpdateInstanceCtlResponse>;
export type UpdateIpGroupCommandOutput = CommandOutput<UpdateIpGroupResponse>;
export type UpdateSystemBotConfigCommandOutput = CommandOutput<UpdateSystemBotConfigResponse>;
export type UpdateTamperProofCommandOutput = CommandOutput<UpdateTamperProofResponse>;
export type UpdateTamperProofCacheCommandOutput = CommandOutput<UpdateTamperProofCacheResponse>;
export type UpdateVulWhiteFieldCommandOutput = CommandOutput<UpdateVulWhiteFieldResponse>;
export type UpdateVulnerabilityConfigCommandOutput = CommandOutput<UpdateVulnerabilityConfigResponse>;
export type UpdateWafServiceControlCommandOutput = CommandOutput<UpdateWafServiceControlResponse>;
export type UploadWafServiceCertificateCommandOutput = CommandOutput<UploadWafServiceCertificateResponse>;


/**
 * WAFClient Service Client
 */
export class WAFClient extends Client {
  constructor(config: ClientConfig = {}) {
    super({
      protocol: 'https',
      region: 'cn-beijing',
      ...config,
    });
  }
}

/**
 * Command to AddHostGroup
 */
export class AddHostGroupCommand extends Command<
  AddHostGroupRequest,
  AddHostGroupCommandOutput,
  'AddHostGroupCommand'
> {
  static readonly metaPath = '/AddHostGroup/2023-12-25/waf/post/application_json/';

  constructor(input: AddHostGroupRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(AddHostGroupCommand.metaPath);
  }
}
/**
 * Command to AddIpGroup
 */
export class AddIpGroupCommand extends Command<
  AddIpGroupRequest,
  AddIpGroupCommandOutput,
  'AddIpGroupCommand'
> {
  static readonly metaPath = '/AddIpGroup/2023-12-25/waf/post/application_json/';

  constructor(input: AddIpGroupRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(AddIpGroupCommand.metaPath);
  }
}
/**
 * Command to AddProhibitionBlack
 */
export class AddProhibitionBlackCommand extends Command<
  AddProhibitionBlackRequest,
  AddProhibitionBlackCommandOutput,
  'AddProhibitionBlackCommand'
> {
  static readonly metaPath = '/AddProhibitionBlack/2023-12-25/waf/post/application_json/';

  constructor(input: AddProhibitionBlackRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(AddProhibitionBlackCommand.metaPath);
  }
}
/**
 * Command to AddProhibitionWhite
 */
export class AddProhibitionWhiteCommand extends Command<
  AddProhibitionWhiteRequest,
  AddProhibitionWhiteCommandOutput,
  'AddProhibitionWhiteCommand'
> {
  static readonly metaPath = '/AddProhibitionWhite/2023-12-25/waf/post/application_json/';

  constructor(input: AddProhibitionWhiteRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(AddProhibitionWhiteCommand.metaPath);
  }
}
/**
 * Command to BatchUpdateTLSFieldsConfig
 */
export class BatchUpdateTLSFieldsConfigCommand extends Command<
  BatchUpdateTLSFieldsConfigRequest,
  BatchUpdateTLSFieldsConfigCommandOutput,
  'BatchUpdateTLSFieldsConfigCommand'
> {
  static readonly metaPath = '/BatchUpdateTLSFieldsConfig/2023-12-25/waf/post/application_json/';

  constructor(input: BatchUpdateTLSFieldsConfigRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(BatchUpdateTLSFieldsConfigCommand.metaPath);
  }
}
/**
 * Command to CheckLLMPrompt
 */
export class CheckLLMPromptCommand extends Command<
  CheckLLMPromptRequest,
  CheckLLMPromptCommandOutput,
  'CheckLLMPromptCommand'
> {
  static readonly metaPath = '/CheckLLMPrompt/2023-12-25/waf/post/application_json/';

  constructor(input: CheckLLMPromptRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(CheckLLMPromptCommand.metaPath);
  }
}
/**
 * Command to CheckLLMResponseStream
 */
export class CheckLLMResponseStreamCommand extends Command<
  CheckLLMResponseStreamRequest,
  CheckLLMResponseStreamCommandOutput,
  'CheckLLMResponseStreamCommand'
> {
  static readonly metaPath = '/CheckLLMResponseStream/2023-12-25/waf/post/application_json/';

  constructor(input: CheckLLMResponseStreamRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(CheckLLMResponseStreamCommand.metaPath);
  }
}
/**
 * Command to CreateAclRule
 */
export class CreateAclRuleCommand extends Command<
  CreateAclRuleRequest,
  CreateAclRuleCommandOutput,
  'CreateAclRuleCommand'
> {
  static readonly metaPath = '/CreateAclRule/2023-12-25/waf/post/application_json/';

  constructor(input: CreateAclRuleRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(CreateAclRuleCommand.metaPath);
  }
}
/**
 * Command to CreateAllowRule
 */
export class CreateAllowRuleCommand extends Command<
  CreateAllowRuleRequest,
  CreateAllowRuleCommandOutput,
  'CreateAllowRuleCommand'
> {
  static readonly metaPath = '/CreateAllowRule/2023-12-25/waf/post/application_json/';

  constructor(input: CreateAllowRuleRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(CreateAllowRuleCommand.metaPath);
  }
}
/**
 * Command to CreateBlockRule
 */
export class CreateBlockRuleCommand extends Command<
  CreateBlockRuleRequest,
  CreateBlockRuleCommandOutput,
  'CreateBlockRuleCommand'
> {
  static readonly metaPath = '/CreateBlockRule/2023-12-25/waf/post/application_json/';

  constructor(input: CreateBlockRuleRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(CreateBlockRuleCommand.metaPath);
  }
}
/**
 * Command to CreateBotAnalyseProtectRule
 */
export class CreateBotAnalyseProtectRuleCommand extends Command<
  CreateBotAnalyseProtectRuleRequest,
  CreateBotAnalyseProtectRuleCommandOutput,
  'CreateBotAnalyseProtectRuleCommand'
> {
  static readonly metaPath = '/CreateBotAnalyseProtectRule/2023-12-25/waf/post/application_json/';

  constructor(input: CreateBotAnalyseProtectRuleRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(CreateBotAnalyseProtectRuleCommand.metaPath);
  }
}
/**
 * Command to CreateCCRule
 */
export class CreateCCRuleCommand extends Command<
  CreateCCRuleRequest,
  CreateCCRuleCommandOutput,
  'CreateCCRuleCommand'
> {
  static readonly metaPath = '/CreateCCRule/2023-12-25/waf/post/application_json/';

  constructor(input: CreateCCRuleRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(CreateCCRuleCommand.metaPath);
  }
}
/**
 * Command to CreateCustomBotConfig
 */
export class CreateCustomBotConfigCommand extends Command<
  CreateCustomBotConfigRequest,
  CreateCustomBotConfigCommandOutput,
  'CreateCustomBotConfigCommand'
> {
  static readonly metaPath = '/CreateCustomBotConfig/2023-12-25/waf/post/application_json/';

  constructor(input: CreateCustomBotConfigRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(CreateCustomBotConfigCommand.metaPath);
  }
}
/**
 * Command to CreateCustomPage
 */
export class CreateCustomPageCommand extends Command<
  CreateCustomPageRequest,
  CreateCustomPageCommandOutput,
  'CreateCustomPageCommand'
> {
  static readonly metaPath = '/CreateCustomPage/2023-12-25/waf/post/application_json/';

  constructor(input: CreateCustomPageRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(CreateCustomPageCommand.metaPath);
  }
}
/**
 * Command to CreateDomain
 */
export class CreateDomainCommand extends Command<
  CreateDomainRequest,
  CreateDomainCommandOutput,
  'CreateDomainCommand'
> {
  static readonly metaPath = '/CreateDomain/2023-12-25/waf/post/application_json/';

  constructor(input: CreateDomainRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(CreateDomainCommand.metaPath);
  }
}
/**
 * Command to CreateTamperProof
 */
export class CreateTamperProofCommand extends Command<
  CreateTamperProofRequest,
  CreateTamperProofCommandOutput,
  'CreateTamperProofCommand'
> {
  static readonly metaPath = '/CreateTamperProof/2023-12-25/waf/post/application_json/';

  constructor(input: CreateTamperProofRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(CreateTamperProofCommand.metaPath);
  }
}
/**
 * Command to CreateVulWhiteField
 */
export class CreateVulWhiteFieldCommand extends Command<
  CreateVulWhiteFieldRequest,
  CreateVulWhiteFieldCommandOutput,
  'CreateVulWhiteFieldCommand'
> {
  static readonly metaPath = '/CreateVulWhiteField/2023-12-25/waf/post/application_json/';

  constructor(input: CreateVulWhiteFieldRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(CreateVulWhiteFieldCommand.metaPath);
  }
}
/**
 * Command to DeleteAclRule
 */
export class DeleteAclRuleCommand extends Command<
  DeleteAclRuleRequest,
  DeleteAclRuleCommandOutput,
  'DeleteAclRuleCommand'
> {
  static readonly metaPath = '/DeleteAclRule/2023-12-25/waf/post/application_json/';

  constructor(input: DeleteAclRuleRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(DeleteAclRuleCommand.metaPath);
  }
}
/**
 * Command to DeleteAllowRule
 */
export class DeleteAllowRuleCommand extends Command<
  DeleteAllowRuleRequest,
  DeleteAllowRuleCommandOutput,
  'DeleteAllowRuleCommand'
> {
  static readonly metaPath = '/DeleteAllowRule/2023-12-25/waf/post/application_json/';

  constructor(input: DeleteAllowRuleRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(DeleteAllowRuleCommand.metaPath);
  }
}
/**
 * Command to DeleteBlockRule
 */
export class DeleteBlockRuleCommand extends Command<
  DeleteBlockRuleRequest,
  DeleteBlockRuleCommandOutput,
  'DeleteBlockRuleCommand'
> {
  static readonly metaPath = '/DeleteBlockRule/2023-12-25/waf/post/application_json/';

  constructor(input: DeleteBlockRuleRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(DeleteBlockRuleCommand.metaPath);
  }
}
/**
 * Command to DeleteBotAnalyseProtectRule
 */
export class DeleteBotAnalyseProtectRuleCommand extends Command<
  DeleteBotAnalyseProtectRuleRequest,
  DeleteBotAnalyseProtectRuleCommandOutput,
  'DeleteBotAnalyseProtectRuleCommand'
> {
  static readonly metaPath = '/DeleteBotAnalyseProtectRule/2023-12-25/waf/post/application_json/';

  constructor(input: DeleteBotAnalyseProtectRuleRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(DeleteBotAnalyseProtectRuleCommand.metaPath);
  }
}
/**
 * Command to DeleteCCRule
 */
export class DeleteCCRuleCommand extends Command<
  DeleteCCRuleRequest,
  DeleteCCRuleCommandOutput,
  'DeleteCCRuleCommand'
> {
  static readonly metaPath = '/DeleteCCRule/2023-12-25/waf/post/application_json/';

  constructor(input: DeleteCCRuleRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(DeleteCCRuleCommand.metaPath);
  }
}
/**
 * Command to DeleteCustomBotConfig
 */
export class DeleteCustomBotConfigCommand extends Command<
  DeleteCustomBotConfigRequest,
  DeleteCustomBotConfigCommandOutput,
  'DeleteCustomBotConfigCommand'
> {
  static readonly metaPath = '/DeleteCustomBotConfig/2023-12-25/waf/post/application_json/';

  constructor(input: DeleteCustomBotConfigRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(DeleteCustomBotConfigCommand.metaPath);
  }
}
/**
 * Command to DeleteCustomPage
 */
export class DeleteCustomPageCommand extends Command<
  DeleteCustomPageRequest,
  DeleteCustomPageCommandOutput,
  'DeleteCustomPageCommand'
> {
  static readonly metaPath = '/DeleteCustomPage/2023-12-25/waf/post/application_json/';

  constructor(input: DeleteCustomPageRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(DeleteCustomPageCommand.metaPath);
  }
}
/**
 * Command to DeleteDomain
 */
export class DeleteDomainCommand extends Command<
  DeleteDomainRequest,
  DeleteDomainCommandOutput,
  'DeleteDomainCommand'
> {
  static readonly metaPath = '/DeleteDomain/2023-12-25/waf/post/application_json/';

  constructor(input: DeleteDomainRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(DeleteDomainCommand.metaPath);
  }
}
/**
 * Command to DeleteHostGroup
 */
export class DeleteHostGroupCommand extends Command<
  DeleteHostGroupRequest,
  DeleteHostGroupCommandOutput,
  'DeleteHostGroupCommand'
> {
  static readonly metaPath = '/DeleteHostGroup/2023-12-25/waf/post/application_json/';

  constructor(input: DeleteHostGroupRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(DeleteHostGroupCommand.metaPath);
  }
}
/**
 * Command to DeleteIpGroup
 */
export class DeleteIpGroupCommand extends Command<
  DeleteIpGroupRequest,
  DeleteIpGroupCommandOutput,
  'DeleteIpGroupCommand'
> {
  static readonly metaPath = '/DeleteIpGroup/2023-12-25/waf/post/application_json/';

  constructor(input: DeleteIpGroupRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(DeleteIpGroupCommand.metaPath);
  }
}
/**
 * Command to DeleteProhibitionBlack
 */
export class DeleteProhibitionBlackCommand extends Command<
  DeleteProhibitionBlackRequest,
  DeleteProhibitionBlackCommandOutput,
  'DeleteProhibitionBlackCommand'
> {
  static readonly metaPath = '/DeleteProhibitionBlack/2023-12-25/waf/post/application_json/';

  constructor(input: DeleteProhibitionBlackRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(DeleteProhibitionBlackCommand.metaPath);
  }
}
/**
 * Command to DeleteProhibitionWhite
 */
export class DeleteProhibitionWhiteCommand extends Command<
  DeleteProhibitionWhiteRequest,
  DeleteProhibitionWhiteCommandOutput,
  'DeleteProhibitionWhiteCommand'
> {
  static readonly metaPath = '/DeleteProhibitionWhite/2023-12-25/waf/post/application_json/';

  constructor(input: DeleteProhibitionWhiteRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(DeleteProhibitionWhiteCommand.metaPath);
  }
}
/**
 * Command to DeleteTamperProof
 */
export class DeleteTamperProofCommand extends Command<
  DeleteTamperProofRequest,
  DeleteTamperProofCommandOutput,
  'DeleteTamperProofCommand'
> {
  static readonly metaPath = '/DeleteTamperProof/2023-12-25/waf/post/application_json/';

  constructor(input: DeleteTamperProofRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(DeleteTamperProofCommand.metaPath);
  }
}
/**
 * Command to DeleteVulWhiteField
 */
export class DeleteVulWhiteFieldCommand extends Command<
  DeleteVulWhiteFieldRequest,
  DeleteVulWhiteFieldCommandOutput,
  'DeleteVulWhiteFieldCommand'
> {
  static readonly metaPath = '/DeleteVulWhiteField/2023-12-25/waf/post/application_json/';

  constructor(input: DeleteVulWhiteFieldRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(DeleteVulWhiteFieldCommand.metaPath);
  }
}
/**
 * Command to DeleteWafServiceCertificate
 */
export class DeleteWafServiceCertificateCommand extends Command<
  DeleteWafServiceCertificateRequest,
  DeleteWafServiceCertificateCommandOutput,
  'DeleteWafServiceCertificateCommand'
> {
  static readonly metaPath = '/DeleteWafServiceCertificate/2023-12-25/waf/post/application_json/';

  constructor(input: DeleteWafServiceCertificateRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(DeleteWafServiceCertificateCommand.metaPath);
  }
}
/**
 * Command to GetDomainInfo
 */
export class GetDomainInfoCommand extends Command<
  GetDomainInfoRequest,
  GetDomainInfoCommandOutput,
  'GetDomainInfoCommand'
> {
  static readonly metaPath = '/GetDomainInfo/2023-12-25/waf/post/application_json/';

  constructor(input: GetDomainInfoRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(GetDomainInfoCommand.metaPath);
  }
}
/**
 * Command to GetInstanceCtl
 */
export class GetInstanceCtlCommand extends Command<
  GetInstanceCtlRequest,
  GetInstanceCtlCommandOutput,
  'GetInstanceCtlCommand'
> {
  static readonly metaPath = '/GetInstanceCtl/2023-12-25/waf/post/application_json/';

  constructor(input: GetInstanceCtlRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(GetInstanceCtlCommand.metaPath);
  }
}
/**
 * Command to GetReqQPSAnalysis
 */
export class GetReqQPSAnalysisCommand extends Command<
  GetReqQPSAnalysisRequest,
  GetReqQPSAnalysisCommandOutput,
  'GetReqQPSAnalysisCommand'
> {
  static readonly metaPath = '/GetReqQPSAnalysis/2023-12-25/waf/post/application_json/';

  constructor(input: GetReqQPSAnalysisRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(GetReqQPSAnalysisCommand.metaPath);
  }
}
/**
 * Command to GetTLSConfig
 */
export class GetTLSConfigCommand extends Command<
  GetTLSConfigRequest,
  GetTLSConfigCommandOutput,
  'GetTLSConfigCommand'
> {
  static readonly metaPath = '/GetTLSConfig/2023-12-25/waf/post/application_json/';

  constructor(input: GetTLSConfigRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(GetTLSConfigCommand.metaPath);
  }
}
/**
 * Command to GetVulnerabilityConfig
 */
export class GetVulnerabilityConfigCommand extends Command<
  GetVulnerabilityConfigRequest,
  GetVulnerabilityConfigCommandOutput,
  'GetVulnerabilityConfigCommand'
> {
  static readonly metaPath = '/GetVulnerabilityConfig/2023-12-25/waf/post/application_json/';

  constructor(input: GetVulnerabilityConfigRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(GetVulnerabilityConfigCommand.metaPath);
  }
}
/**
 * Command to ListAclRule
 */
export class ListAclRuleCommand extends Command<
  ListAclRuleRequest,
  ListAclRuleCommandOutput,
  'ListAclRuleCommand'
> {
  static readonly metaPath = '/ListAclRule/2023-12-25/waf/post/application_json/';

  constructor(input: ListAclRuleRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(ListAclRuleCommand.metaPath);
  }
}
/**
 * Command to ListAllIpGroups
 */
export class ListAllIpGroupsCommand extends Command<
  ListAllIpGroupsRequest,
  ListAllIpGroupsCommandOutput,
  'ListAllIpGroupsCommand'
> {
  static readonly metaPath = '/ListAllIpGroups/2023-12-25/waf/post/application_json/';

  constructor(input: ListAllIpGroupsRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(ListAllIpGroupsCommand.metaPath);
  }
}
/**
 * Command to ListAllowRule
 */
export class ListAllowRuleCommand extends Command<
  ListAllowRuleRequest,
  ListAllowRuleCommandOutput,
  'ListAllowRuleCommand'
> {
  static readonly metaPath = '/ListAllowRule/2023-12-25/waf/post/application_json/';

  constructor(input: ListAllowRuleRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(ListAllowRuleCommand.metaPath);
  }
}
/**
 * Command to ListAreaBlockRule
 */
export class ListAreaBlockRuleCommand extends Command<
  ListAreaBlockRuleRequest,
  ListAreaBlockRuleCommandOutput,
  'ListAreaBlockRuleCommand'
> {
  static readonly metaPath = '/ListAreaBlockRule/2023-12-25/waf/post/application_json/';

  constructor(input: ListAreaBlockRuleRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(ListAreaBlockRuleCommand.metaPath);
  }
}
/**
 * Command to ListBlockRule
 */
export class ListBlockRuleCommand extends Command<
  ListBlockRuleRequest,
  ListBlockRuleCommandOutput,
  'ListBlockRuleCommand'
> {
  static readonly metaPath = '/ListBlockRule/2023-12-25/waf/post/application_json/';

  constructor(input: ListBlockRuleRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(ListBlockRuleCommand.metaPath);
  }
}
/**
 * Command to ListBotAnalyseProtectRule
 */
export class ListBotAnalyseProtectRuleCommand extends Command<
  ListBotAnalyseProtectRuleRequest,
  ListBotAnalyseProtectRuleCommandOutput,
  'ListBotAnalyseProtectRuleCommand'
> {
  static readonly metaPath = '/ListBotAnalyseProtectRule/2023-12-25/waf/post/application_json/';

  constructor(input: ListBotAnalyseProtectRuleRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(ListBotAnalyseProtectRuleCommand.metaPath);
  }
}
/**
 * Command to ListBotAnalyseProtectRulePriorityAvailable
 */
export class ListBotAnalyseProtectRulePriorityAvailableCommand extends Command<
  ListBotAnalyseProtectRulePriorityAvailableRequest,
  ListBotAnalyseProtectRulePriorityAvailableCommandOutput,
  'ListBotAnalyseProtectRulePriorityAvailableCommand'
> {
  static readonly metaPath = '/ListBotAnalyseProtectRulePriorityAvailable/2023-12-25/waf/post/application_json/';

  constructor(input: ListBotAnalyseProtectRulePriorityAvailableRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(ListBotAnalyseProtectRulePriorityAvailableCommand.metaPath);
  }
}
/**
 * Command to ListCCRule
 */
export class ListCCRuleCommand extends Command<
  ListCCRuleRequest,
  ListCCRuleCommandOutput,
  'ListCCRuleCommand'
> {
  static readonly metaPath = '/ListCCRule/2023-12-25/waf/post/application_json/';

  constructor(input: ListCCRuleRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(ListCCRuleCommand.metaPath);
  }
}
/**
 * Command to ListCertificateServices
 */
export class ListCertificateServicesCommand extends Command<
  ListCertificateServicesRequest,
  ListCertificateServicesCommandOutput,
  'ListCertificateServicesCommand'
> {
  static readonly metaPath = '/ListCertificateServices/2023-12-25/waf/post/application_json/';

  constructor(input: ListCertificateServicesRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(ListCertificateServicesCommand.metaPath);
  }
}
/**
 * Command to ListCustomBotConfig
 */
export class ListCustomBotConfigCommand extends Command<
  ListCustomBotConfigRequest,
  ListCustomBotConfigCommandOutput,
  'ListCustomBotConfigCommand'
> {
  static readonly metaPath = '/ListCustomBotConfig/2023-12-25/waf/post/application_json/';

  constructor(input: ListCustomBotConfigRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(ListCustomBotConfigCommand.metaPath);
  }
}
/**
 * Command to ListCustomPage
 */
export class ListCustomPageCommand extends Command<
  ListCustomPageRequest,
  ListCustomPageCommandOutput,
  'ListCustomPageCommand'
> {
  static readonly metaPath = '/ListCustomPage/2023-12-25/waf/post/application_json/';

  constructor(input: ListCustomPageRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(ListCustomPageCommand.metaPath);
  }
}
/**
 * Command to ListDomain
 */
export class ListDomainCommand extends Command<
  ListDomainRequest,
  ListDomainCommandOutput,
  'ListDomainCommand'
> {
  static readonly metaPath = '/ListDomain/2023-12-25/waf/post/application_json/';

  constructor(input: ListDomainRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(ListDomainCommand.metaPath);
  }
}
/**
 * Command to ListHostGroup
 */
export class ListHostGroupCommand extends Command<
  ListHostGroupRequest,
  ListHostGroupCommandOutput,
  'ListHostGroupCommand'
> {
  static readonly metaPath = '/ListHostGroup/2023-12-25/waf/post/application_json/';

  constructor(input: ListHostGroupRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(ListHostGroupCommand.metaPath);
  }
}
/**
 * Command to ListIpGroup
 */
export class ListIpGroupCommand extends Command<
  ListIpGroupRequest,
  ListIpGroupCommandOutput,
  'ListIpGroupCommand'
> {
  static readonly metaPath = '/ListIpGroup/2023-12-25/waf/post/application_json/';

  constructor(input: ListIpGroupRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(ListIpGroupCommand.metaPath);
  }
}
/**
 * Command to ListLoadBalancer
 */
export class ListLoadBalancerCommand extends Command<
  ListLoadBalancerRequest,
  ListLoadBalancerCommandOutput,
  'ListLoadBalancerCommand'
> {
  static readonly metaPath = '/ListLoadBalancer/2023-12-25/waf/post/application_json/';

  constructor(input: ListLoadBalancerRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(ListLoadBalancerCommand.metaPath);
  }
}
/**
 * Command to ListProhibition
 */
export class ListProhibitionCommand extends Command<
  ListProhibitionRequest,
  ListProhibitionCommandOutput,
  'ListProhibitionCommand'
> {
  static readonly metaPath = '/ListProhibition/2023-12-25/waf/post/application_json/';

  constructor(input: ListProhibitionRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(ListProhibitionCommand.metaPath);
  }
}
/**
 * Command to ListSystemBotConfig
 */
export class ListSystemBotConfigCommand extends Command<
  ListSystemBotConfigRequest,
  ListSystemBotConfigCommandOutput,
  'ListSystemBotConfigCommand'
> {
  static readonly metaPath = '/ListSystemBotConfig/2023-12-25/waf/post/application_json/';

  constructor(input: ListSystemBotConfigRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(ListSystemBotConfigCommand.metaPath);
  }
}
/**
 * Command to ListTamperProof
 */
export class ListTamperProofCommand extends Command<
  ListTamperProofRequest,
  ListTamperProofCommandOutput,
  'ListTamperProofCommand'
> {
  static readonly metaPath = '/ListTamperProof/2023-12-25/waf/post/application_json/';

  constructor(input: ListTamperProofRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(ListTamperProofCommand.metaPath);
  }
}
/**
 * Command to ListVulWhiteField
 */
export class ListVulWhiteFieldCommand extends Command<
  ListVulWhiteFieldRequest,
  ListVulWhiteFieldCommandOutput,
  'ListVulWhiteFieldCommand'
> {
  static readonly metaPath = '/ListVulWhiteField/2023-12-25/waf/post/application_json/';

  constructor(input: ListVulWhiteFieldRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(ListVulWhiteFieldCommand.metaPath);
  }
}
/**
 * Command to ListVulnerabilityRule
 */
export class ListVulnerabilityRuleCommand extends Command<
  ListVulnerabilityRuleRequest,
  ListVulnerabilityRuleCommandOutput,
  'ListVulnerabilityRuleCommand'
> {
  static readonly metaPath = '/ListVulnerabilityRule/2023-12-25/waf/post/application_json/';

  constructor(input: ListVulnerabilityRuleRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(ListVulnerabilityRuleCommand.metaPath);
  }
}
/**
 * Command to ListWafServiceCertificate
 */
export class ListWafServiceCertificateCommand extends Command<
  ListWafServiceCertificateRequest,
  ListWafServiceCertificateCommandOutput,
  'ListWafServiceCertificateCommand'
> {
  static readonly metaPath = '/ListWafServiceCertificate/2023-12-25/waf/post/application_json/';

  constructor(input: ListWafServiceCertificateRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(ListWafServiceCertificateCommand.metaPath);
  }
}
/**
 * Command to ModifyServiceDefenceMode
 */
export class ModifyServiceDefenceModeCommand extends Command<
  ModifyServiceDefenceModeRequest,
  ModifyServiceDefenceModeCommandOutput,
  'ModifyServiceDefenceModeCommand'
> {
  static readonly metaPath = '/ModifyServiceDefenceMode/2023-12-25/waf/post/application_json/';

  constructor(input: ModifyServiceDefenceModeRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(ModifyServiceDefenceModeCommand.metaPath);
  }
}
/**
 * Command to ModifyTLSConfig
 */
export class ModifyTLSConfigCommand extends Command<
  ModifyTLSConfigRequest,
  ModifyTLSConfigCommandOutput,
  'ModifyTLSConfigCommand'
> {
  static readonly metaPath = '/ModifyTLSConfig/2023-12-25/waf/post/application_json/';

  constructor(input: ModifyTLSConfigRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(ModifyTLSConfigCommand.metaPath);
  }
}
/**
 * Command to QueryAttackAnalysisTermsAggLb
 */
export class QueryAttackAnalysisTermsAggLbCommand extends Command<
  QueryAttackAnalysisTermsAggLbRequest,
  QueryAttackAnalysisTermsAggLbCommandOutput,
  'QueryAttackAnalysisTermsAggLbCommand'
> {
  static readonly metaPath = '/QueryAttackAnalysisTermsAggLb/2023-12-25/waf/post/application_json/';

  constructor(input: QueryAttackAnalysisTermsAggLbRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(QueryAttackAnalysisTermsAggLbCommand.metaPath);
  }
}
/**
 * Command to QueryAttackAnalysisWithRuleAggLb
 */
export class QueryAttackAnalysisWithRuleAggLbCommand extends Command<
  QueryAttackAnalysisWithRuleAggLbRequest,
  QueryAttackAnalysisWithRuleAggLbCommandOutput,
  'QueryAttackAnalysisWithRuleAggLbCommand'
> {
  static readonly metaPath = '/QueryAttackAnalysisWithRuleAggLb/2023-12-25/waf/post/application_json/';

  constructor(input: QueryAttackAnalysisWithRuleAggLbRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(QueryAttackAnalysisWithRuleAggLbCommand.metaPath);
  }
}
/**
 * Command to QueryAttackSecurityEvent
 */
export class QueryAttackSecurityEventCommand extends Command<
  QueryAttackSecurityEventRequest,
  QueryAttackSecurityEventCommandOutput,
  'QueryAttackSecurityEventCommand'
> {
  static readonly metaPath = '/QueryAttackSecurityEvent/2023-12-25/waf/post/application_json/';

  constructor(input: QueryAttackSecurityEventRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(QueryAttackSecurityEventCommand.metaPath);
  }
}
/**
 * Command to QueryCertificateIfReplace
 */
export class QueryCertificateIfReplaceCommand extends Command<
  QueryCertificateIfReplaceRequest,
  QueryCertificateIfReplaceCommandOutput,
  'QueryCertificateIfReplaceCommand'
> {
  static readonly metaPath = '/QueryCertificateIfReplace/2023-12-25/waf/post/application_json/';

  constructor(input: QueryCertificateIfReplaceRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(QueryCertificateIfReplaceCommand.metaPath);
  }
}
/**
 * Command to QueryFlowOverviewLb
 */
export class QueryFlowOverviewLbCommand extends Command<
  QueryFlowOverviewLbRequest,
  QueryFlowOverviewLbCommandOutput,
  'QueryFlowOverviewLbCommand'
> {
  static readonly metaPath = '/QueryFlowOverviewLb/2023-12-25/waf/post/application_json/';

  constructor(input: QueryFlowOverviewLbRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(QueryFlowOverviewLbCommand.metaPath);
  }
}
/**
 * Command to QueryLLMGenerate
 */
export class QueryLLMGenerateCommand extends Command<
  QueryLLMGenerateRequest,
  QueryLLMGenerateCommandOutput,
  'QueryLLMGenerateCommand'
> {
  static readonly metaPath = '/QueryLLMGenerate/2023-12-25/waf/post/application_json/';

  constructor(input: QueryLLMGenerateRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(QueryLLMGenerateCommand.metaPath);
  }
}
/**
 * Command to QueryProtectionOverviewLb
 */
export class QueryProtectionOverviewLbCommand extends Command<
  QueryProtectionOverviewLbRequest,
  QueryProtectionOverviewLbCommandOutput,
  'QueryProtectionOverviewLbCommand'
> {
  static readonly metaPath = '/QueryProtectionOverviewLb/2023-12-25/waf/post/application_json/';

  constructor(input: QueryProtectionOverviewLbRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(QueryProtectionOverviewLbCommand.metaPath);
  }
}
/**
 * Command to UpdateAclRule
 */
export class UpdateAclRuleCommand extends Command<
  UpdateAclRuleRequest,
  UpdateAclRuleCommandOutput,
  'UpdateAclRuleCommand'
> {
  static readonly metaPath = '/UpdateAclRule/2023-12-25/waf/post/application_json/';

  constructor(input: UpdateAclRuleRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(UpdateAclRuleCommand.metaPath);
  }
}
/**
 * Command to UpdateAllowRule
 */
export class UpdateAllowRuleCommand extends Command<
  UpdateAllowRuleRequest,
  UpdateAllowRuleCommandOutput,
  'UpdateAllowRuleCommand'
> {
  static readonly metaPath = '/UpdateAllowRule/2023-12-25/waf/post/application_json/';

  constructor(input: UpdateAllowRuleRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(UpdateAllowRuleCommand.metaPath);
  }
}
/**
 * Command to UpdateAreaBlockRule
 */
export class UpdateAreaBlockRuleCommand extends Command<
  UpdateAreaBlockRuleRequest,
  UpdateAreaBlockRuleCommandOutput,
  'UpdateAreaBlockRuleCommand'
> {
  static readonly metaPath = '/UpdateAreaBlockRule/2023-12-25/waf/post/application_json/';

  constructor(input: UpdateAreaBlockRuleRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(UpdateAreaBlockRuleCommand.metaPath);
  }
}
/**
 * Command to UpdateBlockRule
 */
export class UpdateBlockRuleCommand extends Command<
  UpdateBlockRuleRequest,
  UpdateBlockRuleCommandOutput,
  'UpdateBlockRuleCommand'
> {
  static readonly metaPath = '/UpdateBlockRule/2023-12-25/waf/post/application_json/';

  constructor(input: UpdateBlockRuleRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(UpdateBlockRuleCommand.metaPath);
  }
}
/**
 * Command to UpdateBotAnalyseProtectRule
 */
export class UpdateBotAnalyseProtectRuleCommand extends Command<
  UpdateBotAnalyseProtectRuleRequest,
  UpdateBotAnalyseProtectRuleCommandOutput,
  'UpdateBotAnalyseProtectRuleCommand'
> {
  static readonly metaPath = '/UpdateBotAnalyseProtectRule/2023-12-25/waf/post/application_json/';

  constructor(input: UpdateBotAnalyseProtectRuleRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(UpdateBotAnalyseProtectRuleCommand.metaPath);
  }
}
/**
 * Command to UpdateCCRule
 */
export class UpdateCCRuleCommand extends Command<
  UpdateCCRuleRequest,
  UpdateCCRuleCommandOutput,
  'UpdateCCRuleCommand'
> {
  static readonly metaPath = '/UpdateCCRule/2023-12-25/waf/post/application_json/';

  constructor(input: UpdateCCRuleRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(UpdateCCRuleCommand.metaPath);
  }
}
/**
 * Command to UpdateCustomBotConfig
 */
export class UpdateCustomBotConfigCommand extends Command<
  UpdateCustomBotConfigRequest,
  UpdateCustomBotConfigCommandOutput,
  'UpdateCustomBotConfigCommand'
> {
  static readonly metaPath = '/UpdateCustomBotConfig/2023-12-25/waf/post/application_json/';

  constructor(input: UpdateCustomBotConfigRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(UpdateCustomBotConfigCommand.metaPath);
  }
}
/**
 * Command to UpdateCustomPage
 */
export class UpdateCustomPageCommand extends Command<
  UpdateCustomPageRequest,
  UpdateCustomPageCommandOutput,
  'UpdateCustomPageCommand'
> {
  static readonly metaPath = '/UpdateCustomPage/2023-12-25/waf/post/application_json/';

  constructor(input: UpdateCustomPageRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(UpdateCustomPageCommand.metaPath);
  }
}
/**
 * Command to UpdateCustomSystemVulRule
 */
export class UpdateCustomSystemVulRuleCommand extends Command<
  UpdateCustomSystemVulRuleRequest,
  UpdateCustomSystemVulRuleCommandOutput,
  'UpdateCustomSystemVulRuleCommand'
> {
  static readonly metaPath = '/UpdateCustomSystemVulRule/2023-12-25/waf/post/application_json/';

  constructor(input: UpdateCustomSystemVulRuleRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(UpdateCustomSystemVulRuleCommand.metaPath);
  }
}
/**
 * Command to UpdateDomain
 */
export class UpdateDomainCommand extends Command<
  UpdateDomainRequest,
  UpdateDomainCommandOutput,
  'UpdateDomainCommand'
> {
  static readonly metaPath = '/UpdateDomain/2023-12-25/waf/post/application_json/';

  constructor(input: UpdateDomainRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(UpdateDomainCommand.metaPath);
  }
}
/**
 * Command to UpdateHostGroup
 */
export class UpdateHostGroupCommand extends Command<
  UpdateHostGroupRequest,
  UpdateHostGroupCommandOutput,
  'UpdateHostGroupCommand'
> {
  static readonly metaPath = '/UpdateHostGroup/2023-12-25/waf/post/application_json/';

  constructor(input: UpdateHostGroupRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(UpdateHostGroupCommand.metaPath);
  }
}
/**
 * Command to UpdateInstanceCtl
 */
export class UpdateInstanceCtlCommand extends Command<
  UpdateInstanceCtlRequest,
  UpdateInstanceCtlCommandOutput,
  'UpdateInstanceCtlCommand'
> {
  static readonly metaPath = '/UpdateInstanceCtl/2023-12-25/waf/post/application_json/';

  constructor(input: UpdateInstanceCtlRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(UpdateInstanceCtlCommand.metaPath);
  }
}
/**
 * Command to UpdateIpGroup
 */
export class UpdateIpGroupCommand extends Command<
  UpdateIpGroupRequest,
  UpdateIpGroupCommandOutput,
  'UpdateIpGroupCommand'
> {
  static readonly metaPath = '/UpdateIpGroup/2023-12-25/waf/post/application_json/';

  constructor(input: UpdateIpGroupRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(UpdateIpGroupCommand.metaPath);
  }
}
/**
 * Command to UpdateSystemBotConfig
 */
export class UpdateSystemBotConfigCommand extends Command<
  UpdateSystemBotConfigRequest,
  UpdateSystemBotConfigCommandOutput,
  'UpdateSystemBotConfigCommand'
> {
  static readonly metaPath = '/UpdateSystemBotConfig/2023-12-25/waf/post/application_json/';

  constructor(input: UpdateSystemBotConfigRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(UpdateSystemBotConfigCommand.metaPath);
  }
}
/**
 * Command to UpdateTamperProof
 */
export class UpdateTamperProofCommand extends Command<
  UpdateTamperProofRequest,
  UpdateTamperProofCommandOutput,
  'UpdateTamperProofCommand'
> {
  static readonly metaPath = '/UpdateTamperProof/2023-12-25/waf/post/application_json/';

  constructor(input: UpdateTamperProofRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(UpdateTamperProofCommand.metaPath);
  }
}
/**
 * Command to UpdateTamperProofCache
 */
export class UpdateTamperProofCacheCommand extends Command<
  UpdateTamperProofCacheRequest,
  UpdateTamperProofCacheCommandOutput,
  'UpdateTamperProofCacheCommand'
> {
  static readonly metaPath = '/UpdateTamperProofCache/2023-12-25/waf/post/application_json/';

  constructor(input: UpdateTamperProofCacheRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(UpdateTamperProofCacheCommand.metaPath);
  }
}
/**
 * Command to UpdateVulWhiteField
 */
export class UpdateVulWhiteFieldCommand extends Command<
  UpdateVulWhiteFieldRequest,
  UpdateVulWhiteFieldCommandOutput,
  'UpdateVulWhiteFieldCommand'
> {
  static readonly metaPath = '/UpdateVulWhiteField/2023-12-25/waf/post/application_json/';

  constructor(input: UpdateVulWhiteFieldRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(UpdateVulWhiteFieldCommand.metaPath);
  }
}
/**
 * Command to UpdateVulnerabilityConfig
 */
export class UpdateVulnerabilityConfigCommand extends Command<
  UpdateVulnerabilityConfigRequest,
  UpdateVulnerabilityConfigCommandOutput,
  'UpdateVulnerabilityConfigCommand'
> {
  static readonly metaPath = '/UpdateVulnerabilityConfig/2023-12-25/waf/post/application_json/';

  constructor(input: UpdateVulnerabilityConfigRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(UpdateVulnerabilityConfigCommand.metaPath);
  }
}
/**
 * Command to UpdateWafServiceControl
 */
export class UpdateWafServiceControlCommand extends Command<
  UpdateWafServiceControlRequest,
  UpdateWafServiceControlCommandOutput,
  'UpdateWafServiceControlCommand'
> {
  static readonly metaPath = '/UpdateWafServiceControl/2023-12-25/waf/post/application_json/';

  constructor(input: UpdateWafServiceControlRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(UpdateWafServiceControlCommand.metaPath);
  }
}
/**
 * Command to UploadWafServiceCertificate
 */
export class UploadWafServiceCertificateCommand extends Command<
  UploadWafServiceCertificateRequest,
  UploadWafServiceCertificateCommandOutput,
  'UploadWafServiceCertificateCommand'
> {
  static readonly metaPath = '/UploadWafServiceCertificate/2023-12-25/waf/post/application_json/';

  constructor(input: UploadWafServiceCertificateRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(UploadWafServiceCertificateCommand.metaPath);
  }
}

export default {
  WAFClient,
  AddHostGroupCommand,
  AddIpGroupCommand,
  AddProhibitionBlackCommand,
  AddProhibitionWhiteCommand,
  BatchUpdateTLSFieldsConfigCommand,
  CheckLLMPromptCommand,
  CheckLLMResponseStreamCommand,
  CreateAclRuleCommand,
  CreateAllowRuleCommand,
  CreateBlockRuleCommand,
  CreateBotAnalyseProtectRuleCommand,
  CreateCCRuleCommand,
  CreateCustomBotConfigCommand,
  CreateCustomPageCommand,
  CreateDomainCommand,
  CreateTamperProofCommand,
  CreateVulWhiteFieldCommand,
  DeleteAclRuleCommand,
  DeleteAllowRuleCommand,
  DeleteBlockRuleCommand,
  DeleteBotAnalyseProtectRuleCommand,
  DeleteCCRuleCommand,
  DeleteCustomBotConfigCommand,
  DeleteCustomPageCommand,
  DeleteDomainCommand,
  DeleteHostGroupCommand,
  DeleteIpGroupCommand,
  DeleteProhibitionBlackCommand,
  DeleteProhibitionWhiteCommand,
  DeleteTamperProofCommand,
  DeleteVulWhiteFieldCommand,
  DeleteWafServiceCertificateCommand,
  GetDomainInfoCommand,
  GetInstanceCtlCommand,
  GetReqQPSAnalysisCommand,
  GetTLSConfigCommand,
  GetVulnerabilityConfigCommand,
  ListAclRuleCommand,
  ListAllIpGroupsCommand,
  ListAllowRuleCommand,
  ListAreaBlockRuleCommand,
  ListBlockRuleCommand,
  ListBotAnalyseProtectRuleCommand,
  ListBotAnalyseProtectRulePriorityAvailableCommand,
  ListCCRuleCommand,
  ListCertificateServicesCommand,
  ListCustomBotConfigCommand,
  ListCustomPageCommand,
  ListDomainCommand,
  ListHostGroupCommand,
  ListIpGroupCommand,
  ListLoadBalancerCommand,
  ListProhibitionCommand,
  ListSystemBotConfigCommand,
  ListTamperProofCommand,
  ListVulWhiteFieldCommand,
  ListVulnerabilityRuleCommand,
  ListWafServiceCertificateCommand,
  ModifyServiceDefenceModeCommand,
  ModifyTLSConfigCommand,
  QueryAttackAnalysisTermsAggLbCommand,
  QueryAttackAnalysisWithRuleAggLbCommand,
  QueryAttackSecurityEventCommand,
  QueryCertificateIfReplaceCommand,
  QueryFlowOverviewLbCommand,
  QueryLLMGenerateCommand,
  QueryProtectionOverviewLbCommand,
  UpdateAclRuleCommand,
  UpdateAllowRuleCommand,
  UpdateAreaBlockRuleCommand,
  UpdateBlockRuleCommand,
  UpdateBotAnalyseProtectRuleCommand,
  UpdateCCRuleCommand,
  UpdateCustomBotConfigCommand,
  UpdateCustomPageCommand,
  UpdateCustomSystemVulRuleCommand,
  UpdateDomainCommand,
  UpdateHostGroupCommand,
  UpdateInstanceCtlCommand,
  UpdateIpGroupCommand,
  UpdateSystemBotConfigCommand,
  UpdateTamperProofCommand,
  UpdateTamperProofCacheCommand,
  UpdateVulWhiteFieldCommand,
  UpdateVulnerabilityConfigCommand,
  UpdateWafServiceControlCommand,
  UploadWafServiceCertificateCommand,
};
