/* tslint:disable */
/* eslint-disable */
/**
 * iam20210801
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: common-version
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Client, ClientConfig, Command, buildRequestConfigFromMetaPath, CommandOutput } from '@volcengine/sdk-core';

import { AttachPolicyInProjectRequest } from './types/index';
import { AttachPolicyInProjectResponse } from './types/index';
import { CreateProjectRequest } from './types/index';
import { CreateProjectResponse } from './types/index';
import { DeleteProjectRequest } from './types/index';
import { DeleteProjectResponse } from './types/index';
import { DetachPolicyInProjectRequest } from './types/index';
import { DetachPolicyInProjectResponse } from './types/index';
import { GetProjectRequest } from './types/index';
import { GetProjectResponse } from './types/index';
import { ListProjectIdentitiesRequest } from './types/index';
import { ListProjectIdentitiesResponse } from './types/index';
import { ListProjectResourcesRequest } from './types/index';
import { ListProjectResourcesResponse } from './types/index';
import { ListProjectsRequest } from './types/index';
import { ListProjectsResponse } from './types/index';
import { MoveProjectResourceRequest } from './types/index';
import { MoveProjectResourceResponse } from './types/index';
import { UpdateProjectRequest } from './types/index';
import { UpdateProjectResponse } from './types/index';

// ============================================================================
// Output Type Definitions
// ============================================================================
export type AttachPolicyInProjectCommandOutput = CommandOutput<AttachPolicyInProjectResponse>;
export type CreateProjectCommandOutput = CommandOutput<CreateProjectResponse>;
export type DeleteProjectCommandOutput = CommandOutput<DeleteProjectResponse>;
export type DetachPolicyInProjectCommandOutput = CommandOutput<DetachPolicyInProjectResponse>;
export type GetProjectCommandOutput = CommandOutput<GetProjectResponse>;
export type ListProjectIdentitiesCommandOutput = CommandOutput<ListProjectIdentitiesResponse>;
export type ListProjectResourcesCommandOutput = CommandOutput<ListProjectResourcesResponse>;
export type ListProjectsCommandOutput = CommandOutput<ListProjectsResponse>;
export type MoveProjectResourceCommandOutput = CommandOutput<MoveProjectResourceResponse>;
export type UpdateProjectCommandOutput = CommandOutput<UpdateProjectResponse>;


/**
 * IAM20210801Client Service Client
 */
export class IAM20210801Client extends Client {
  constructor(config: ClientConfig = {}) {
    super({
      protocol: 'https',
      region: 'cn-beijing',
      ...config,
    });
  }
}

/**
 * Command to AttachPolicyInProject
 */
export class AttachPolicyInProjectCommand extends Command<
  AttachPolicyInProjectRequest,
  AttachPolicyInProjectCommandOutput,
  'AttachPolicyInProjectCommand'
> {
  static readonly metaPath = '/AttachPolicyInProject/2021-08-01/iam/get/text_plain/';

  constructor(input: AttachPolicyInProjectRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(AttachPolicyInProjectCommand.metaPath);
  }
}
/**
 * Command to CreateProject
 */
export class CreateProjectCommand extends Command<
  CreateProjectRequest,
  CreateProjectCommandOutput,
  'CreateProjectCommand'
> {
  static readonly metaPath = '/CreateProject/2021-08-01/iam/get/text_plain/';

  constructor(input: CreateProjectRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(CreateProjectCommand.metaPath);
  }
}
/**
 * Command to DeleteProject
 */
export class DeleteProjectCommand extends Command<
  DeleteProjectRequest,
  DeleteProjectCommandOutput,
  'DeleteProjectCommand'
> {
  static readonly metaPath = '/DeleteProject/2021-08-01/iam/get/text_plain/';

  constructor(input: DeleteProjectRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(DeleteProjectCommand.metaPath);
  }
}
/**
 * Command to DetachPolicyInProject
 */
export class DetachPolicyInProjectCommand extends Command<
  DetachPolicyInProjectRequest,
  DetachPolicyInProjectCommandOutput,
  'DetachPolicyInProjectCommand'
> {
  static readonly metaPath = '/DetachPolicyInProject/2021-08-01/iam/get/text_plain/';

  constructor(input: DetachPolicyInProjectRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(DetachPolicyInProjectCommand.metaPath);
  }
}
/**
 * Command to GetProject
 */
export class GetProjectCommand extends Command<
  GetProjectRequest,
  GetProjectCommandOutput,
  'GetProjectCommand'
> {
  static readonly metaPath = '/GetProject/2021-08-01/iam/get/text_plain/';

  constructor(input: GetProjectRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(GetProjectCommand.metaPath);
  }
}
/**
 * Command to ListProjectIdentities
 */
export class ListProjectIdentitiesCommand extends Command<
  ListProjectIdentitiesRequest,
  ListProjectIdentitiesCommandOutput,
  'ListProjectIdentitiesCommand'
> {
  static readonly metaPath = '/ListProjectIdentities/2021-08-01/iam/get/text_plain/';

  constructor(input: ListProjectIdentitiesRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(ListProjectIdentitiesCommand.metaPath);
  }
}
/**
 * Command to ListProjectResources
 */
export class ListProjectResourcesCommand extends Command<
  ListProjectResourcesRequest,
  ListProjectResourcesCommandOutput,
  'ListProjectResourcesCommand'
> {
  static readonly metaPath = '/ListProjectResources/2021-08-01/iam/get/text_plain/';

  constructor(input: ListProjectResourcesRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(ListProjectResourcesCommand.metaPath);
  }
}
/**
 * Command to ListProjects
 */
export class ListProjectsCommand extends Command<
  ListProjectsRequest,
  ListProjectsCommandOutput,
  'ListProjectsCommand'
> {
  static readonly metaPath = '/ListProjects/2021-08-01/iam/get/text_plain/';

  constructor(input: ListProjectsRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(ListProjectsCommand.metaPath);
  }
}
/**
 * Command to MoveProjectResource
 */
export class MoveProjectResourceCommand extends Command<
  MoveProjectResourceRequest,
  MoveProjectResourceCommandOutput,
  'MoveProjectResourceCommand'
> {
  static readonly metaPath = '/MoveProjectResource/2021-08-01/iam/get/text_plain/';

  constructor(input: MoveProjectResourceRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(MoveProjectResourceCommand.metaPath);
  }
}
/**
 * Command to UpdateProject
 */
export class UpdateProjectCommand extends Command<
  UpdateProjectRequest,
  UpdateProjectCommandOutput,
  'UpdateProjectCommand'
> {
  static readonly metaPath = '/UpdateProject/2021-08-01/iam/get/text_plain/';

  constructor(input: UpdateProjectRequest) {
    super(input);
    this.requestConfig = buildRequestConfigFromMetaPath(UpdateProjectCommand.metaPath);
  }
}

export default {
  IAM20210801Client,
  AttachPolicyInProjectCommand,
  CreateProjectCommand,
  DeleteProjectCommand,
  DetachPolicyInProjectCommand,
  GetProjectCommand,
  ListProjectIdentitiesCommand,
  ListProjectResourcesCommand,
  ListProjectsCommand,
  MoveProjectResourceCommand,
  UpdateProjectCommand,
};
